/* theodoratranscode.c generated by valac 0.18.1, the Vala compiler
 * generated from theodoratranscode.vala, do not modify */

/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * theodoratranscode.c
 * Copyright (C) 2013 Wolfgang Pirker <w_pirker@gmx.de>
 * 
 * theodoratranscode is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * theodoratranscode is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include "config.h"
#include <glib/gstdio.h>
#include <stdio.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define NS_WIDGETS_TYPE_ADJUSTMENT (ns_widgets_adjustment_get_type ())
#define NS_WIDGETS_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustment))
#define NS_WIDGETS_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustmentClass))
#define NS_WIDGETS_IS_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_WIDGETS_TYPE_ADJUSTMENT))
#define NS_WIDGETS_IS_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_WIDGETS_TYPE_ADJUSTMENT))
#define NS_WIDGETS_ADJUSTMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustmentClass))

typedef struct _NSWidgetsAdjustment NSWidgetsAdjustment;
typedef struct _NSWidgetsAdjustmentClass NSWidgetsAdjustmentClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _Main {
	GtkApplication parent_instance;
	MainPrivate * priv;
	GtkBuilder* builder;
	GtkLabel* advice_label;
	GtkInfoBar* infobar;
	GtkInfoBar* error_infbar;
	GtkLabel* lbl_video;
	GtkLabel* lbl_audio;
	GtkLabel* lbl_other;
};

struct _MainClass {
	GtkApplicationClass parent_class;
};

struct _MainPrivate {
	gboolean gtk_builder_without_infobars;
	gchar* _active_tab;
};


static gpointer main_parent_class = NULL;

GType main_get_type (void) G_GNUC_CONST;
#define MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN, MainPrivate))
enum  {
	MAIN_DUMMY_PROPERTY,
	MAIN_ACTIVE_TAB
};
#define MAIN_LAST_PROFILE "most recent"
#define MAIN_PROFILE_PATH "/.local/share/theodora-transcode/"
#define MAIN_PROFILE_MODE1 "config_last"

/* UI file 
 uncomment this line if it is located at /usr/local/share/theodoratranscode/theodoratranscode.ui */
// #define MAIN_UI_FILE PACKAGE_DATA_DIR "/" "theodoratranscode.ui"

/* uncomment this line, if you just testing and not want to install this application */
#define MAIN_UI_FILE "src/theodoratranscode.ui"


Main* main_new (void);
Main* main_construct (GType object_type);
gint ns_file_cd (const gchar* new_path, gboolean relative_to_home);
NSWidgetsAdjustment* ns_widgets_adjustment_new (const gchar* profile, gboolean startup);
NSWidgetsAdjustment* ns_widgets_adjustment_construct (GType object_type, const gchar* profile, gboolean startup);
GType ns_widgets_adjustment_get_type (void) G_GNUC_CONST;
void ns_widgets_adjustment_adjust_widgets (NSWidgetsAdjustment* self, GtkBuilder* _builder);
void main_built_infbar_layout (Main* self, GtkMessageType type, const gchar* message, const gchar* button);
static void ___lambda3_ (Main* self);
static void ____lambda3__gtk_info_bar_response (GtkInfoBar* _sender, gint response_id, gpointer self);
static gint main_main (gchar** args, int args_length1);
const gchar* main_get_active_tab (Main* self);
void main_set_active_tab (Main* self, const gchar* value);
static void main_finalize (GObject* obj);
static void _vala_main_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_main_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


Main* main_construct (GType object_type) {
	Main * self = NULL;
	GtkBuilder* _tmp15_;
	GObject* _tmp16_ = NULL;
	GtkInfoBar* _tmp17_;
	GtkInfoBar* test_infobar;
	GtkInfoBar* _tmp18_;
	GError * _inner_error_ = NULL;
	self = (Main*) g_object_new (object_type, NULL);
	{
		GtkLabel* _tmp0_;
		GtkBuilder* _tmp1_;
		GtkBuilder* _tmp2_;
		GtkBuilder* _tmp3_;
		GtkBuilder* _tmp4_;
		GObject* _tmp5_ = NULL;
		GtkWindow* _tmp6_;
		GtkWindow* window;
		GtkWindow* _tmp7_;
		gboolean _tmp8_ = FALSE;
		_tmp0_ = (GtkLabel*) gtk_label_new ("In case a filename is entered as target, the file will " "be stored in your home user directory.\n\n" "Tips on Subtitle section\n" "if you want to specify more than one subtitle, " "you can do this via Other→parameters.\n" "if you leave the encoding field blank, UTF-8 will be " "used, which works in most cases.\n" "For a list of supported encodings you can use the " "'iconv -l' command.\n.");
		g_object_ref_sink (_tmp0_);
		_g_object_unref0 (self->advice_label);
		self->advice_label = _tmp0_;
		_tmp1_ = gtk_builder_new ();
		_g_object_unref0 (self->builder);
		self->builder = G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_BUILDER) ? ((GtkBuilder*) _tmp1_) : NULL;
		_tmp2_ = self->builder;
		gtk_builder_add_from_file (_tmp2_, MAIN_UI_FILE, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		_tmp3_ = self->builder;
		gtk_builder_connect_signals (_tmp3_, self);
		_tmp4_ = self->builder;
		_tmp5_ = gtk_builder_get_object (_tmp4_, "window");
		_tmp6_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, GTK_TYPE_WINDOW) ? ((GtkWindow*) _tmp5_) : NULL);
		window = _tmp6_;
		_tmp7_ = window;
		gtk_widget_show_all ((GtkWidget*) _tmp7_);
		ns_file_cd (MAIN_PROFILE_PATH, TRUE);
		_tmp8_ = g_file_test (MAIN_PROFILE_MODE1 ".json", G_FILE_TEST_IS_REGULAR);
		if (_tmp8_ == TRUE) {
			NSWidgetsAdjustment* _tmp9_;
			NSWidgetsAdjustment* adjust;
			NSWidgetsAdjustment* _tmp10_;
			GtkBuilder* _tmp11_;
			_tmp9_ = ns_widgets_adjustment_new (MAIN_PROFILE_MODE1, TRUE);
			adjust = _tmp9_;
			_tmp10_ = adjust;
			_tmp11_ = self->builder;
			ns_widgets_adjustment_adjust_widgets (_tmp10_, _tmp11_);
			_g_object_unref0 (adjust);
		}
		_g_object_unref0 (window);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp12_;
		GError* _tmp13_;
		const gchar* _tmp14_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp12_ = stderr;
		_tmp13_ = e;
		_tmp14_ = _tmp13_->message;
		fprintf (_tmp12_, "Could not load UI: %s\n", _tmp14_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp15_ = self->builder;
	_tmp16_ = gtk_builder_get_object (_tmp15_, "infbar_basics");
	_tmp17_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp16_, GTK_TYPE_INFO_BAR) ? ((GtkInfoBar*) _tmp16_) : NULL);
	test_infobar = _tmp17_;
	_tmp18_ = test_infobar;
	if (_tmp18_ == NULL) {
		self->priv->gtk_builder_without_infobars = TRUE;
	}
	_g_object_unref0 (test_infobar);
	return self;
}


Main* main_new (void) {
	return main_construct (TYPE_MAIN);
}


static void ___lambda3_ (Main* self) {
	GtkInfoBar* _tmp0_;
	_tmp0_ = self->error_infbar;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
}


static void ____lambda3__gtk_info_bar_response (GtkInfoBar* _sender, gint response_id, gpointer self) {
	___lambda3_ (self);
}


void main_built_infbar_layout (Main* self, GtkMessageType type, const gchar* message, const gchar* button) {
	GtkInfoBar* _tmp0_;
	GtkImage* _tmp2_;
	GtkImage* error_image;
	GtkMessageType _tmp3_;
	GtkInfoBar* _tmp7_;
	GtkInfoBar* _tmp8_;
	GtkContainer* _tmp9_ = NULL;
	GtkContainer* _tmp10_;
	GtkContainer* error_infbar_ca;
	const gchar* _tmp11_;
	GtkLabel* _tmp12_;
	GtkLabel* error_label;
	GtkInfoBar* _tmp13_;
	GtkMessageType _tmp14_;
	GtkContainer* _tmp15_;
	GtkImage* _tmp16_;
	GtkContainer* _tmp17_;
	GtkLabel* _tmp18_;
	GtkBuilder* _tmp19_;
	GObject* _tmp20_ = NULL;
	GtkBox* _tmp21_;
	GtkBox* box;
	GtkBox* _tmp22_;
	GtkBox* _tmp23_;
	GtkInfoBar* _tmp24_;
	GtkImage* _tmp25_;
	GtkLabel* _tmp26_;
	GtkInfoBar* _tmp27_;
	const gchar* _tmp28_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (message != NULL);
	g_return_if_fail (button != NULL);
	_tmp0_ = self->error_infbar;
	if (_tmp0_ != NULL) {
		GtkInfoBar* _tmp1_;
		_tmp1_ = self->error_infbar;
		gtk_widget_destroy ((GtkWidget*) _tmp1_);
	}
	_tmp2_ = (GtkImage*) gtk_image_new_from_stock (GTK_STOCK_DIALOG_INFO, GTK_ICON_SIZE_DIALOG);
	g_object_ref_sink (_tmp2_);
	error_image = _tmp2_;
	_tmp3_ = type;
	if (_tmp3_ == GTK_MESSAGE_ERROR) {
		GtkImage* _tmp4_;
		_tmp4_ = (GtkImage*) gtk_image_new_from_stock (GTK_STOCK_DIALOG_ERROR, GTK_ICON_SIZE_DIALOG);
		g_object_ref_sink (_tmp4_);
		_g_object_unref0 (error_image);
		error_image = _tmp4_;
	} else {
		GtkMessageType _tmp5_;
		_tmp5_ = type;
		if (_tmp5_ == GTK_MESSAGE_WARNING) {
			GtkImage* _tmp6_;
			_tmp6_ = (GtkImage*) gtk_image_new_from_stock (GTK_STOCK_DIALOG_WARNING, GTK_ICON_SIZE_DIALOG);
			g_object_ref_sink (_tmp6_);
			_g_object_unref0 (error_image);
			error_image = _tmp6_;
		}
	}
	_tmp7_ = (GtkInfoBar*) gtk_info_bar_new ();
	g_object_ref_sink (_tmp7_);
	_g_object_unref0 (self->error_infbar);
	self->error_infbar = G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, GTK_TYPE_INFO_BAR) ? ((GtkInfoBar*) _tmp7_) : NULL;
	_tmp8_ = self->error_infbar;
	_tmp9_ = gtk_info_bar_get_content_area (_tmp8_);
	_tmp10_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp9_, GTK_TYPE_CONTAINER) ? ((GtkContainer*) _tmp9_) : NULL);
	error_infbar_ca = _tmp10_;
	_tmp11_ = message;
	_tmp12_ = (GtkLabel*) gtk_label_new (_tmp11_);
	g_object_ref_sink (_tmp12_);
	error_label = _tmp12_;
	_tmp13_ = self->error_infbar;
	_tmp14_ = type;
	gtk_info_bar_set_message_type (_tmp13_, _tmp14_);
	_tmp15_ = error_infbar_ca;
	_tmp16_ = error_image;
	gtk_container_add (_tmp15_, (GtkWidget*) _tmp16_);
	_tmp17_ = error_infbar_ca;
	_tmp18_ = error_label;
	gtk_container_add (_tmp17_, (GtkWidget*) _tmp18_);
	_tmp19_ = self->builder;
	_tmp20_ = gtk_builder_get_object (_tmp19_, "box_on_top_of_sbar");
	_tmp21_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp20_, GTK_TYPE_BOX) ? ((GtkBox*) _tmp20_) : NULL);
	box = _tmp21_;
	_tmp22_ = box;
	gtk_widget_show ((GtkWidget*) _tmp22_);
	_tmp23_ = box;
	_tmp24_ = self->error_infbar;
	gtk_box_pack_end (_tmp23_, (GtkWidget*) _tmp24_, TRUE, TRUE, (guint) 5);
	_tmp25_ = error_image;
	gtk_widget_show ((GtkWidget*) _tmp25_);
	_tmp26_ = error_label;
	gtk_widget_show ((GtkWidget*) _tmp26_);
	_tmp27_ = self->error_infbar;
	gtk_widget_show ((GtkWidget*) _tmp27_);
	_tmp28_ = button;
	if (g_strcmp0 (_tmp28_, "") != 0) {
		GtkInfoBar* _tmp29_;
		GtkInfoBar* _tmp30_;
		_tmp29_ = self->error_infbar;
		gtk_info_bar_add_button (_tmp29_, "Hide", (gint) GTK_RESPONSE_CLOSE);
		_tmp30_ = self->error_infbar;
		g_signal_connect_object (_tmp30_, "response", (GCallback) ____lambda3__gtk_info_bar_response, self, 0);
	}
	_g_object_unref0 (box);
	_g_object_unref0 (error_label);
	_g_object_unref0 (error_infbar_ca);
	_g_object_unref0 (error_image);
}


static gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	Main* _tmp0_;
	Main* app;
	gtk_init (&args_length1, &args);
	_tmp0_ = main_new ();
	app = _tmp0_;
	gtk_main ();
	result = 0;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return main_main (argv, argc);
}


const gchar* main_get_active_tab (Main* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_active_tab;
	result = _tmp0_;
	return result;
}


void main_set_active_tab (Main* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_active_tab);
	self->priv->_active_tab = _tmp1_;
	g_object_notify ((GObject *) self, "active-tab");
}


static void main_class_init (MainClass * klass) {
	main_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_main_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_main_set_property;
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MAIN_ACTIVE_TAB, g_param_spec_string ("active-tab", "active-tab", "active-tab", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void main_instance_init (Main * self) {
	gchar* _tmp0_;
	self->priv = MAIN_GET_PRIVATE (self);
	self->priv->gtk_builder_without_infobars = FALSE;
	_tmp0_ = g_strdup ("basics");
	self->priv->_active_tab = _tmp0_;
}


static void main_finalize (GObject* obj) {
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
	_g_object_unref0 (self->builder);
	_g_object_unref0 (self->advice_label);
	_g_object_unref0 (self->infobar);
	_g_object_unref0 (self->error_infbar);
	_g_object_unref0 (self->lbl_video);
	_g_object_unref0 (self->lbl_audio);
	_g_object_unref0 (self->lbl_other);
	_g_free0 (self->priv->_active_tab);
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (GTK_TYPE_APPLICATION, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}


static void _vala_main_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_MAIN, Main);
	switch (property_id) {
		case MAIN_ACTIVE_TAB:
		g_value_set_string (value, main_get_active_tab (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_main_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_MAIN, Main);
	switch (property_id) {
		case MAIN_ACTIVE_TAB:
		main_set_active_tab (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



