/* widgets-profile.c generated by valac 0.18.1, the Vala compiler
 * generated from widgets-profile.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <stdio.h>
#include <glib/gstdio.h>


#define NS_WIDGETS_TYPE_PROFILE_NAMES (ns_widgets_profile_names_get_type ())
#define NS_WIDGETS_PROFILE_NAMES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_WIDGETS_TYPE_PROFILE_NAMES, NSWidgetsProfileNames))
#define NS_WIDGETS_PROFILE_NAMES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_WIDGETS_TYPE_PROFILE_NAMES, NSWidgetsProfileNamesClass))
#define NS_WIDGETS_IS_PROFILE_NAMES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_WIDGETS_TYPE_PROFILE_NAMES))
#define NS_WIDGETS_IS_PROFILE_NAMES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_WIDGETS_TYPE_PROFILE_NAMES))
#define NS_WIDGETS_PROFILE_NAMES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_WIDGETS_TYPE_PROFILE_NAMES, NSWidgetsProfileNamesClass))

typedef struct _NSWidgetsProfileNames NSWidgetsProfileNames;
typedef struct _NSWidgetsProfileNamesClass NSWidgetsProfileNamesClass;
typedef struct _NSWidgetsProfileNamesPrivate NSWidgetsProfileNamesPrivate;
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))

#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define NS_WIDGETS_TYPE_PROFILE (ns_widgets_profile_get_type ())
#define NS_WIDGETS_PROFILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_WIDGETS_TYPE_PROFILE, NSWidgetsProfile))
#define NS_WIDGETS_PROFILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_WIDGETS_TYPE_PROFILE, NSWidgetsProfileClass))
#define NS_WIDGETS_IS_PROFILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_WIDGETS_TYPE_PROFILE))
#define NS_WIDGETS_IS_PROFILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_WIDGETS_TYPE_PROFILE))
#define NS_WIDGETS_PROFILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_WIDGETS_TYPE_PROFILE, NSWidgetsProfileClass))

typedef struct _NSWidgetsProfile NSWidgetsProfile;
typedef struct _NSWidgetsProfileClass NSWidgetsProfileClass;
typedef struct _NSWidgetsProfilePrivate NSWidgetsProfilePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block4Data Block4Data;

#define NS_WIDGETS_TYPE_ADJUSTMENT (ns_widgets_adjustment_get_type ())
#define NS_WIDGETS_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustment))
#define NS_WIDGETS_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustmentClass))
#define NS_WIDGETS_IS_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_WIDGETS_TYPE_ADJUSTMENT))
#define NS_WIDGETS_IS_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_WIDGETS_TYPE_ADJUSTMENT))
#define NS_WIDGETS_ADJUSTMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustmentClass))

typedef struct _NSWidgetsAdjustment NSWidgetsAdjustment;
typedef struct _NSWidgetsAdjustmentClass NSWidgetsAdjustmentClass;

struct _NSWidgetsProfileNames {
	GObject parent_instance;
	NSWidgetsProfileNamesPrivate * priv;
};

struct _NSWidgetsProfileNamesClass {
	GObjectClass parent_class;
};

struct _NSWidgetsProfileNamesPrivate {
	GList* _profiles;
};

struct _Main {
	GtkApplication parent_instance;
	MainPrivate * priv;
	GtkBuilder* builder;
	GtkLabel* advice_label;
	GtkInfoBar* infobar;
	GtkInfoBar* error_infbar;
	GtkLabel* lbl_video;
	GtkLabel* lbl_audio;
	GtkLabel* lbl_other;
};

struct _MainClass {
	GtkApplicationClass parent_class;
};

struct _NSWidgetsProfile {
	Main parent_instance;
	NSWidgetsProfilePrivate * priv;
};

struct _NSWidgetsProfileClass {
	MainClass parent_class;
};

struct _Block4Data {
	int _ref_count_;
	NSWidgetsProfile * self;
	GtkComboBoxText* cboxt;
};


static gpointer ns_widgets_profile_names_parent_class = NULL;
static gpointer ns_widgets_profile_parent_class = NULL;
static gchar* ns_widgets_profile_previous_name;
static gchar* ns_widgets_profile_previous_name = NULL;
static gint ns_widgets_profile_previously_active;
static gint ns_widgets_profile_previously_active = 0 - 1;

GType ns_widgets_profile_names_get_type (void) G_GNUC_CONST;
#define NS_WIDGETS_PROFILE_NAMES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), NS_WIDGETS_TYPE_PROFILE_NAMES, NSWidgetsProfileNamesPrivate))
enum  {
	NS_WIDGETS_PROFILE_NAMES_DUMMY_PROPERTY,
	NS_WIDGETS_PROFILE_NAMES_PROFILES
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
NSWidgetsProfileNames* ns_widgets_profile_names_new (void);
NSWidgetsProfileNames* ns_widgets_profile_names_construct (GType object_type);
static void ns_widgets_profile_names_update (NSWidgetsProfileNames* self);
GList* ns_file_dir (const gchar* path, gboolean relative_to_home, const gchar* prefix, const gchar* suffix);
#define MAIN_PROFILE_PATH "/.local/share/theodora-transcode/"
GList* ns_widgets_profile_names_get_profiles (NSWidgetsProfileNames* self);
static void ns_widgets_profile_names_finalize (GObject* obj);
static void _vala_ns_widgets_profile_names_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
GType main_get_type (void) G_GNUC_CONST;
GType ns_widgets_profile_get_type (void) G_GNUC_CONST;
enum  {
	NS_WIDGETS_PROFILE_DUMMY_PROPERTY
};
NSWidgetsProfile* ns_widgets_profile_new (void);
NSWidgetsProfile* ns_widgets_profile_construct (GType object_type);
Main* main_new (void);
Main* main_construct (GType object_type);
void on_e_profile_icon_press (GtkEntry* entry, GtkEntryIconPosition pos, NSWidgetsProfile* self);
void on_e_profile_activate (GtkEntry* entry, NSWidgetsProfile* self);
void ns_widgets_profile_delete_profile (NSWidgetsProfile* self, const gchar* profile);
static void ns_widgets_profile_push_statusbar_message (NSWidgetsProfile* self, const gchar* message);
void ns_widgets_profile_update_cboxt (NSWidgetsProfile* self, GtkComboBoxText* cboxt);
gint ns_file_cd (const gchar* new_path, gboolean relative_to_home);
void on_btn_delete_profile_clicked (GtkButton* sender, GtkEntry* entry, NSWidgetsProfile* self);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
static void __lambda9_ (Block4Data* _data4_, const gchar* profile);
static void ___lambda9__gfunc (gconstpointer data, gpointer self);
void on_infbar_profiles_show (GtkInfoBar* infbar_profiles, NSWidgetsProfile* self);
void on_btn_new_profile_clicked (GtkButton* sender, GtkEntry* entry, NSWidgetsProfile* self);
void on_cboxt_profile_changed (GtkComboBox* cbox, NSWidgetsProfile* self);
NSWidgetsAdjustment* ns_widgets_adjustment_new (const gchar* profile, gboolean startup);
NSWidgetsAdjustment* ns_widgets_adjustment_construct (GType object_type, const gchar* profile, gboolean startup);
GType ns_widgets_adjustment_get_type (void) G_GNUC_CONST;
void ns_widgets_adjustment_adjust_widgets (NSWidgetsAdjustment* self, GtkBuilder* _builder);
static void ns_widgets_profile_finalize (GObject* obj);


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


NSWidgetsProfileNames* ns_widgets_profile_names_construct (GType object_type) {
	NSWidgetsProfileNames * self = NULL;
	self = (NSWidgetsProfileNames*) g_object_new (object_type, NULL);
	ns_widgets_profile_names_update (self);
	return self;
}


NSWidgetsProfileNames* ns_widgets_profile_names_new (void) {
	return ns_widgets_profile_names_construct (NS_WIDGETS_TYPE_PROFILE_NAMES);
}


static void ns_widgets_profile_names_update (NSWidgetsProfileNames* self) {
	GList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = ns_file_dir (MAIN_PROFILE_PATH, TRUE, "profile_", ".json");
	__g_list_free__g_free0_0 (self->priv->_profiles);
	self->priv->_profiles = _tmp0_;
}


GList* ns_widgets_profile_names_get_profiles (NSWidgetsProfileNames* self) {
	GList* result;
	GList* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_profiles;
	result = _tmp0_;
	return result;
}


static void ns_widgets_profile_names_class_init (NSWidgetsProfileNamesClass * klass) {
	ns_widgets_profile_names_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (NSWidgetsProfileNamesPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_ns_widgets_profile_names_get_property;
	G_OBJECT_CLASS (klass)->finalize = ns_widgets_profile_names_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), NS_WIDGETS_PROFILE_NAMES_PROFILES, g_param_spec_pointer ("profiles", "profiles", "profiles", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void ns_widgets_profile_names_instance_init (NSWidgetsProfileNames * self) {
	self->priv = NS_WIDGETS_PROFILE_NAMES_GET_PRIVATE (self);
}


static void ns_widgets_profile_names_finalize (GObject* obj) {
	NSWidgetsProfileNames * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NS_WIDGETS_TYPE_PROFILE_NAMES, NSWidgetsProfileNames);
	__g_list_free__g_free0_0 (self->priv->_profiles);
	G_OBJECT_CLASS (ns_widgets_profile_names_parent_class)->finalize (obj);
}


GType ns_widgets_profile_names_get_type (void) {
	static volatile gsize ns_widgets_profile_names_type_id__volatile = 0;
	if (g_once_init_enter (&ns_widgets_profile_names_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (NSWidgetsProfileNamesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ns_widgets_profile_names_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NSWidgetsProfileNames), 0, (GInstanceInitFunc) ns_widgets_profile_names_instance_init, NULL };
		GType ns_widgets_profile_names_type_id;
		ns_widgets_profile_names_type_id = g_type_register_static (G_TYPE_OBJECT, "NSWidgetsProfileNames", &g_define_type_info, 0);
		g_once_init_leave (&ns_widgets_profile_names_type_id__volatile, ns_widgets_profile_names_type_id);
	}
	return ns_widgets_profile_names_type_id__volatile;
}


static void _vala_ns_widgets_profile_names_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	NSWidgetsProfileNames * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NS_WIDGETS_TYPE_PROFILE_NAMES, NSWidgetsProfileNames);
	switch (property_id) {
		case NS_WIDGETS_PROFILE_NAMES_PROFILES:
		g_value_set_pointer (value, ns_widgets_profile_names_get_profiles (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


NSWidgetsProfile* ns_widgets_profile_construct (GType object_type) {
	NSWidgetsProfile * self = NULL;
	FILE* _tmp0_;
	self = (NSWidgetsProfile*) main_construct (object_type);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Profile class\n\n");
	return self;
}


NSWidgetsProfile* ns_widgets_profile_new (void) {
	return ns_widgets_profile_construct (NS_WIDGETS_TYPE_PROFILE);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void on_e_profile_icon_press (GtkEntry* entry, GtkEntryIconPosition pos, NSWidgetsProfile* self) {
	GtkEntry* _tmp0_;
	GtkWidget* _tmp1_ = NULL;
	GtkComboBoxText* _tmp2_;
	GtkComboBoxText* cboxt;
	GtkEntryIconPosition _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (entry != NULL);
	_tmp0_ = entry;
	_tmp1_ = gtk_widget_get_parent ((GtkWidget*) _tmp0_);
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_COMBO_BOX_TEXT) ? ((GtkComboBoxText*) _tmp1_) : NULL);
	cboxt = _tmp2_;
	_tmp3_ = pos;
	if (_tmp3_ == GTK_ENTRY_ICON_PRIMARY) {
		GtkEntry* _tmp4_;
		const gchar* _tmp5_ = NULL;
		gchar* _tmp6_;
		GtkEntry* _tmp7_;
		GtkEntry* _tmp8_;
		GtkEntry* _tmp9_;
		GtkEntry* _tmp10_;
		_tmp4_ = entry;
		_tmp5_ = gtk_entry_get_text (_tmp4_);
		_tmp6_ = g_strdup (_tmp5_);
		_g_free0 (ns_widgets_profile_previous_name);
		ns_widgets_profile_previous_name = _tmp6_;
		_tmp7_ = entry;
		gtk_entry_set_icon_sensitive (_tmp7_, GTK_ENTRY_ICON_PRIMARY, FALSE);
		_tmp8_ = entry;
		gtk_widget_set_can_focus ((GtkWidget*) _tmp8_, TRUE);
		_tmp9_ = entry;
		gtk_widget_grab_focus ((GtkWidget*) _tmp9_);
		_tmp10_ = entry;
		gtk_entry_set_icon_sensitive (_tmp10_, GTK_ENTRY_ICON_SECONDARY, TRUE);
	} else {
		GtkEntry* _tmp11_;
		_tmp11_ = entry;
		g_signal_emit_by_name (_tmp11_, "activate");
	}
	_g_object_unref0 (cboxt);
}


void on_e_profile_activate (GtkEntry* entry, NSWidgetsProfile* self) {
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkButton* _tmp2_;
	GtkButton* button;
	GtkEntry* _tmp3_;
	GtkEntry* _tmp4_;
	GtkEntry* _tmp5_;
	GtkButton* _tmp6_;
	GtkButton* _tmp7_;
	const gchar* _tmp8_;
	GtkEntry* _tmp13_;
	GtkWidget* _tmp14_ = NULL;
	GtkComboBoxText* _tmp15_;
	GtkComboBoxText* cboxt;
	g_return_if_fail (self != NULL);
	g_return_if_fail (entry != NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "btn_save_profile");
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_BUTTON) ? ((GtkButton*) _tmp1_) : NULL);
	button = _tmp2_;
	_tmp3_ = entry;
	gtk_entry_set_icon_sensitive (_tmp3_, GTK_ENTRY_ICON_PRIMARY, TRUE);
	_tmp4_ = entry;
	gtk_widget_set_can_focus ((GtkWidget*) _tmp4_, FALSE);
	_tmp5_ = entry;
	gtk_entry_set_icon_sensitive (_tmp5_, GTK_ENTRY_ICON_SECONDARY, FALSE);
	_tmp6_ = button;
	gtk_button_clicked (_tmp6_);
	_tmp7_ = button;
	gtk_widget_grab_focus ((GtkWidget*) _tmp7_);
	_tmp8_ = ns_widgets_profile_previous_name;
	if (g_strcmp0 (_tmp8_, "") != 0) {
		const gchar* _tmp9_;
		const gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		_tmp9_ = ns_widgets_profile_previous_name;
		ns_widgets_profile_delete_profile (self, _tmp9_);
		_tmp10_ = ns_widgets_profile_previous_name;
		_tmp11_ = g_strconcat ("renamed profile ", _tmp10_, NULL);
		_tmp12_ = _tmp11_;
		ns_widgets_profile_push_statusbar_message (self, _tmp12_);
		_g_free0 (_tmp12_);
	}
	_tmp13_ = entry;
	_tmp14_ = gtk_widget_get_parent ((GtkWidget*) _tmp13_);
	_tmp15_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp14_, GTK_TYPE_COMBO_BOX_TEXT) ? ((GtkComboBoxText*) _tmp14_) : NULL);
	cboxt = _tmp15_;
	ns_widgets_profile_update_cboxt (self, cboxt);
	_g_object_unref0 (cboxt);
	_g_object_unref0 (button);
}


void ns_widgets_profile_delete_profile (NSWidgetsProfile* self, const gchar* profile) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	NSWidgetsProfileNames* _tmp5_;
	NSWidgetsProfileNames* profiles;
	g_return_if_fail (self != NULL);
	g_return_if_fail (profile != NULL);
	ns_file_cd (MAIN_PROFILE_PATH, TRUE);
	_tmp0_ = profile;
	_tmp1_ = g_strconcat ("profile_", _tmp0_, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat (_tmp2_, ".json", NULL);
	_tmp4_ = _tmp3_;
	g_remove (_tmp4_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	_tmp5_ = ns_widgets_profile_names_new ();
	profiles = _tmp5_;
	_g_object_unref0 (profiles);
}


void on_btn_delete_profile_clicked (GtkButton* sender, GtkEntry* entry, NSWidgetsProfile* self) {
	gint auswahl;
	GtkEntry* _tmp0_;
	GtkWidget* _tmp1_ = NULL;
	GtkComboBoxText* _tmp2_;
	GtkComboBoxText* cboxt;
	GtkEntry* _tmp3_;
	const gchar* _tmp4_ = NULL;
	GtkEntry* _tmp5_;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	gchar* removed;
	GtkEntry* _tmp8_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	g_return_if_fail (entry != NULL);
	auswahl = 0;
	_tmp0_ = entry;
	_tmp1_ = gtk_widget_get_parent ((GtkWidget*) _tmp0_);
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_COMBO_BOX_TEXT) ? ((GtkComboBoxText*) _tmp1_) : NULL);
	cboxt = _tmp2_;
	_tmp3_ = entry;
	_tmp4_ = gtk_entry_get_text (_tmp3_);
	ns_widgets_profile_delete_profile (self, _tmp4_);
	ns_widgets_profile_update_cboxt (self, cboxt);
	_tmp5_ = entry;
	_tmp6_ = gtk_entry_get_text (_tmp5_);
	_tmp7_ = g_strdup (_tmp6_);
	removed = _tmp7_;
	_tmp8_ = entry;
	gtk_entry_set_text (_tmp8_, "");
	_g_free0 (removed);
	_g_object_unref0 (cboxt);
}


static Block4Data* block4_data_ref (Block4Data* _data4_) {
	g_atomic_int_inc (&_data4_->_ref_count_);
	return _data4_;
}


static void block4_data_unref (void * _userdata_) {
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
		NSWidgetsProfile * self;
		self = _data4_->self;
		_g_object_unref0 (_data4_->cboxt);
		_g_object_unref0 (self);
		g_slice_free (Block4Data, _data4_);
	}
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	gint _tmp0_;
	gint _tmp1_;
	glong string_length;
	glong _tmp2_;
	glong _tmp5_;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_;
	gboolean _tmp12_;
	gboolean _tmp13_ = FALSE;
	glong _tmp14_;
	gboolean _tmp17_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_;
		glong _tmp4_;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_;
		glong _tmp7_;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	_tmp12_ = _tmp8_;
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp14_ = end;
	if (_tmp14_ >= ((glong) 0)) {
		glong _tmp15_;
		glong _tmp16_;
		_tmp15_ = end;
		_tmp16_ = string_length;
		_tmp13_ = _tmp15_ <= _tmp16_;
	} else {
		_tmp13_ = FALSE;
	}
	_tmp17_ = _tmp13_;
	g_return_val_if_fail (_tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	g_return_val_if_fail (_tmp18_ <= _tmp19_, NULL);
	_tmp20_ = start;
	_tmp21_ = end;
	_tmp22_ = start;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) (_tmp21_ - _tmp22_));
	result = _tmp23_;
	return result;
}


static void __lambda9_ (Block4Data* _data4_, const gchar* profile) {
	NSWidgetsProfile * self;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gchar* _tmp4_ = NULL;
	gchar* clean_profilename;
	GtkComboBoxText* _tmp5_;
	self = _data4_->self;
	g_return_if_fail (profile != NULL);
	_tmp0_ = profile;
	_tmp1_ = profile;
	_tmp2_ = strlen (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = string_slice (_tmp0_, (glong) 8, (glong) (_tmp3_ - 5));
	clean_profilename = _tmp4_;
	_tmp5_ = _data4_->cboxt;
	gtk_combo_box_text_append_text (_tmp5_, clean_profilename);
	_g_free0 (clean_profilename);
}


static void ___lambda9__gfunc (gconstpointer data, gpointer self) {
	__lambda9_ (self, data);
}


void ns_widgets_profile_update_cboxt (NSWidgetsProfile* self, GtkComboBoxText* cboxt) {
	Block4Data* _data4_;
	GtkComboBoxText* _tmp0_;
	GtkComboBoxText* _tmp1_;
	NSWidgetsProfileNames* _tmp2_;
	NSWidgetsProfileNames* profilenames;
	GtkComboBoxText* _tmp3_;
	GList* _tmp4_;
	GList* _tmp5_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (cboxt != NULL);
	_data4_ = g_slice_new0 (Block4Data);
	_data4_->_ref_count_ = 1;
	_data4_->self = g_object_ref (self);
	_tmp0_ = cboxt;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (_data4_->cboxt);
	_data4_->cboxt = _tmp1_;
	_tmp2_ = ns_widgets_profile_names_new ();
	profilenames = _tmp2_;
	_tmp3_ = _data4_->cboxt;
	gtk_combo_box_text_remove_all (_tmp3_);
	_tmp4_ = ns_widgets_profile_names_get_profiles (profilenames);
	_tmp5_ = _tmp4_;
	g_list_foreach (_tmp5_, ___lambda9__gfunc, _data4_);
	_g_object_unref0 (profilenames);
	block4_data_unref (_data4_);
	_data4_ = NULL;
}


void on_infbar_profiles_show (GtkInfoBar* infbar_profiles, NSWidgetsProfile* self) {
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkComboBoxText* _tmp2_;
	GtkComboBoxText* cboxt;
	g_return_if_fail (self != NULL);
	g_return_if_fail (infbar_profiles != NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "cboxt_profile");
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_COMBO_BOX_TEXT) ? ((GtkComboBoxText*) _tmp1_) : NULL);
	cboxt = _tmp2_;
	ns_widgets_profile_update_cboxt (self, cboxt);
	_g_object_unref0 (cboxt);
}


void on_btn_new_profile_clicked (GtkButton* sender, GtkEntry* entry, NSWidgetsProfile* self) {
	GtkEntry* _tmp0_;
	GtkEntry* _tmp1_;
	GtkEntry* _tmp2_;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	gchar* profile;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	g_return_if_fail (entry != NULL);
	_tmp0_ = entry;
	gtk_entry_set_text (_tmp0_, "");
	_tmp1_ = entry;
	on_e_profile_icon_press (_tmp1_, GTK_ENTRY_ICON_PRIMARY, self);
	_tmp2_ = entry;
	_tmp3_ = gtk_entry_get_text (_tmp2_);
	_tmp4_ = g_strdup (_tmp3_);
	profile = _tmp4_;
	_g_free0 (profile);
}


void on_cboxt_profile_changed (GtkComboBox* cbox, NSWidgetsProfile* self) {
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkEntry* _tmp2_;
	GtkEntry* e;
	GtkEntry* _tmp3_;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	gchar* profile;
	GtkComboBox* _tmp6_;
	gint _tmp7_ = 0;
	gint now_active;
	gboolean _tmp8_ = FALSE;
	gint _tmp9_;
	gint _tmp10_;
	gboolean _tmp12_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (cbox != NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "e_profile");
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp1_) : NULL);
	e = _tmp2_;
	_tmp3_ = e;
	_tmp4_ = gtk_entry_get_text (_tmp3_);
	_tmp5_ = g_strdup (_tmp4_);
	profile = _tmp5_;
	_tmp6_ = cbox;
	_tmp7_ = gtk_combo_box_get_active (_tmp6_);
	now_active = _tmp7_;
	_tmp9_ = now_active;
	_tmp10_ = ns_widgets_profile_previously_active;
	if (_tmp9_ != _tmp10_) {
		gint _tmp11_;
		_tmp11_ = now_active;
		_tmp8_ = _tmp11_ != (-1);
	} else {
		_tmp8_ = FALSE;
	}
	_tmp12_ = _tmp8_;
	if (_tmp12_) {
		const gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		gchar* _tmp16_;
		gchar* _tmp17_;
		gboolean _tmp18_ = FALSE;
		gboolean _tmp19_;
		gint _tmp27_;
		_tmp13_ = profile;
		_tmp14_ = g_strconcat ("profile_", _tmp13_, NULL);
		_tmp15_ = _tmp14_;
		_tmp16_ = g_strconcat (_tmp15_, ".json", NULL);
		_tmp17_ = _tmp16_;
		_tmp18_ = g_file_test (_tmp17_, G_FILE_TEST_IS_REGULAR);
		_tmp19_ = _tmp18_ == TRUE;
		_g_free0 (_tmp17_);
		_g_free0 (_tmp15_);
		if (_tmp19_) {
			const gchar* _tmp20_;
			NSWidgetsAdjustment* _tmp21_;
			NSWidgetsAdjustment* adjust;
			NSWidgetsAdjustment* _tmp22_;
			GtkBuilder* _tmp23_;
			const gchar* _tmp24_;
			gchar* _tmp25_;
			gchar* _tmp26_;
			_tmp20_ = profile;
			_tmp21_ = ns_widgets_adjustment_new (_tmp20_, FALSE);
			adjust = _tmp21_;
			_tmp22_ = adjust;
			_tmp23_ = ((Main*) self)->builder;
			ns_widgets_adjustment_adjust_widgets (_tmp22_, _tmp23_);
			_tmp24_ = profile;
			_tmp25_ = g_strconcat ("loaded profile: ", _tmp24_, NULL);
			_tmp26_ = _tmp25_;
			ns_widgets_profile_push_statusbar_message (self, _tmp26_);
			_g_free0 (_tmp26_);
			_g_object_unref0 (adjust);
		}
		_tmp27_ = now_active;
		ns_widgets_profile_previously_active = _tmp27_;
	}
	_g_free0 (profile);
	_g_object_unref0 (e);
}


static void ns_widgets_profile_push_statusbar_message (NSWidgetsProfile* self, const gchar* message) {
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkStatusbar* _tmp2_;
	GtkStatusbar* sbar;
	const gchar* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (message != NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "sbar");
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_STATUSBAR) ? ((GtkStatusbar*) _tmp1_) : NULL);
	sbar = _tmp2_;
	_tmp3_ = message;
	gtk_statusbar_push (sbar, (guint) 0, _tmp3_);
	gtk_widget_set_tooltip_text ((GtkWidget*) sbar, "");
	_g_object_unref0 (sbar);
}


static void ns_widgets_profile_class_init (NSWidgetsProfileClass * klass) {
	ns_widgets_profile_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = ns_widgets_profile_finalize;
}


static void ns_widgets_profile_instance_init (NSWidgetsProfile * self) {
}


static void ns_widgets_profile_finalize (GObject* obj) {
	NSWidgetsProfile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NS_WIDGETS_TYPE_PROFILE, NSWidgetsProfile);
	G_OBJECT_CLASS (ns_widgets_profile_parent_class)->finalize (obj);
}


GType ns_widgets_profile_get_type (void) {
	static volatile gsize ns_widgets_profile_type_id__volatile = 0;
	if (g_once_init_enter (&ns_widgets_profile_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (NSWidgetsProfileClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ns_widgets_profile_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NSWidgetsProfile), 0, (GInstanceInitFunc) ns_widgets_profile_instance_init, NULL };
		GType ns_widgets_profile_type_id;
		ns_widgets_profile_type_id = g_type_register_static (TYPE_MAIN, "NSWidgetsProfile", &g_define_type_info, 0);
		g_once_init_leave (&ns_widgets_profile_type_id__volatile, ns_widgets_profile_type_id);
	}
	return ns_widgets_profile_type_id__volatile;
}



