/* widgets-query.c generated by valac 0.18.1, the Vala compiler
 * generated from widgets-query.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <stdio.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define NS_WIDGETS_TYPE_QUERY (ns_widgets_query_get_type ())
#define NS_WIDGETS_QUERY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_WIDGETS_TYPE_QUERY, NSWidgetsQuery))
#define NS_WIDGETS_QUERY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_WIDGETS_TYPE_QUERY, NSWidgetsQueryClass))
#define NS_WIDGETS_IS_QUERY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_WIDGETS_TYPE_QUERY))
#define NS_WIDGETS_IS_QUERY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_WIDGETS_TYPE_QUERY))
#define NS_WIDGETS_QUERY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_WIDGETS_TYPE_QUERY, NSWidgetsQueryClass))

typedef struct _NSWidgetsQuery NSWidgetsQuery;
typedef struct _NSWidgetsQueryClass NSWidgetsQueryClass;
typedef struct _NSWidgetsQueryPrivate NSWidgetsQueryPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_JsonObject_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonObject_free (var), NULL)))
#define _g_variant_iter_free0(var) ((var == NULL) ? NULL : (var = (g_variant_iter_free (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))

#define NS_FILE_TYPE_SAVING (ns_file_saving_get_type ())
#define NS_FILE_SAVING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_FILE_TYPE_SAVING, NSFileSaving))
#define NS_FILE_SAVING_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_FILE_TYPE_SAVING, NSFileSavingClass))
#define NS_FILE_IS_SAVING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_FILE_TYPE_SAVING))
#define NS_FILE_IS_SAVING_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_FILE_TYPE_SAVING))
#define NS_FILE_SAVING_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_FILE_TYPE_SAVING, NSFileSavingClass))

typedef struct _NSFileSaving NSFileSaving;
typedef struct _NSFileSavingClass NSFileSavingClass;

#define NS_COMMAND_TYPE_CREATION (ns_command_creation_get_type ())
#define NS_COMMAND_CREATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_COMMAND_TYPE_CREATION, NSCommandCreation))
#define NS_COMMAND_CREATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_COMMAND_TYPE_CREATION, NSCommandCreationClass))
#define NS_COMMAND_IS_CREATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_COMMAND_TYPE_CREATION))
#define NS_COMMAND_IS_CREATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_COMMAND_TYPE_CREATION))
#define NS_COMMAND_CREATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_COMMAND_TYPE_CREATION, NSCommandCreationClass))

typedef struct _NSCommandCreation NSCommandCreation;
typedef struct _NSCommandCreationClass NSCommandCreationClass;

#define NS_COMMAND_TYPE_EXECUTION (ns_command_execution_get_type ())
#define NS_COMMAND_EXECUTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_COMMAND_TYPE_EXECUTION, NSCommandExecution))
#define NS_COMMAND_EXECUTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_COMMAND_TYPE_EXECUTION, NSCommandExecutionClass))
#define NS_COMMAND_IS_EXECUTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_COMMAND_TYPE_EXECUTION))
#define NS_COMMAND_IS_EXECUTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_COMMAND_TYPE_EXECUTION))
#define NS_COMMAND_EXECUTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_COMMAND_TYPE_EXECUTION, NSCommandExecutionClass))

typedef struct _NSCommandExecution NSCommandExecution;
typedef struct _NSCommandExecutionClass NSCommandExecutionClass;
#define _g_variant_type_free0(var) ((var == NULL) ? NULL : (var = (g_variant_type_free (var), NULL)))
#define _g_variant_builder_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_builder_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _Main {
	GtkApplication parent_instance;
	MainPrivate * priv;
	GtkBuilder* builder;
	GtkLabel* advice_label;
	GtkInfoBar* infobar;
	GtkInfoBar* error_infbar;
	GtkLabel* lbl_video;
	GtkLabel* lbl_audio;
	GtkLabel* lbl_other;
};

struct _MainClass {
	GtkApplicationClass parent_class;
};

struct _NSWidgetsQuery {
	Main parent_instance;
	NSWidgetsQueryPrivate * priv;
};

struct _NSWidgetsQueryClass {
	MainClass parent_class;
};


static gpointer ns_widgets_query_parent_class = NULL;
static JsonGenerator* ns_widgets_query__generator;
static JsonGenerator* ns_widgets_query__generator = NULL;

GType main_get_type (void) G_GNUC_CONST;
GType ns_widgets_query_get_type (void) G_GNUC_CONST;
enum  {
	NS_WIDGETS_QUERY_DUMMY_PROPERTY
};
NSWidgetsQuery* ns_widgets_query_new (void);
NSWidgetsQuery* ns_widgets_query_construct (GType object_type);
Main* main_new (void);
Main* main_construct (GType object_type);
static void update_rootobject (guint8 mode, NSWidgetsQuery* self);
GVariant* ns_widgets_query_widgets_to_check (guint8 mode);
JsonObject* ns_widgets_query_query_category (NSWidgetsQuery* self, const gchar* category, GVariant* widgettypes);
static void _vala_JsonObject_free (JsonObject* self);
static JsonObject* _vala_JsonObject_copy (JsonObject* self);
static void _vala_JsonNode_free (JsonNode* self);
void main_on_destroy (GtkWidget* window, NSWidgetsQuery* self);
#define MAIN_PROFILE_MODE1 "config_last"
NSFileSaving* ns_file_saving_new (const gchar* filename);
NSFileSaving* ns_file_saving_construct (GType object_type, const gchar* filename);
GType ns_file_saving_get_type (void) G_GNUC_CONST;
void on_btn_conversion_clicked (GtkButton* sender, NSWidgetsQuery* self);
void main_built_infbar_layout (Main* self, GtkMessageType type, const gchar* message, const gchar* button);
gint ns_file_cd (const gchar* new_path, gboolean relative_to_home);
#define MAIN_PROFILE_PATH "/.local/share/theodora-transcode/"
#define MAIN_LAST_PROFILE "most recent"
NSCommandCreation* ns_command_creation_new (void);
NSCommandCreation* ns_command_creation_construct (GType object_type);
GType ns_command_creation_get_type (void) G_GNUC_CONST;
const gchar* ns_command_creation_get_conversion_command (NSCommandCreation* self);
NSCommandExecution* ns_command_execution_new (void);
NSCommandExecution* ns_command_execution_construct (GType object_type);
GType ns_command_execution_get_type (void) G_GNUC_CONST;
gboolean ns_command_execution_async_command (NSCommandExecution* self, const gchar* command);
void on_btn_conversion_clicked_update_timelabel (GtkButton* sender, GtkGrid* grid, NSWidgetsQuery* self);
void on_btn_save_profile_clicked (GtkButton* sender, NSWidgetsQuery* self);
static GVariant* _variant_new1 (const gchar* value);
static GVariant* _variant_new2 (const gchar* value);
static GVariant* _variant_new3 (const gchar* value);
static GVariant* _variant_new4 (const gchar* value);
static GVariant* _variant_new5 (const gchar* value);
static GVariant* _variant_new6 (const gchar* value);
static GVariant* _variant_new7 (const gchar* value);
static GVariant* _variant_new8 (const gchar* value);
static GVariant* _variant_new9 (const gchar* value);
static GVariant* _variant_new10 (const gchar* value);
static GVariant* _variant_new11 (const gchar* value);
static GVariant* _variant_new12 (const gchar* value);
GVariantIter* ns_widgets_query_get_description (const gchar* category, const gchar* type, guint8 number);
void on_btn_preview_clicked (GtkButton* sender, NSWidgetsQuery* self);
gboolean ns_command_execution_sync_command (NSCommandExecution* self, const gchar* command);
JsonGenerator* ns_widgets_query_get_generator (void);
static void ns_widgets_query_finalize (GObject* obj);
static void _vala_ns_widgets_query_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


NSWidgetsQuery* ns_widgets_query_construct (GType object_type) {
	NSWidgetsQuery * self = NULL;
	self = (NSWidgetsQuery*) main_construct (object_type);
	return self;
}


NSWidgetsQuery* ns_widgets_query_new (void) {
	return ns_widgets_query_construct (NS_WIDGETS_TYPE_QUERY);
}


static void _vala_JsonObject_free (JsonObject* self) {
	g_boxed_free (json_object_get_type (), self);
}


static JsonObject* _vala_JsonObject_copy (JsonObject* self) {
	return g_boxed_copy (json_object_get_type (), self);
}


static gpointer __vala_JsonObject_copy0 (gpointer self) {
	return self ? _vala_JsonObject_copy (self) : NULL;
}


static void _vala_JsonNode_free (JsonNode* self) {
	g_boxed_free (json_node_get_type (), self);
}


static void update_rootobject (guint8 mode, NSWidgetsQuery* self) {
	guint8 _tmp0_;
	GVariant* _tmp1_ = NULL;
	GVariant* dictionary;
	GVariant* val;
	gchar* key;
	JsonNode* _tmp2_;
	JsonNode* root;
	JsonObject* _tmp3_;
	JsonObject* robject;
	JsonObject* _tmp4_;
	JsonObject* object;
	JsonGenerator* _tmp5_;
	JsonGenerator* _tmp6_;
	JsonNode* _tmp7_;
	JsonObject* _tmp8_;
	JsonGenerator* _tmp9_;
	JsonNode* _tmp10_;
	GVariant* _tmp11_;
	GVariantIter* _tmp12_ = NULL;
	GVariantIter* iter;
	g_return_if_fail (self != NULL);
	_tmp0_ = mode;
	_tmp1_ = ns_widgets_query_widgets_to_check (_tmp0_);
	dictionary = _tmp1_;
	val = NULL;
	key = NULL;
	_tmp2_ = json_node_new (JSON_NODE_OBJECT);
	root = _tmp2_;
	_tmp3_ = json_object_new ();
	robject = _tmp3_;
	_tmp4_ = json_object_new ();
	object = _tmp4_;
	_tmp5_ = json_generator_new ();
	_g_object_unref0 (ns_widgets_query__generator);
	ns_widgets_query__generator = _tmp5_;
	_tmp6_ = ns_widgets_query__generator;
	json_generator_set_pretty (_tmp6_, TRUE);
	_tmp7_ = root;
	_tmp8_ = robject;
	json_node_set_object (_tmp7_, _tmp8_);
	_tmp9_ = ns_widgets_query__generator;
	_tmp10_ = root;
	json_generator_set_root (_tmp9_, _tmp10_);
	_tmp11_ = dictionary;
	_tmp12_ = g_variant_iter_new (_tmp11_);
	iter = _tmp12_;
	while (TRUE) {
		GVariantIter* _tmp13_;
		gboolean _tmp14_ = FALSE;
		const gchar* _tmp15_;
		GVariant* _tmp16_;
		JsonObject* _tmp17_ = NULL;
		JsonObject* _tmp18_;
		const gchar* _tmp19_;
		JsonObject* _tmp20_;
		JsonObject* _tmp21_;
		_tmp13_ = iter;
		_tmp14_ = g_variant_iter_next (_tmp13_, "{sv}", &key, &val, NULL);
		if (!_tmp14_) {
			break;
		}
		_tmp15_ = key;
		_tmp16_ = val;
		_tmp17_ = ns_widgets_query_query_category (self, _tmp15_, _tmp16_);
		__vala_JsonObject_free0 (object);
		object = _tmp17_;
		_tmp18_ = robject;
		_tmp19_ = key;
		_tmp20_ = object;
		_tmp21_ = __vala_JsonObject_copy0 (_tmp20_);
		json_object_set_object_member (_tmp18_, _tmp19_, _tmp21_);
	}
	_g_variant_iter_free0 (iter);
	__vala_JsonObject_free0 (object);
	__vala_JsonObject_free0 (robject);
	__vala_JsonNode_free0 (root);
	_g_free0 (key);
	_g_variant_unref0 (val);
	_g_variant_unref0 (dictionary);
}


void main_on_destroy (GtkWidget* window, NSWidgetsQuery* self) {
	NSFileSaving* _tmp0_;
	NSFileSaving* save_file;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	update_rootobject ((guint8) 1, self);
	_tmp0_ = ns_file_saving_new (MAIN_PROFILE_MODE1 ".json");
	save_file = _tmp0_;
	gtk_main_quit ();
	_g_object_unref0 (save_file);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void on_btn_conversion_clicked (GtkButton* sender, NSWidgetsQuery* self) {
	GtkInfoBar* _tmp0_;
	GtkBuilder* _tmp2_;
	GObject* _tmp3_ = NULL;
	GtkFileChooser* _tmp4_;
	GtkFileChooser* source_fbtn;
	GtkFileChooser* _tmp5_;
	gchar* _tmp6_ = NULL;
	gchar* input;
	GtkBuilder* _tmp7_;
	GObject* _tmp8_ = NULL;
	GtkEntry* _tmp9_;
	GtkEntry* target_e;
	GtkEntry* _tmp10_;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_;
	gchar* target;
	gboolean _tmp13_ = FALSE;
	const gchar* _tmp14_;
	gboolean _tmp16_;
	NSFileSaving* _tmp17_;
	NSFileSaving* save_file;
	NSCommandCreation* _tmp18_;
	NSCommandCreation* command;
	NSCommandCreation* _tmp19_;
	const gchar* _tmp20_;
	const gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* c;
	GtkBuilder* _tmp23_;
	GObject* _tmp24_ = NULL;
	GtkToggleButton* _tmp25_;
	GtkToggleButton* subtitle_file_rbtn;
	GtkToggleButton* _tmp26_;
	gboolean _tmp27_ = FALSE;
	GtkBuilder* _tmp38_;
	GObject* _tmp39_ = NULL;
	GtkEntry* _tmp40_;
	GtkEntry* terminal_e;
	GtkEntry* _tmp41_;
	const gchar* _tmp42_ = NULL;
	gchar* _tmp43_;
	gchar* terminal;
	const gchar* _tmp44_;
	const gchar* _tmp45_;
	gchar* _tmp46_;
	gchar* _tmp47_;
	const gchar* _tmp48_;
	gchar* _tmp49_;
	const gchar* _tmp50_;
	gchar* _tmp51_;
	gchar* _tmp52_;
	const gchar* _tmp53_;
	gchar* _tmp54_;
	gchar* _tmp55_;
	gchar* _tmp56_;
	gchar* _tmp57_;
	const gchar* _tmp58_;
	gchar* _tmp59_;
	gchar* _tmp60_;
	gchar* _tmp61_;
	GtkBuilder* _tmp62_;
	GObject* _tmp63_ = NULL;
	GtkStatusbar* _tmp64_;
	GtkStatusbar* sbar;
	GtkStatusbar* _tmp65_;
	const gchar* _tmp66_;
	gchar* _tmp67_;
	gchar* _tmp68_;
	GtkStatusbar* _tmp69_;
	const gchar* _tmp70_;
	const gchar* _tmp71_ = NULL;
	gchar* _tmp72_;
	gchar* home;
	const gchar* _tmp73_;
	NSCommandExecution* _tmp74_;
	NSCommandExecution* process;
	NSCommandExecution* _tmp75_;
	const gchar* _tmp76_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	_tmp0_ = ((Main*) self)->error_infbar;
	if (_tmp0_ != NULL) {
		GtkInfoBar* _tmp1_;
		_tmp1_ = ((Main*) self)->error_infbar;
		gtk_widget_destroy ((GtkWidget*) _tmp1_);
	}
	_tmp2_ = ((Main*) self)->builder;
	_tmp3_ = gtk_builder_get_object (_tmp2_, "fbtn_basics0");
	_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, GTK_TYPE_FILE_CHOOSER) ? ((GtkFileChooser*) _tmp3_) : NULL);
	source_fbtn = _tmp4_;
	_tmp5_ = source_fbtn;
	_tmp6_ = gtk_file_chooser_get_filename (_tmp5_);
	input = _tmp6_;
	_tmp7_ = ((Main*) self)->builder;
	_tmp8_ = gtk_builder_get_object (_tmp7_, "e_basics0");
	_tmp9_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp8_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp8_) : NULL);
	target_e = _tmp9_;
	_tmp10_ = target_e;
	_tmp11_ = gtk_entry_get_text (_tmp10_);
	_tmp12_ = g_strdup (_tmp11_);
	target = _tmp12_;
	_tmp14_ = input;
	if (g_strcmp0 (_tmp14_, "") == 0) {
		_tmp13_ = TRUE;
	} else {
		const gchar* _tmp15_;
		_tmp15_ = target;
		_tmp13_ = g_strcmp0 (_tmp15_, "") == 0;
	}
	_tmp16_ = _tmp13_;
	if (_tmp16_) {
		main_built_infbar_layout ((Main*) self, GTK_MESSAGE_WARNING, "Not started yet! " "Please specify the input and output file first!", "");
		_g_free0 (target);
		_g_object_unref0 (target_e);
		_g_free0 (input);
		_g_object_unref0 (source_fbtn);
		return;
	}
	update_rootobject ((guint8) 0, self);
	ns_file_cd (MAIN_PROFILE_PATH, TRUE);
	_tmp17_ = ns_file_saving_new ("last_" MAIN_LAST_PROFILE ".json");
	save_file = _tmp17_;
	_tmp18_ = ns_command_creation_new ();
	command = _tmp18_;
	_tmp19_ = command;
	_tmp20_ = ns_command_creation_get_conversion_command (_tmp19_);
	_tmp21_ = _tmp20_;
	_tmp22_ = g_strdup (_tmp21_);
	c = _tmp22_;
	_tmp23_ = ((Main*) self)->builder;
	_tmp24_ = gtk_builder_get_object (_tmp23_, "rbtn_basics1");
	_tmp25_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp24_, GTK_TYPE_TOGGLE_BUTTON) ? ((GtkToggleButton*) _tmp24_) : NULL);
	subtitle_file_rbtn = _tmp25_;
	_tmp26_ = subtitle_file_rbtn;
	_tmp27_ = gtk_toggle_button_get_active (_tmp26_);
	if (_tmp27_ == TRUE) {
		GtkBuilder* _tmp28_;
		GObject* _tmp29_ = NULL;
		GtkFileChooser* _tmp30_;
		GtkFileChooser* subtitle_fbtn;
		const gchar* _tmp31_;
		gchar* _tmp32_;
		gchar* _tmp33_;
		GtkFileChooser* _tmp34_;
		gchar* _tmp35_ = NULL;
		gchar* _tmp36_;
		gchar* _tmp37_;
		_tmp28_ = ((Main*) self)->builder;
		_tmp29_ = gtk_builder_get_object (_tmp28_, "fbtn_basics1");
		_tmp30_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp29_, GTK_TYPE_FILE_CHOOSER) ? ((GtkFileChooser*) _tmp29_) : NULL);
		subtitle_fbtn = _tmp30_;
		_tmp31_ = c;
		_tmp32_ = g_strconcat (_tmp31_, " --subtitles ", NULL);
		_tmp33_ = _tmp32_;
		_tmp34_ = subtitle_fbtn;
		_tmp35_ = gtk_file_chooser_get_filename (_tmp34_);
		_tmp36_ = _tmp35_;
		_tmp37_ = g_strconcat (_tmp33_, _tmp36_, NULL);
		_g_free0 (c);
		c = _tmp37_;
		_g_free0 (_tmp36_);
		_g_free0 (_tmp33_);
		_g_object_unref0 (subtitle_fbtn);
	}
	_tmp38_ = ((Main*) self)->builder;
	_tmp39_ = gtk_builder_get_object (_tmp38_, "ce_terminal0");
	_tmp40_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp39_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp39_) : NULL);
	terminal_e = _tmp40_;
	_tmp41_ = terminal_e;
	_tmp42_ = gtk_entry_get_text (_tmp41_);
	_tmp43_ = g_strdup (_tmp42_);
	terminal = _tmp43_;
	_tmp44_ = terminal;
	if (g_strcmp0 (_tmp44_, "") == 0) {
		main_built_infbar_layout ((Main*) self, GTK_MESSAGE_WARNING, "Specify a terminal first, please!", "");
		_g_free0 (terminal);
		_g_object_unref0 (terminal_e);
		_g_object_unref0 (subtitle_file_rbtn);
		_g_free0 (c);
		_g_object_unref0 (command);
		_g_object_unref0 (save_file);
		_g_free0 (target);
		_g_object_unref0 (target_e);
		_g_free0 (input);
		_g_object_unref0 (source_fbtn);
		return;
	}
	_tmp45_ = terminal;
	_tmp46_ = g_strconcat (_tmp45_, " -e \"", NULL);
	_tmp47_ = _tmp46_;
	_tmp48_ = c;
	_tmp49_ = g_strconcat (_tmp47_, _tmp48_, NULL);
	_g_free0 (c);
	c = _tmp49_;
	_g_free0 (_tmp47_);
	_tmp50_ = c;
	_tmp51_ = g_strconcat (_tmp50_, " '", NULL);
	_tmp52_ = _tmp51_;
	_tmp53_ = input;
	_tmp54_ = g_strconcat (_tmp52_, _tmp53_, NULL);
	_tmp55_ = _tmp54_;
	_tmp56_ = g_strconcat (_tmp55_, "' -o '", NULL);
	_tmp57_ = _tmp56_;
	_tmp58_ = target;
	_tmp59_ = g_strconcat (_tmp57_, _tmp58_, NULL);
	_tmp60_ = _tmp59_;
	_tmp61_ = g_strconcat (_tmp60_, "'\"", NULL);
	_g_free0 (c);
	c = _tmp61_;
	_g_free0 (_tmp60_);
	_g_free0 (_tmp57_);
	_g_free0 (_tmp55_);
	_g_free0 (_tmp52_);
	_tmp62_ = ((Main*) self)->builder;
	_tmp63_ = gtk_builder_get_object (_tmp62_, "sbar");
	_tmp64_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp63_, GTK_TYPE_STATUSBAR) ? ((GtkStatusbar*) _tmp63_) : NULL);
	sbar = _tmp64_;
	_tmp65_ = sbar;
	_tmp66_ = c;
	_tmp67_ = g_strconcat ("executed: ", _tmp66_, NULL);
	_tmp68_ = _tmp67_;
	gtk_statusbar_push (_tmp65_, (guint) 0, _tmp68_);
	_g_free0 (_tmp68_);
	_tmp69_ = sbar;
	_tmp70_ = c;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp69_, _tmp70_);
	_tmp71_ = g_get_home_dir ();
	_tmp72_ = g_strdup (_tmp71_);
	home = _tmp72_;
	_tmp73_ = home;
	g_chdir (_tmp73_);
	_tmp74_ = ns_command_execution_new ();
	process = _tmp74_;
	_tmp75_ = process;
	_tmp76_ = c;
	ns_command_execution_async_command (_tmp75_, _tmp76_);
	ns_file_cd (MAIN_PROFILE_PATH, TRUE);
	main_built_infbar_layout ((Main*) self, GTK_MESSAGE_INFO, "During conversion, " "better not close this GUI and neither the terminal! " "\nOtherwise the conversion will be stopped!", "Hide");
	_g_object_unref0 (process);
	_g_free0 (home);
	_g_object_unref0 (sbar);
	_g_free0 (terminal);
	_g_object_unref0 (terminal_e);
	_g_object_unref0 (subtitle_file_rbtn);
	_g_free0 (c);
	_g_object_unref0 (command);
	_g_object_unref0 (save_file);
	_g_free0 (target);
	_g_object_unref0 (target_e);
	_g_free0 (input);
	_g_object_unref0 (source_fbtn);
}


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	gchar* _tmp4_;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


void on_btn_conversion_clicked_update_timelabel (GtkButton* sender, GtkGrid* grid, NSWidgetsQuery* self) {
	GtkGrid* _tmp0_;
	GtkWidget* _tmp1_ = NULL;
	GtkGrid* _tmp2_;
	GtkGrid* start_grid;
	GtkWidget* _tmp3_ = NULL;
	GtkEntry* _tmp4_;
	GtkEntry* minutes_widget;
	GtkWidget* _tmp5_ = NULL;
	GtkSpinButton* _tmp6_;
	GtkSpinButton* seconds_widget;
	GtkWidget* _tmp7_ = NULL;
	GtkLabel* _tmp8_;
	GtkLabel* lbl;
	GtkEntry* _tmp9_;
	const gchar* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	GtkSpinButton* _tmp12_;
	const gchar* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gdouble seconds;
	GtkLabel* _tmp15_;
	gdouble _tmp16_;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_;
	GtkGrid* _tmp19_;
	GtkWidget* _tmp20_ = NULL;
	GtkGrid* _tmp21_;
	GtkGrid* end_grid;
	GtkWidget* _tmp22_ = NULL;
	GtkLabel* _tmp23_;
	GtkWidget* _tmp24_ = NULL;
	GtkEntry* _tmp25_;
	GtkWidget* _tmp26_ = NULL;
	GtkSpinButton* _tmp27_;
	GtkEntry* _tmp28_;
	const gchar* _tmp29_ = NULL;
	gint _tmp30_ = 0;
	GtkSpinButton* _tmp31_;
	const gchar* _tmp32_ = NULL;
	gint _tmp33_ = 0;
	GtkLabel* _tmp34_;
	gdouble _tmp35_;
	gchar* _tmp36_ = NULL;
	gchar* _tmp37_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	g_return_if_fail (grid != NULL);
	_tmp0_ = grid;
	_tmp1_ = gtk_grid_get_child_at (_tmp0_, 0, 1);
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_GRID) ? ((GtkGrid*) _tmp1_) : NULL);
	start_grid = _tmp2_;
	_tmp3_ = gtk_grid_get_child_at (start_grid, 0, 0);
	_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp3_) : NULL);
	minutes_widget = _tmp4_;
	_tmp5_ = gtk_grid_get_child_at (start_grid, 1, 0);
	_tmp6_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, GTK_TYPE_SPIN_BUTTON) ? ((GtkSpinButton*) _tmp5_) : NULL);
	seconds_widget = _tmp6_;
	_tmp7_ = gtk_grid_get_child_at (start_grid, 2, 1);
	_tmp8_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, GTK_TYPE_LABEL) ? ((GtkLabel*) _tmp7_) : NULL);
	lbl = _tmp8_;
	_tmp9_ = minutes_widget;
	_tmp10_ = gtk_entry_get_text (_tmp9_);
	_tmp11_ = atoi (_tmp10_);
	_tmp12_ = seconds_widget;
	_tmp13_ = gtk_entry_get_text ((GtkEntry*) _tmp12_);
	_tmp14_ = atoi (_tmp13_);
	seconds = (gdouble) ((_tmp11_ * 60) + _tmp14_);
	_tmp15_ = lbl;
	_tmp16_ = seconds;
	_tmp17_ = double_to_string (_tmp16_);
	_tmp18_ = _tmp17_;
	gtk_label_set_text (_tmp15_, _tmp18_);
	_g_free0 (_tmp18_);
	_tmp19_ = grid;
	_tmp20_ = gtk_grid_get_child_at (_tmp19_, 1, 1);
	_tmp21_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp20_, GTK_TYPE_GRID) ? ((GtkGrid*) _tmp20_) : NULL);
	end_grid = _tmp21_;
	_tmp22_ = gtk_grid_get_child_at (end_grid, 2, 1);
	_tmp23_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp22_, GTK_TYPE_LABEL) ? ((GtkLabel*) _tmp22_) : NULL);
	_g_object_unref0 (lbl);
	lbl = _tmp23_;
	_tmp24_ = gtk_grid_get_child_at (end_grid, 0, 0);
	_tmp25_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp24_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp24_) : NULL);
	_g_object_unref0 (minutes_widget);
	minutes_widget = _tmp25_;
	_tmp26_ = gtk_grid_get_child_at (end_grid, 1, 0);
	_tmp27_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp26_, GTK_TYPE_SPIN_BUTTON) ? ((GtkSpinButton*) _tmp26_) : NULL);
	_g_object_unref0 (seconds_widget);
	seconds_widget = _tmp27_;
	_tmp28_ = minutes_widget;
	_tmp29_ = gtk_entry_get_text (_tmp28_);
	_tmp30_ = atoi (_tmp29_);
	_tmp31_ = seconds_widget;
	_tmp32_ = gtk_entry_get_text ((GtkEntry*) _tmp31_);
	_tmp33_ = atoi (_tmp32_);
	seconds = (gdouble) ((_tmp30_ * 60) + _tmp33_);
	_tmp34_ = lbl;
	_tmp35_ = seconds;
	_tmp36_ = double_to_string (_tmp35_);
	_tmp37_ = _tmp36_;
	gtk_label_set_text (_tmp34_, _tmp37_);
	_g_free0 (_tmp37_);
	_g_object_unref0 (end_grid);
	_g_object_unref0 (lbl);
	_g_object_unref0 (seconds_widget);
	_g_object_unref0 (minutes_widget);
	_g_object_unref0 (start_grid);
}


void on_btn_save_profile_clicked (GtkButton* sender, NSWidgetsQuery* self) {
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkEntry* _tmp2_;
	GtkEntry* profile_e;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	gchar* profilename;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	NSFileSaving* _tmp9_;
	NSFileSaving* _tmp10_;
	NSFileSaving* save;
	GtkBuilder* _tmp11_;
	GObject* _tmp12_ = NULL;
	GtkStatusbar* _tmp13_;
	GtkStatusbar* sbar;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "e_profile");
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp1_) : NULL);
	profile_e = _tmp2_;
	update_rootobject ((guint8) 2, self);
	_tmp3_ = gtk_entry_get_text (profile_e);
	_tmp4_ = g_strdup (_tmp3_);
	profilename = _tmp4_;
	_tmp5_ = g_strconcat ("profile_", profilename, NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strconcat (_tmp6_, ".json", NULL);
	_tmp8_ = _tmp7_;
	_tmp9_ = ns_file_saving_new (_tmp8_);
	_tmp10_ = _tmp9_;
	_g_free0 (_tmp8_);
	_g_free0 (_tmp6_);
	save = _tmp10_;
	_tmp11_ = ((Main*) self)->builder;
	_tmp12_ = gtk_builder_get_object (_tmp11_, "sbar");
	_tmp13_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp12_, GTK_TYPE_STATUSBAR) ? ((GtkStatusbar*) _tmp12_) : NULL);
	sbar = _tmp13_;
	_tmp14_ = g_strconcat ("saved in profile '", profilename, NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_strconcat (_tmp15_, "': color-, quality-", NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_strconcat (_tmp17_, " and additional parameter settings", NULL);
	_tmp19_ = _tmp18_;
	gtk_statusbar_push (sbar, (guint) 0, _tmp19_);
	_g_free0 (_tmp19_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp15_);
	gtk_widget_set_tooltip_text ((GtkWidget*) sbar, "");
	_g_object_unref0 (sbar);
	_g_object_unref0 (save);
	_g_free0 (profilename);
	_g_object_unref0 (profile_e);
}


static GVariant* _variant_new1 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new2 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new3 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new4 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new5 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new6 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new7 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new8 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new9 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new10 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new11 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


static GVariant* _variant_new12 (const gchar* value) {
	return g_variant_ref_sink (g_variant_new_string (value));
}


GVariant* ns_widgets_query_widgets_to_check (guint8 mode) {
	GVariant* result = NULL;
	GVariantType* _tmp0_;
	GVariantType* _tmp1_;
	GVariantBuilder* _tmp2_;
	GVariantBuilder* _tmp3_;
	GVariantBuilder* vbuilder;
	GVariantBuilder* _tmp4_;
	GVariant* _tmp5_;
	GVariant** _tmp6_ = NULL;
	GVariant** _tmp7_;
	gint _tmp7__length1;
	GVariant* _tmp8_;
	GVariant* _tmp9_;
	GVariantBuilder* _tmp10_;
	GVariant* _tmp11_;
	GVariant* _tmp12_;
	GVariant* _tmp13_;
	GVariant** _tmp14_ = NULL;
	GVariant** _tmp15_;
	gint _tmp15__length1;
	GVariant* _tmp16_;
	GVariant* _tmp17_;
	guint8 _tmp18_;
	guint8 _tmp27_;
	guint8 _tmp34_;
	guint8 _tmp42_;
	guint8 _tmp49_;
	GVariantBuilder* _tmp56_;
	GVariant* _tmp57_ = NULL;
	GVariant* dictionary;
	_tmp0_ = g_variant_type_new ("a{sv}");
	_tmp1_ = _tmp0_;
	_tmp2_ = g_variant_builder_new (_tmp1_);
	_tmp3_ = _tmp2_;
	_g_variant_type_free0 (_tmp1_);
	vbuilder = _tmp3_;
	_tmp4_ = vbuilder;
	_tmp5_ = _variant_new1 ("scale");
	_tmp6_ = g_new0 (GVariant*, 1 + 1);
	_tmp6_[0] = _tmp5_;
	_tmp7_ = _tmp6_;
	_tmp7__length1 = 1;
	_tmp8_ = g_variant_new_tuple (_tmp7_, 1);
	g_variant_ref_sink (_tmp8_);
	_tmp9_ = _tmp8_;
	g_variant_builder_add (_tmp4_, "{sv}", "color", _tmp9_, NULL);
	_g_variant_unref0 (_tmp9_);
	_tmp7_ = (_vala_array_free (_tmp7_, _tmp7__length1, (GDestroyNotify) g_variant_unref), NULL);
	_tmp10_ = vbuilder;
	_tmp11_ = _variant_new2 ("scale");
	_tmp12_ = _variant_new3 ("e");
	_tmp13_ = _variant_new4 ("cbtn");
	_tmp14_ = g_new0 (GVariant*, 3 + 1);
	_tmp14_[0] = _tmp11_;
	_tmp14_[1] = _tmp12_;
	_tmp14_[2] = _tmp13_;
	_tmp15_ = _tmp14_;
	_tmp15__length1 = 3;
	_tmp16_ = g_variant_new_tuple (_tmp15_, 3);
	g_variant_ref_sink (_tmp16_);
	_tmp17_ = _tmp16_;
	g_variant_builder_add (_tmp10_, "{sv}", "quality", _tmp17_, NULL);
	_g_variant_unref0 (_tmp17_);
	_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_variant_unref), NULL);
	_tmp18_ = mode;
	if (((gint) _tmp18_) == 0) {
		GVariantBuilder* _tmp19_;
		GVariant* _tmp20_;
		GVariant* _tmp21_;
		GVariant* _tmp22_;
		GVariant** _tmp23_ = NULL;
		GVariant** _tmp24_;
		gint _tmp24__length1;
		GVariant* _tmp25_;
		GVariant* _tmp26_;
		_tmp19_ = vbuilder;
		_tmp20_ = _variant_new5 ("e");
		_tmp21_ = _variant_new6 ("rbtn");
		_tmp22_ = _variant_new7 ("lbl");
		_tmp23_ = g_new0 (GVariant*, 3 + 1);
		_tmp23_[0] = _tmp20_;
		_tmp23_[1] = _tmp21_;
		_tmp23_[2] = _tmp22_;
		_tmp24_ = _tmp23_;
		_tmp24__length1 = 3;
		_tmp25_ = g_variant_new_tuple (_tmp24_, 3);
		g_variant_ref_sink (_tmp25_);
		_tmp26_ = _tmp25_;
		g_variant_builder_add (_tmp19_, "{sv}", "basics", _tmp26_, NULL);
		_g_variant_unref0 (_tmp26_);
		_tmp24_ = (_vala_array_free (_tmp24_, _tmp24__length1, (GDestroyNotify) g_variant_unref), NULL);
	}
	_tmp27_ = mode;
	if (((gint) _tmp27_) == 0) {
		GVariantBuilder* _tmp28_;
		GVariant* _tmp29_;
		GVariant** _tmp30_ = NULL;
		GVariant** _tmp31_;
		gint _tmp31__length1;
		GVariant* _tmp32_;
		GVariant* _tmp33_;
		_tmp28_ = vbuilder;
		_tmp29_ = _variant_new8 ("sbtn");
		_tmp30_ = g_new0 (GVariant*, 1 + 1);
		_tmp30_[0] = _tmp29_;
		_tmp31_ = _tmp30_;
		_tmp31__length1 = 1;
		_tmp32_ = g_variant_new_tuple (_tmp31_, 1);
		g_variant_ref_sink (_tmp32_);
		_tmp33_ = _tmp32_;
		g_variant_builder_add (_tmp28_, "{sv}", "crop", _tmp33_, NULL);
		_g_variant_unref0 (_tmp33_);
		_tmp31_ = (_vala_array_free (_tmp31_, _tmp31__length1, (GDestroyNotify) g_variant_unref), NULL);
	}
	_tmp34_ = mode;
	if (((gint) _tmp34_) != 2) {
		GVariantBuilder* _tmp35_;
		GVariant* _tmp36_;
		GVariant* _tmp37_;
		GVariant** _tmp38_ = NULL;
		GVariant** _tmp39_;
		gint _tmp39__length1;
		GVariant* _tmp40_;
		GVariant* _tmp41_;
		_tmp35_ = vbuilder;
		_tmp36_ = _variant_new9 ("e");
		_tmp37_ = _variant_new10 ("ce");
		_tmp38_ = g_new0 (GVariant*, 2 + 1);
		_tmp38_[0] = _tmp36_;
		_tmp38_[1] = _tmp37_;
		_tmp39_ = _tmp38_;
		_tmp39__length1 = 2;
		_tmp40_ = g_variant_new_tuple (_tmp39_, 2);
		g_variant_ref_sink (_tmp40_);
		_tmp41_ = _tmp40_;
		g_variant_builder_add (_tmp35_, "{sv}", "terminal", _tmp41_, NULL);
		_g_variant_unref0 (_tmp41_);
		_tmp39_ = (_vala_array_free (_tmp39_, _tmp39__length1, (GDestroyNotify) g_variant_unref), NULL);
	}
	_tmp42_ = mode;
	if (((gint) _tmp42_) == 2) {
		GVariantBuilder* _tmp43_;
		GVariant* _tmp44_;
		GVariant** _tmp45_ = NULL;
		GVariant** _tmp46_;
		gint _tmp46__length1;
		GVariant* _tmp47_;
		GVariant* _tmp48_;
		_tmp43_ = vbuilder;
		_tmp44_ = _variant_new11 ("e");
		_tmp45_ = g_new0 (GVariant*, 1 + 1);
		_tmp45_[0] = _tmp44_;
		_tmp46_ = _tmp45_;
		_tmp46__length1 = 1;
		_tmp47_ = g_variant_new_tuple (_tmp46_, 1);
		g_variant_ref_sink (_tmp47_);
		_tmp48_ = _tmp47_;
		g_variant_builder_add (_tmp43_, "{sv}", "terminal", _tmp48_, NULL);
		_g_variant_unref0 (_tmp48_);
		_tmp46_ = (_vala_array_free (_tmp46_, _tmp46__length1, (GDestroyNotify) g_variant_unref), NULL);
	}
	_tmp49_ = mode;
	if (((gint) _tmp49_) == 1) {
		GVariantBuilder* _tmp50_;
		GVariant* _tmp51_;
		GVariant** _tmp52_ = NULL;
		GVariant** _tmp53_;
		gint _tmp53__length1;
		GVariant* _tmp54_;
		GVariant* _tmp55_;
		_tmp50_ = vbuilder;
		_tmp51_ = _variant_new12 ("e");
		_tmp52_ = g_new0 (GVariant*, 1 + 1);
		_tmp52_[0] = _tmp51_;
		_tmp53_ = _tmp52_;
		_tmp53__length1 = 1;
		_tmp54_ = g_variant_new_tuple (_tmp53_, 1);
		g_variant_ref_sink (_tmp54_);
		_tmp55_ = _tmp54_;
		g_variant_builder_add (_tmp50_, "{sv}", "crop", _tmp55_, NULL);
		_g_variant_unref0 (_tmp55_);
		_tmp53_ = (_vala_array_free (_tmp53_, _tmp53__length1, (GDestroyNotify) g_variant_unref), NULL);
	}
	_tmp56_ = vbuilder;
	_tmp57_ = g_variant_builder_end (_tmp56_);
	g_variant_ref_sink (_tmp57_);
	dictionary = _tmp57_;
	result = dictionary;
	_g_variant_builder_unref0 (vbuilder);
	return result;
}


JsonObject* ns_widgets_query_query_category (NSWidgetsQuery* self, const gchar* category, GVariant* widgettypes) {
	JsonObject* result = NULL;
	guint8 i;
	JsonObject* _tmp0_;
	JsonObject* object;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (category != NULL, NULL);
	g_return_val_if_fail (widgettypes != NULL, NULL);
	i = (guint8) 0;
	_tmp0_ = json_object_new ();
	object = _tmp0_;
	while (TRUE) {
		guint8 _tmp1_;
		GVariant* _tmp2_;
		gsize _tmp3_ = 0UL;
		GVariant* _tmp4_;
		guint8 _tmp5_;
		GVariant* _tmp6_ = NULL;
		GVariant* _tmp7_;
		const gchar* _tmp8_ = NULL;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* type;
		const gchar* _tmp11_;
		const gchar* _tmp12_;
		GQuark _tmp14_ = 0U;
		static GQuark _tmp13_label0 = 0;
		static GQuark _tmp13_label1 = 0;
		static GQuark _tmp13_label2 = 0;
		static GQuark _tmp13_label3 = 0;
		static GQuark _tmp13_label4 = 0;
		static GQuark _tmp13_label5 = 0;
		static GQuark _tmp13_label6 = 0;
		guint8 _tmp164_;
		_tmp1_ = i;
		_tmp2_ = widgettypes;
		_tmp3_ = g_variant_n_children (_tmp2_);
		if (!(((gsize) _tmp1_) < _tmp3_)) {
			break;
		}
		_tmp4_ = widgettypes;
		_tmp5_ = i;
		_tmp6_ = g_variant_get_child_value (_tmp4_, (gsize) _tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = g_variant_get_string (_tmp7_, NULL);
		_tmp9_ = g_strdup (_tmp8_);
		_tmp10_ = _tmp9_;
		_g_variant_unref0 (_tmp7_);
		type = _tmp10_;
		_tmp11_ = type;
		_tmp12_ = _tmp11_;
		_tmp14_ = (NULL == _tmp12_) ? 0 : g_quark_from_string (_tmp12_);
		if ((_tmp14_ == ((0 != _tmp13_label0) ? _tmp13_label0 : (_tmp13_label0 = g_quark_from_static_string ("scale")))) || (_tmp14_ == ((0 != _tmp13_label1) ? _tmp13_label1 : (_tmp13_label1 = g_quark_from_static_string ("sbtn"))))) {
			switch (0) {
				default:
				{
					gdouble val = 0.0;
					guint8 j;
					GtkBuilder* _tmp15_;
					const gchar* _tmp16_;
					gchar* _tmp17_;
					gchar* _tmp18_;
					gchar* _tmp19_;
					gchar* _tmp20_;
					GObject* _tmp21_ = NULL;
					GtkAdjustment* _tmp22_;
					GtkAdjustment* _tmp23_;
					GtkAdjustment* adjust;
					j = (guint8) 0;
					_tmp15_ = ((Main*) self)->builder;
					_tmp16_ = category;
					_tmp17_ = g_strconcat ("adjust_", _tmp16_, NULL);
					_tmp18_ = _tmp17_;
					_tmp19_ = g_strconcat (_tmp18_, "0", NULL);
					_tmp20_ = _tmp19_;
					_tmp21_ = gtk_builder_get_object (_tmp15_, _tmp20_);
					_tmp22_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp21_, GTK_TYPE_ADJUSTMENT) ? ((GtkAdjustment*) _tmp21_) : NULL);
					_tmp23_ = _tmp22_;
					_g_free0 (_tmp20_);
					_g_free0 (_tmp18_);
					adjust = _tmp23_;
					while (TRUE) {
						GtkAdjustment* _tmp24_;
						gchar* description;
						const gchar* _tmp25_;
						const gchar* _tmp26_;
						guint8 _tmp27_;
						GVariantIter* _tmp28_ = NULL;
						GVariantIter* iter;
						GVariantIter* _tmp29_;
						GtkAdjustment* _tmp30_;
						gdouble _tmp31_ = 0.0;
						JsonObject* _tmp32_;
						const gchar* _tmp33_;
						gdouble _tmp34_;
						guint8 _tmp35_;
						GtkBuilder* _tmp36_;
						const gchar* _tmp37_;
						gchar* _tmp38_;
						gchar* _tmp39_;
						guint8 _tmp40_;
						gchar* _tmp41_ = NULL;
						gchar* _tmp42_;
						gchar* _tmp43_;
						gchar* _tmp44_;
						GObject* _tmp45_ = NULL;
						GtkAdjustment* _tmp46_;
						_tmp24_ = adjust;
						if (!(_tmp24_ != NULL)) {
							break;
						}
						description = NULL;
						_tmp25_ = category;
						_tmp26_ = type;
						_tmp27_ = j;
						_tmp28_ = ns_widgets_query_get_description (_tmp25_, _tmp26_, _tmp27_);
						iter = _tmp28_;
						_tmp29_ = iter;
						g_variant_iter_next (_tmp29_, "s", &description, NULL);
						_tmp30_ = adjust;
						_tmp31_ = gtk_adjustment_get_value (_tmp30_);
						val = _tmp31_;
						_tmp32_ = object;
						_tmp33_ = description;
						_tmp34_ = val;
						json_object_set_double_member (_tmp32_, _tmp33_, _tmp34_);
						_tmp35_ = j;
						j = _tmp35_ + 1;
						_tmp36_ = ((Main*) self)->builder;
						_tmp37_ = category;
						_tmp38_ = g_strconcat ("adjust_", _tmp37_, NULL);
						_tmp39_ = _tmp38_;
						_tmp40_ = j;
						_tmp41_ = g_strdup_printf ("%d", _tmp40_);
						_tmp42_ = _tmp41_;
						_tmp43_ = g_strconcat (_tmp39_, _tmp42_, NULL);
						_tmp44_ = _tmp43_;
						_tmp45_ = gtk_builder_get_object (_tmp36_, _tmp44_);
						_tmp46_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp45_, GTK_TYPE_ADJUSTMENT) ? ((GtkAdjustment*) _tmp45_) : NULL);
						_g_object_unref0 (adjust);
						adjust = _tmp46_;
						_g_free0 (_tmp44_);
						_g_free0 (_tmp42_);
						_g_free0 (_tmp39_);
						_g_variant_iter_free0 (iter);
						_g_free0 (description);
					}
					_g_object_unref0 (adjust);
					break;
				}
			}
		} else if ((_tmp14_ == ((0 != _tmp13_label2) ? _tmp13_label2 : (_tmp13_label2 = g_quark_from_static_string ("cbtn")))) || (_tmp14_ == ((0 != _tmp13_label3) ? _tmp13_label3 : (_tmp13_label3 = g_quark_from_static_string ("rbtn"))))) {
			switch (0) {
				default:
				{
					gboolean val = FALSE;
					guint8 j;
					GtkBuilder* _tmp47_;
					const gchar* _tmp48_;
					gchar* _tmp49_;
					gchar* _tmp50_;
					const gchar* _tmp51_;
					gchar* _tmp52_;
					gchar* _tmp53_;
					gchar* _tmp54_;
					gchar* _tmp55_;
					GObject* _tmp56_ = NULL;
					GtkToggleButton* _tmp57_;
					GtkToggleButton* _tmp58_;
					GtkToggleButton* cbtn;
					j = (guint8) 0;
					_tmp47_ = ((Main*) self)->builder;
					_tmp48_ = type;
					_tmp49_ = g_strconcat (_tmp48_, "_", NULL);
					_tmp50_ = _tmp49_;
					_tmp51_ = category;
					_tmp52_ = g_strconcat (_tmp50_, _tmp51_, NULL);
					_tmp53_ = _tmp52_;
					_tmp54_ = g_strconcat (_tmp53_, "0", NULL);
					_tmp55_ = _tmp54_;
					_tmp56_ = gtk_builder_get_object (_tmp47_, _tmp55_);
					_tmp57_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp56_, GTK_TYPE_TOGGLE_BUTTON) ? ((GtkToggleButton*) _tmp56_) : NULL);
					_tmp58_ = _tmp57_;
					_g_free0 (_tmp55_);
					_g_free0 (_tmp53_);
					_g_free0 (_tmp50_);
					cbtn = _tmp58_;
					while (TRUE) {
						GtkToggleButton* _tmp59_;
						gchar* description;
						const gchar* _tmp60_;
						const gchar* _tmp61_;
						guint8 _tmp62_;
						GVariantIter* _tmp63_ = NULL;
						GVariantIter* iter;
						GVariantIter* _tmp64_;
						GtkToggleButton* _tmp65_;
						gboolean _tmp66_ = FALSE;
						JsonObject* _tmp67_;
						const gchar* _tmp68_;
						gboolean _tmp69_;
						guint8 _tmp70_;
						GtkBuilder* _tmp71_;
						const gchar* _tmp72_;
						gchar* _tmp73_;
						gchar* _tmp74_;
						const gchar* _tmp75_;
						gchar* _tmp76_;
						gchar* _tmp77_;
						guint8 _tmp78_;
						gchar* _tmp79_ = NULL;
						gchar* _tmp80_;
						gchar* _tmp81_;
						gchar* _tmp82_;
						GObject* _tmp83_ = NULL;
						GtkToggleButton* _tmp84_;
						_tmp59_ = cbtn;
						if (!(_tmp59_ != NULL)) {
							break;
						}
						description = NULL;
						_tmp60_ = category;
						_tmp61_ = type;
						_tmp62_ = j;
						_tmp63_ = ns_widgets_query_get_description (_tmp60_, _tmp61_, _tmp62_);
						iter = _tmp63_;
						_tmp64_ = iter;
						g_variant_iter_next (_tmp64_, "s", &description, NULL);
						_tmp65_ = cbtn;
						_tmp66_ = gtk_toggle_button_get_active (_tmp65_);
						val = _tmp66_;
						_tmp67_ = object;
						_tmp68_ = description;
						_tmp69_ = val;
						json_object_set_boolean_member (_tmp67_, _tmp68_, _tmp69_);
						_tmp70_ = j;
						j = _tmp70_ + 1;
						_tmp71_ = ((Main*) self)->builder;
						_tmp72_ = type;
						_tmp73_ = g_strconcat (_tmp72_, "_", NULL);
						_tmp74_ = _tmp73_;
						_tmp75_ = category;
						_tmp76_ = g_strconcat (_tmp74_, _tmp75_, NULL);
						_tmp77_ = _tmp76_;
						_tmp78_ = j;
						_tmp79_ = g_strdup_printf ("%d", _tmp78_);
						_tmp80_ = _tmp79_;
						_tmp81_ = g_strconcat (_tmp77_, _tmp80_, NULL);
						_tmp82_ = _tmp81_;
						_tmp83_ = gtk_builder_get_object (_tmp71_, _tmp82_);
						_tmp84_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp83_, GTK_TYPE_TOGGLE_BUTTON) ? ((GtkToggleButton*) _tmp83_) : NULL);
						_g_object_unref0 (cbtn);
						cbtn = _tmp84_;
						_g_free0 (_tmp82_);
						_g_free0 (_tmp80_);
						_g_free0 (_tmp77_);
						_g_free0 (_tmp74_);
						_g_variant_iter_free0 (iter);
						_g_free0 (description);
					}
					_g_object_unref0 (cbtn);
					break;
				}
			}
		} else if ((_tmp14_ == ((0 != _tmp13_label4) ? _tmp13_label4 : (_tmp13_label4 = g_quark_from_static_string ("e")))) || (_tmp14_ == ((0 != _tmp13_label5) ? _tmp13_label5 : (_tmp13_label5 = g_quark_from_static_string ("ce"))))) {
			switch (0) {
				default:
				{
					gchar* val = NULL;
					guint8 j;
					GtkBuilder* _tmp85_;
					const gchar* _tmp86_;
					gchar* _tmp87_;
					gchar* _tmp88_;
					const gchar* _tmp89_;
					gchar* _tmp90_;
					gchar* _tmp91_;
					gchar* _tmp92_;
					gchar* _tmp93_;
					GObject* _tmp94_ = NULL;
					GtkEntry* _tmp95_;
					GtkEntry* _tmp96_;
					GtkEntry* e;
					j = (guint8) 0;
					_tmp85_ = ((Main*) self)->builder;
					_tmp86_ = type;
					_tmp87_ = g_strconcat (_tmp86_, "_", NULL);
					_tmp88_ = _tmp87_;
					_tmp89_ = category;
					_tmp90_ = g_strconcat (_tmp88_, _tmp89_, NULL);
					_tmp91_ = _tmp90_;
					_tmp92_ = g_strconcat (_tmp91_, "0", NULL);
					_tmp93_ = _tmp92_;
					_tmp94_ = gtk_builder_get_object (_tmp85_, _tmp93_);
					_tmp95_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp94_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp94_) : NULL);
					_tmp96_ = _tmp95_;
					_g_free0 (_tmp93_);
					_g_free0 (_tmp91_);
					_g_free0 (_tmp88_);
					e = _tmp96_;
					while (TRUE) {
						GtkEntry* _tmp97_;
						gchar* description;
						const gchar* _tmp98_;
						const gchar* _tmp99_;
						guint8 _tmp100_;
						GVariantIter* _tmp101_ = NULL;
						GVariantIter* iter;
						GVariantIter* _tmp102_;
						GtkEntry* _tmp103_;
						const gchar* _tmp104_ = NULL;
						gchar* _tmp105_;
						JsonObject* _tmp106_;
						const gchar* _tmp107_;
						const gchar* _tmp108_;
						guint8 _tmp109_;
						GtkBuilder* _tmp110_;
						const gchar* _tmp111_;
						gchar* _tmp112_;
						gchar* _tmp113_;
						const gchar* _tmp114_;
						gchar* _tmp115_;
						gchar* _tmp116_;
						guint8 _tmp117_;
						gchar* _tmp118_ = NULL;
						gchar* _tmp119_;
						gchar* _tmp120_;
						gchar* _tmp121_;
						GObject* _tmp122_ = NULL;
						GtkEntry* _tmp123_;
						_tmp97_ = e;
						if (!(_tmp97_ != NULL)) {
							break;
						}
						description = NULL;
						_tmp98_ = category;
						_tmp99_ = type;
						_tmp100_ = j;
						_tmp101_ = ns_widgets_query_get_description (_tmp98_, _tmp99_, _tmp100_);
						iter = _tmp101_;
						_tmp102_ = iter;
						g_variant_iter_next (_tmp102_, "s", &description, NULL);
						_tmp103_ = e;
						_tmp104_ = gtk_entry_get_text (_tmp103_);
						_tmp105_ = g_strdup (_tmp104_);
						_g_free0 (val);
						val = _tmp105_;
						_tmp106_ = object;
						_tmp107_ = description;
						_tmp108_ = val;
						json_object_set_string_member (_tmp106_, _tmp107_, _tmp108_);
						_tmp109_ = j;
						j = _tmp109_ + 1;
						_tmp110_ = ((Main*) self)->builder;
						_tmp111_ = type;
						_tmp112_ = g_strconcat (_tmp111_, "_", NULL);
						_tmp113_ = _tmp112_;
						_tmp114_ = category;
						_tmp115_ = g_strconcat (_tmp113_, _tmp114_, NULL);
						_tmp116_ = _tmp115_;
						_tmp117_ = j;
						_tmp118_ = g_strdup_printf ("%d", _tmp117_);
						_tmp119_ = _tmp118_;
						_tmp120_ = g_strconcat (_tmp116_, _tmp119_, NULL);
						_tmp121_ = _tmp120_;
						_tmp122_ = gtk_builder_get_object (_tmp110_, _tmp121_);
						_tmp123_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp122_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp122_) : NULL);
						_g_object_unref0 (e);
						e = _tmp123_;
						_g_free0 (_tmp121_);
						_g_free0 (_tmp119_);
						_g_free0 (_tmp116_);
						_g_free0 (_tmp113_);
						_g_variant_iter_free0 (iter);
						_g_free0 (description);
					}
					_g_object_unref0 (e);
					_g_free0 (val);
					break;
				}
			}
		} else if (_tmp14_ == ((0 != _tmp13_label6) ? _tmp13_label6 : (_tmp13_label6 = g_quark_from_static_string ("lbl")))) {
			switch (0) {
				default:
				{
					gchar* val = NULL;
					guint8 j;
					GtkLabel* lbl;
					GtkBuilder* _tmp124_;
					const gchar* _tmp125_;
					gchar* _tmp126_;
					gchar* _tmp127_;
					const gchar* _tmp128_;
					gchar* _tmp129_;
					gchar* _tmp130_;
					gchar* _tmp131_;
					gchar* _tmp132_;
					GObject* _tmp133_ = NULL;
					GtkLabel* _tmp134_;
					j = (guint8) 0;
					lbl = NULL;
					_tmp124_ = ((Main*) self)->builder;
					_tmp125_ = type;
					_tmp126_ = g_strconcat (_tmp125_, "_", NULL);
					_tmp127_ = _tmp126_;
					_tmp128_ = category;
					_tmp129_ = g_strconcat (_tmp127_, _tmp128_, NULL);
					_tmp130_ = _tmp129_;
					_tmp131_ = g_strconcat (_tmp130_, "0", NULL);
					_tmp132_ = _tmp131_;
					_tmp133_ = gtk_builder_get_object (_tmp124_, _tmp132_);
					_tmp134_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp133_, GTK_TYPE_LABEL) ? ((GtkLabel*) _tmp133_) : NULL);
					_g_object_unref0 (lbl);
					lbl = _tmp134_;
					_g_free0 (_tmp132_);
					_g_free0 (_tmp130_);
					_g_free0 (_tmp127_);
					while (TRUE) {
						GtkLabel* _tmp135_;
						gchar* description;
						const gchar* _tmp136_;
						const gchar* _tmp137_;
						guint8 _tmp138_;
						GVariantIter* _tmp139_ = NULL;
						GVariantIter* iter;
						GVariantIter* _tmp140_;
						GtkLabel* _tmp141_;
						const gchar* _tmp142_ = NULL;
						gchar* _tmp143_;
						JsonObject* _tmp144_;
						const gchar* _tmp145_;
						const gchar* _tmp146_;
						guint8 _tmp147_;
						GtkBuilder* _tmp148_;
						const gchar* _tmp149_;
						gchar* _tmp150_;
						gchar* _tmp151_;
						const gchar* _tmp152_;
						gchar* _tmp153_;
						gchar* _tmp154_;
						guint8 _tmp155_;
						gchar* _tmp156_ = NULL;
						gchar* _tmp157_;
						gchar* _tmp158_;
						gchar* _tmp159_;
						GObject* _tmp160_ = NULL;
						GtkLabel* _tmp161_;
						_tmp135_ = lbl;
						if (!(_tmp135_ != NULL)) {
							break;
						}
						description = NULL;
						_tmp136_ = category;
						_tmp137_ = type;
						_tmp138_ = j;
						_tmp139_ = ns_widgets_query_get_description (_tmp136_, _tmp137_, _tmp138_);
						iter = _tmp139_;
						_tmp140_ = iter;
						g_variant_iter_next (_tmp140_, "s", &description, NULL);
						_tmp141_ = lbl;
						_tmp142_ = gtk_label_get_text (_tmp141_);
						_tmp143_ = g_strdup (_tmp142_);
						_g_free0 (val);
						val = _tmp143_;
						_tmp144_ = object;
						_tmp145_ = description;
						_tmp146_ = val;
						json_object_set_string_member (_tmp144_, _tmp145_, _tmp146_);
						_tmp147_ = j;
						j = _tmp147_ + 1;
						_g_object_unref0 (lbl);
						lbl = NULL;
						_tmp148_ = ((Main*) self)->builder;
						_tmp149_ = type;
						_tmp150_ = g_strconcat (_tmp149_, "_", NULL);
						_tmp151_ = _tmp150_;
						_tmp152_ = category;
						_tmp153_ = g_strconcat (_tmp151_, _tmp152_, NULL);
						_tmp154_ = _tmp153_;
						_tmp155_ = j;
						_tmp156_ = g_strdup_printf ("%d", _tmp155_);
						_tmp157_ = _tmp156_;
						_tmp158_ = g_strconcat (_tmp154_, _tmp157_, NULL);
						_tmp159_ = _tmp158_;
						_tmp160_ = gtk_builder_get_object (_tmp148_, _tmp159_);
						_tmp161_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp160_, GTK_TYPE_LABEL) ? ((GtkLabel*) _tmp160_) : NULL);
						_g_object_unref0 (lbl);
						lbl = _tmp161_;
						_g_free0 (_tmp159_);
						_g_free0 (_tmp157_);
						_g_free0 (_tmp154_);
						_g_free0 (_tmp151_);
						_g_variant_iter_free0 (iter);
						_g_free0 (description);
					}
					_g_object_unref0 (lbl);
					_g_free0 (val);
					break;
				}
			}
		} else {
			switch (0) {
				default:
				{
					FILE* _tmp162_;
					const gchar* _tmp163_;
					_tmp162_ = stdout;
					_tmp163_ = type;
					fprintf (_tmp162_, "unknown type, %s\n", _tmp163_);
					break;
				}
			}
		}
		_tmp164_ = i;
		i = _tmp164_ + 1;
		_g_free0 (type);
	}
	result = object;
	return result;
}


GVariantIter* ns_widgets_query_get_description (const gchar* category, const gchar* type, guint8 number) {
	GVariantIter* result = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	guint8 _tmp6_;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* defaultstring;
	const gchar* _tmp11_;
	GVariant* _tmp12_;
	GVariant* var1;
	const gchar* _tmp13_;
	const gchar* _tmp14_;
	GQuark _tmp16_ = 0U;
	static GQuark _tmp15_label0 = 0;
	static GQuark _tmp15_label1 = 0;
	static GQuark _tmp15_label2 = 0;
	g_return_val_if_fail (category != NULL, NULL);
	g_return_val_if_fail (type != NULL, NULL);
	_tmp0_ = type;
	_tmp1_ = g_strconcat (_tmp0_, "_", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = category;
	_tmp4_ = g_strconcat (_tmp2_, _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = number;
	_tmp7_ = g_strdup_printf ("%d", _tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = g_strconcat (_tmp5_, _tmp8_, NULL);
	_tmp10_ = _tmp9_;
	_g_free0 (_tmp8_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp2_);
	defaultstring = _tmp10_;
	_tmp11_ = defaultstring;
	_tmp12_ = g_variant_new ("(s)", _tmp11_, NULL);
	g_variant_ref_sink (_tmp12_);
	var1 = _tmp12_;
	_tmp13_ = category;
	_tmp14_ = _tmp13_;
	_tmp16_ = (NULL == _tmp14_) ? 0 : g_quark_from_string (_tmp14_);
	if (_tmp16_ == ((0 != _tmp15_label0) ? _tmp15_label0 : (_tmp15_label0 = g_quark_from_static_string ("quality")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp17_;
				const gchar* _tmp30_;
				const gchar* _tmp43_;
				GVariant* _tmp46_;
				GVariantIter* _tmp47_ = NULL;
				_tmp17_ = type;
				if (g_strcmp0 (_tmp17_, "scale") == 0) {
					guint8 _tmp18_;
					guint8 _tmp20_;
					guint8 _tmp22_;
					guint8 _tmp24_;
					guint8 _tmp26_;
					guint8 _tmp28_;
					_tmp18_ = number;
					if (((gint) _tmp18_) == 0) {
						GVariant* _tmp19_;
						_tmp19_ = g_variant_new ("(s)", "Video Quality", NULL);
						g_variant_ref_sink (_tmp19_);
						_g_variant_unref0 (var1);
						var1 = _tmp19_;
					}
					_tmp20_ = number;
					if (((gint) _tmp20_) == 1) {
						GVariant* _tmp21_;
						_tmp21_ = g_variant_new ("(s)", "Audio Quality", NULL);
						g_variant_ref_sink (_tmp21_);
						_g_variant_unref0 (var1);
						var1 = _tmp21_;
					}
					_tmp22_ = number;
					if (((gint) _tmp22_) == 2) {
						GVariant* _tmp23_;
						_tmp23_ = g_variant_new ("(s)", "Video Bitrate", NULL);
						g_variant_ref_sink (_tmp23_);
						_g_variant_unref0 (var1);
						var1 = _tmp23_;
					}
					_tmp24_ = number;
					if (((gint) _tmp24_) == 3) {
						GVariant* _tmp25_;
						_tmp25_ = g_variant_new ("(s)", "Audio Bitrate", NULL);
						g_variant_ref_sink (_tmp25_);
						_g_variant_unref0 (var1);
						var1 = _tmp25_;
					}
					_tmp26_ = number;
					if (((gint) _tmp26_) == 4) {
						GVariant* _tmp27_;
						_tmp27_ = g_variant_new ("(s)", "Height", NULL);
						g_variant_ref_sink (_tmp27_);
						_g_variant_unref0 (var1);
						var1 = _tmp27_;
					}
					_tmp28_ = number;
					if (((gint) _tmp28_) == 5) {
						GVariant* _tmp29_;
						_tmp29_ = g_variant_new ("(s)", "Framerate", NULL);
						g_variant_ref_sink (_tmp29_);
						_g_variant_unref0 (var1);
						var1 = _tmp29_;
					}
				}
				_tmp30_ = type;
				if (g_strcmp0 (_tmp30_, "cbtn") == 0) {
					guint8 _tmp31_;
					guint8 _tmp33_;
					guint8 _tmp35_;
					guint8 _tmp37_;
					guint8 _tmp39_;
					guint8 _tmp41_;
					_tmp31_ = number;
					if (((gint) _tmp31_) == 0) {
						GVariant* _tmp32_;
						_tmp32_ = g_variant_new ("(s)", "use specific Video Bitrate", NULL);
						g_variant_ref_sink (_tmp32_);
						_g_variant_unref0 (var1);
						var1 = _tmp32_;
					}
					_tmp33_ = number;
					if (((gint) _tmp33_) == 1) {
						GVariant* _tmp34_;
						_tmp34_ = g_variant_new ("(s)", "use specific Audio Bitrate", NULL);
						g_variant_ref_sink (_tmp34_);
						_g_variant_unref0 (var1);
						var1 = _tmp34_;
					}
					_tmp35_ = number;
					if (((gint) _tmp35_) == 2) {
						GVariant* _tmp36_;
						_tmp36_ = g_variant_new ("(s)", "same framerate as source file", NULL);
						g_variant_ref_sink (_tmp36_);
						_g_variant_unref0 (var1);
						var1 = _tmp36_;
					}
					_tmp37_ = number;
					if (((gint) _tmp37_) == 3) {
						GVariant* _tmp38_;
						_tmp38_ = g_variant_new ("(s)", "enable optimization", NULL);
						g_variant_ref_sink (_tmp38_);
						_g_variant_unref0 (var1);
						var1 = _tmp38_;
					}
					_tmp39_ = number;
					if (((gint) _tmp39_) == 4) {
						GVariant* _tmp40_;
						_tmp40_ = g_variant_new ("(s)", "use soft-target", NULL);
						g_variant_ref_sink (_tmp40_);
						_g_variant_unref0 (var1);
						var1 = _tmp40_;
					}
					_tmp41_ = number;
					if (((gint) _tmp41_) == 5) {
						GVariant* _tmp42_;
						_tmp42_ = g_variant_new ("(s)", "use two-pass rate control", NULL);
						g_variant_ref_sink (_tmp42_);
						_g_variant_unref0 (var1);
						var1 = _tmp42_;
					}
				}
				_tmp43_ = type;
				if (g_strcmp0 (_tmp43_, "e") == 0) {
					guint8 _tmp44_;
					_tmp44_ = number;
					if (((gint) _tmp44_) == 0) {
						GVariant* _tmp45_;
						_tmp45_ = g_variant_new ("(s)", "Width", NULL);
						g_variant_ref_sink (_tmp45_);
						_g_variant_unref0 (var1);
						var1 = _tmp45_;
					}
				}
				_tmp46_ = var1;
				_tmp47_ = g_variant_iter_new (_tmp46_);
				result = _tmp47_;
				_g_variant_unref0 (var1);
				_g_free0 (defaultstring);
				return result;
			}
		}
	} else if (_tmp16_ == ((0 != _tmp15_label1) ? _tmp15_label1 : (_tmp15_label1 = g_quark_from_static_string ("color")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp48_;
				GVariant* _tmp57_;
				GVariantIter* _tmp58_ = NULL;
				_tmp48_ = type;
				if (g_strcmp0 (_tmp48_, "scale") == 0) {
					guint8 _tmp49_;
					guint8 _tmp51_;
					guint8 _tmp53_;
					guint8 _tmp55_;
					_tmp49_ = number;
					if (((gint) _tmp49_) == 0) {
						GVariant* _tmp50_;
						_tmp50_ = g_variant_new ("(s)", "Contrast", NULL);
						g_variant_ref_sink (_tmp50_);
						_g_variant_unref0 (var1);
						var1 = _tmp50_;
					}
					_tmp51_ = number;
					if (((gint) _tmp51_) == 1) {
						GVariant* _tmp52_;
						_tmp52_ = g_variant_new ("(s)", "Brightness", NULL);
						g_variant_ref_sink (_tmp52_);
						_g_variant_unref0 (var1);
						var1 = _tmp52_;
					}
					_tmp53_ = number;
					if (((gint) _tmp53_) == 2) {
						GVariant* _tmp54_;
						_tmp54_ = g_variant_new ("(s)", "Gamma", NULL);
						g_variant_ref_sink (_tmp54_);
						_g_variant_unref0 (var1);
						var1 = _tmp54_;
					}
					_tmp55_ = number;
					if (((gint) _tmp55_) == 3) {
						GVariant* _tmp56_;
						_tmp56_ = g_variant_new ("(s)", "Saturation", NULL);
						g_variant_ref_sink (_tmp56_);
						_g_variant_unref0 (var1);
						var1 = _tmp56_;
					}
				}
				_tmp57_ = var1;
				_tmp58_ = g_variant_iter_new (_tmp57_);
				result = _tmp58_;
				_g_variant_unref0 (var1);
				_g_free0 (defaultstring);
				return result;
			}
		}
	} else if (_tmp16_ == ((0 != _tmp15_label2) ? _tmp15_label2 : (_tmp15_label2 = g_quark_from_static_string ("terminal")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp59_;
				const gchar* _tmp62_;
				GVariant* _tmp65_;
				GVariantIter* _tmp66_ = NULL;
				_tmp59_ = type;
				if (g_strcmp0 (_tmp59_, "e") == 0) {
					guint8 _tmp60_;
					_tmp60_ = number;
					if (((gint) _tmp60_) == 0) {
						GVariant* _tmp61_;
						_tmp61_ = g_variant_new ("(s)", "Additional parameters", NULL);
						g_variant_ref_sink (_tmp61_);
						_g_variant_unref0 (var1);
						var1 = _tmp61_;
					}
				}
				_tmp62_ = type;
				if (g_strcmp0 (_tmp62_, "ce") == 0) {
					guint8 _tmp63_;
					_tmp63_ = number;
					if (((gint) _tmp63_) == 0) {
						GVariant* _tmp64_;
						_tmp64_ = g_variant_new ("(s)", "Terminal", NULL);
						g_variant_ref_sink (_tmp64_);
						_g_variant_unref0 (var1);
						var1 = _tmp64_;
					}
				}
				_tmp65_ = var1;
				_tmp66_ = g_variant_iter_new (_tmp65_);
				result = _tmp66_;
				_g_variant_unref0 (var1);
				_g_free0 (defaultstring);
				return result;
			}
		}
	} else {
		switch (0) {
			default:
			{
				GVariant* _tmp67_;
				GVariantIter* _tmp68_ = NULL;
				_tmp67_ = var1;
				_tmp68_ = g_variant_iter_new (_tmp67_);
				result = _tmp68_;
				_g_variant_unref0 (var1);
				_g_free0 (defaultstring);
				return result;
			}
		}
	}
	_g_variant_unref0 (var1);
	_g_free0 (defaultstring);
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		const gchar* _tmp0_;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		GRegex* _tmp3_;
		GRegex* _tmp4_;
		GRegex* regex;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch3_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp5_ = regex;
		_tmp6_ = replacement;
		_tmp7_ = g_regex_replace_literal (_tmp5_, self, (gssize) (-1), 0, _tmp6_, 0, &_inner_error_);
		_tmp8_ = _tmp7_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch3_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		result = _tmp8_;
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally3;
	__catch3_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally3:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


void on_btn_preview_clicked (GtkButton* sender, NSWidgetsQuery* self) {
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkLabel* _tmp2_;
	GtkLabel* start_lbl;
	GtkBuilder* _tmp3_;
	GObject* _tmp4_ = NULL;
	GtkLabel* _tmp5_;
	GtkLabel* end_lbl;
	GtkButton* _tmp6_;
	GtkWidget* _tmp7_ = NULL;
	GtkGrid* _tmp8_;
	GtkGrid* preview_grid;
	GtkGrid* _tmp9_;
	GtkWidget* _tmp10_ = NULL;
	GtkEntry* _tmp11_;
	GtkEntry* minutes_e;
	GtkGrid* _tmp12_;
	GtkWidget* _tmp13_ = NULL;
	GtkSpinButton* _tmp14_;
	GtkSpinButton* seconds_sbtn;
	GtkGrid* _tmp15_;
	GtkWidget* _tmp16_ = NULL;
	GtkSpinButton* _tmp17_;
	GtkSpinButton* duration_sbtn;
	GtkEntry* _tmp18_;
	const gchar* _tmp19_ = NULL;
	gint _tmp20_ = 0;
	GtkSpinButton* _tmp21_;
	gint _tmp22_ = 0;
	gint starttime;
	gint _tmp23_;
	GtkSpinButton* _tmp24_;
	gint _tmp25_ = 0;
	gint endtime;
	GtkLabel* _tmp26_;
	gint _tmp27_;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_;
	GtkLabel* _tmp30_;
	gint _tmp31_;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_;
	NSFileSaving* _tmp34_;
	NSFileSaving* save;
	NSCommandCreation* _tmp35_;
	NSCommandCreation* command;
	NSCommandCreation* _tmp36_;
	const gchar* _tmp37_;
	const gchar* _tmp38_;
	gchar* _tmp39_;
	gchar* c;
	GtkBuilder* _tmp40_;
	GObject* _tmp41_ = NULL;
	GtkToggleButton* _tmp42_;
	GtkToggleButton* subtitle_file_rbtn;
	GtkToggleButton* _tmp43_;
	gboolean _tmp44_ = FALSE;
	GtkBuilder* _tmp55_;
	GObject* _tmp56_ = NULL;
	GtkFileChooser* _tmp57_;
	GtkFileChooser* source_fbtn;
	GtkFileChooser* _tmp58_;
	gchar* _tmp59_ = NULL;
	gchar* input;
	const gchar* _tmp60_ = NULL;
	gchar* _tmp61_;
	gchar* tmp_dir;
	const gchar* _tmp62_;
	gchar* _tmp63_;
	gchar* _tmp64_;
	const gchar* _tmp65_;
	gchar* _tmp66_;
	gchar* _tmp67_;
	gchar* _tmp68_;
	gchar* _tmp69_;
	const gchar* _tmp70_;
	gchar* _tmp71_;
	gchar* _tmp72_;
	gchar* _tmp73_;
	GtkBuilder* _tmp74_;
	GObject* _tmp75_ = NULL;
	GtkToggleButton* _tmp76_;
	GtkToggleButton* cbtn_more_speed;
	GtkToggleButton* _tmp77_;
	gboolean _tmp78_ = FALSE;
	FILE* _tmp85_;
	const gchar* _tmp86_;
	GtkBuilder* _tmp87_;
	GObject* _tmp88_ = NULL;
	GtkStatusbar* _tmp89_;
	GtkStatusbar* sbar;
	const gchar* _tmp90_;
	gchar* _tmp91_;
	gchar* _tmp92_;
	const gchar* _tmp93_;
	NSCommandExecution* _tmp94_;
	NSCommandExecution* process;
	const gchar* _tmp95_;
	GtkBuilder* _tmp96_;
	GObject* _tmp97_ = NULL;
	GtkComboBoxText* _tmp98_;
	GtkComboBoxText* cboxt_player;
	const gchar* _tmp99_ = NULL;
	gchar* _tmp100_;
	gchar* player;
	gchar* _tmp101_;
	gchar* _tmp102_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "lbl_basics0");
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, GTK_TYPE_LABEL) ? ((GtkLabel*) _tmp1_) : NULL);
	start_lbl = _tmp2_;
	_tmp3_ = ((Main*) self)->builder;
	_tmp4_ = gtk_builder_get_object (_tmp3_, "lbl_basics1");
	_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, GTK_TYPE_LABEL) ? ((GtkLabel*) _tmp4_) : NULL);
	end_lbl = _tmp5_;
	_tmp6_ = sender;
	_tmp7_ = gtk_widget_get_parent ((GtkWidget*) _tmp6_);
	_tmp8_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, GTK_TYPE_GRID) ? ((GtkGrid*) _tmp7_) : NULL);
	preview_grid = _tmp8_;
	_tmp9_ = preview_grid;
	_tmp10_ = gtk_grid_get_child_at (_tmp9_, 0, 1);
	_tmp11_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp10_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp10_) : NULL);
	minutes_e = _tmp11_;
	_tmp12_ = preview_grid;
	_tmp13_ = gtk_grid_get_child_at (_tmp12_, 1, 1);
	_tmp14_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, GTK_TYPE_SPIN_BUTTON) ? ((GtkSpinButton*) _tmp13_) : NULL);
	seconds_sbtn = _tmp14_;
	_tmp15_ = preview_grid;
	_tmp16_ = gtk_grid_get_child_at (_tmp15_, 2, 1);
	_tmp17_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp16_, GTK_TYPE_SPIN_BUTTON) ? ((GtkSpinButton*) _tmp16_) : NULL);
	duration_sbtn = _tmp17_;
	_tmp18_ = minutes_e;
	_tmp19_ = gtk_entry_get_text (_tmp18_);
	_tmp20_ = atoi (_tmp19_);
	_tmp21_ = seconds_sbtn;
	_tmp22_ = gtk_spin_button_get_value_as_int (_tmp21_);
	starttime = (_tmp20_ * 60) + _tmp22_;
	_tmp23_ = starttime;
	_tmp24_ = duration_sbtn;
	_tmp25_ = gtk_spin_button_get_value_as_int (_tmp24_);
	endtime = _tmp23_ + _tmp25_;
	_tmp26_ = start_lbl;
	_tmp27_ = starttime;
	_tmp28_ = g_strdup_printf ("%d", _tmp27_);
	_tmp29_ = _tmp28_;
	gtk_label_set_text (_tmp26_, _tmp29_);
	_g_free0 (_tmp29_);
	_tmp30_ = end_lbl;
	_tmp31_ = endtime;
	_tmp32_ = g_strdup_printf ("%d", _tmp31_);
	_tmp33_ = _tmp32_;
	gtk_label_set_text (_tmp30_, _tmp33_);
	_g_free0 (_tmp33_);
	update_rootobject ((guint8) 0, self);
	_tmp34_ = ns_file_saving_new ("last_" MAIN_LAST_PROFILE ".json");
	save = _tmp34_;
	_tmp35_ = ns_command_creation_new ();
	command = _tmp35_;
	_tmp36_ = command;
	_tmp37_ = ns_command_creation_get_conversion_command (_tmp36_);
	_tmp38_ = _tmp37_;
	_tmp39_ = g_strdup (_tmp38_);
	c = _tmp39_;
	_tmp40_ = ((Main*) self)->builder;
	_tmp41_ = gtk_builder_get_object (_tmp40_, "rbtn_basics1");
	_tmp42_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp41_, GTK_TYPE_TOGGLE_BUTTON) ? ((GtkToggleButton*) _tmp41_) : NULL);
	subtitle_file_rbtn = _tmp42_;
	_tmp43_ = subtitle_file_rbtn;
	_tmp44_ = gtk_toggle_button_get_active (_tmp43_);
	if (_tmp44_ == TRUE) {
		GtkBuilder* _tmp45_;
		GObject* _tmp46_ = NULL;
		GtkFileChooser* _tmp47_;
		GtkFileChooser* subtitle_fbtn;
		const gchar* _tmp48_;
		gchar* _tmp49_;
		gchar* _tmp50_;
		GtkFileChooser* _tmp51_;
		gchar* _tmp52_ = NULL;
		gchar* _tmp53_;
		gchar* _tmp54_;
		_tmp45_ = ((Main*) self)->builder;
		_tmp46_ = gtk_builder_get_object (_tmp45_, "fbtn_basics1");
		_tmp47_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp46_, GTK_TYPE_FILE_CHOOSER) ? ((GtkFileChooser*) _tmp46_) : NULL);
		subtitle_fbtn = _tmp47_;
		_tmp48_ = c;
		_tmp49_ = g_strconcat (_tmp48_, " --subtitles ", NULL);
		_tmp50_ = _tmp49_;
		_tmp51_ = subtitle_fbtn;
		_tmp52_ = gtk_file_chooser_get_filename (_tmp51_);
		_tmp53_ = _tmp52_;
		_tmp54_ = g_strconcat (_tmp50_, _tmp53_, NULL);
		_g_free0 (c);
		c = _tmp54_;
		_g_free0 (_tmp53_);
		_g_free0 (_tmp50_);
		_g_object_unref0 (subtitle_fbtn);
	}
	_tmp55_ = ((Main*) self)->builder;
	_tmp56_ = gtk_builder_get_object (_tmp55_, "fbtn_basics0");
	_tmp57_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp56_, GTK_TYPE_FILE_CHOOSER) ? ((GtkFileChooser*) _tmp56_) : NULL);
	source_fbtn = _tmp57_;
	_tmp58_ = source_fbtn;
	_tmp59_ = gtk_file_chooser_get_filename (_tmp58_);
	input = _tmp59_;
	_tmp60_ = g_get_tmp_dir ();
	_tmp61_ = g_strdup (_tmp60_);
	tmp_dir = _tmp61_;
	_tmp62_ = c;
	_tmp63_ = g_strconcat (_tmp62_, " '", NULL);
	_tmp64_ = _tmp63_;
	_tmp65_ = input;
	_tmp66_ = g_strconcat (_tmp64_, _tmp65_, NULL);
	_tmp67_ = _tmp66_;
	_tmp68_ = g_strconcat (_tmp67_, "' -o ", NULL);
	_tmp69_ = _tmp68_;
	_tmp70_ = tmp_dir;
	_tmp71_ = g_strconcat (_tmp69_, _tmp70_, NULL);
	_tmp72_ = _tmp71_;
	_tmp73_ = g_strconcat (_tmp72_, "/preview.ogv", NULL);
	_g_free0 (c);
	c = _tmp73_;
	_g_free0 (_tmp72_);
	_g_free0 (_tmp69_);
	_g_free0 (_tmp67_);
	_g_free0 (_tmp64_);
	_tmp74_ = ((Main*) self)->builder;
	_tmp75_ = gtk_builder_get_object (_tmp74_, "cbtn_preview");
	_tmp76_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp75_, GTK_TYPE_TOGGLE_BUTTON) ? ((GtkToggleButton*) _tmp75_) : NULL);
	cbtn_more_speed = _tmp76_;
	_tmp77_ = cbtn_more_speed;
	_tmp78_ = gtk_toggle_button_get_active (_tmp77_);
	if (_tmp78_ == TRUE) {
		const gchar* _tmp79_;
		gchar* _tmp80_ = NULL;
		const gchar* _tmp81_;
		gchar* _tmp82_ = NULL;
		const gchar* _tmp83_;
		gchar* _tmp84_ = NULL;
		_tmp79_ = c;
		_tmp80_ = string_replace (_tmp79_, "--optimize", "");
		_g_free0 (c);
		c = _tmp80_;
		_tmp81_ = c;
		_tmp82_ = string_replace (_tmp81_, "--two-pass", "");
		_g_free0 (c);
		c = _tmp82_;
		_tmp83_ = c;
		_tmp84_ = string_replace (_tmp83_, "ffmpeg2theora --st", "ffmpeg2theora --speedlevel 2 --st");
		_g_free0 (c);
		c = _tmp84_;
	}
	_tmp85_ = stdout;
	_tmp86_ = c;
	fprintf (_tmp85_, "execute command: \n %s\n", _tmp86_);
	_tmp87_ = ((Main*) self)->builder;
	_tmp88_ = gtk_builder_get_object (_tmp87_, "sbar");
	_tmp89_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp88_, GTK_TYPE_STATUSBAR) ? ((GtkStatusbar*) _tmp88_) : NULL);
	sbar = _tmp89_;
	_tmp90_ = c;
	_tmp91_ = g_strconcat ("executed: ", _tmp90_, NULL);
	_tmp92_ = _tmp91_;
	gtk_statusbar_push (sbar, (guint) 0, _tmp92_);
	_g_free0 (_tmp92_);
	_tmp93_ = c;
	gtk_widget_set_tooltip_text ((GtkWidget*) sbar, _tmp93_);
	_tmp94_ = ns_command_execution_new ();
	process = _tmp94_;
	_tmp95_ = c;
	ns_command_execution_sync_command (process, _tmp95_);
	_tmp96_ = ((Main*) self)->builder;
	_tmp97_ = gtk_builder_get_object (_tmp96_, "cboxt_crop");
	_tmp98_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp97_, GTK_TYPE_COMBO_BOX_TEXT) ? ((GtkComboBoxText*) _tmp97_) : NULL);
	cboxt_player = _tmp98_;
	_tmp99_ = gtk_combo_box_text_get_active_text (cboxt_player);
	_tmp100_ = g_strdup (_tmp99_);
	player = _tmp100_;
	_tmp101_ = g_strconcat (player, " '/tmp/preview.ogv'", NULL);
	_tmp102_ = _tmp101_;
	ns_command_execution_async_command (process, _tmp102_);
	_g_free0 (_tmp102_);
	_g_free0 (player);
	_g_object_unref0 (cboxt_player);
	_g_object_unref0 (process);
	_g_object_unref0 (sbar);
	_g_object_unref0 (cbtn_more_speed);
	_g_free0 (tmp_dir);
	_g_free0 (input);
	_g_object_unref0 (source_fbtn);
	_g_object_unref0 (subtitle_file_rbtn);
	_g_free0 (c);
	_g_object_unref0 (command);
	_g_object_unref0 (save);
	_g_object_unref0 (duration_sbtn);
	_g_object_unref0 (seconds_sbtn);
	_g_object_unref0 (minutes_e);
	_g_object_unref0 (preview_grid);
	_g_object_unref0 (end_lbl);
	_g_object_unref0 (start_lbl);
}


JsonGenerator* ns_widgets_query_get_generator (void) {
	JsonGenerator* result;
	JsonGenerator* _tmp0_;
	_tmp0_ = ns_widgets_query__generator;
	result = _tmp0_;
	return result;
}


static void ns_widgets_query_class_init (NSWidgetsQueryClass * klass) {
	ns_widgets_query_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = _vala_ns_widgets_query_get_property;
	G_OBJECT_CLASS (klass)->finalize = ns_widgets_query_finalize;
}


static void ns_widgets_query_instance_init (NSWidgetsQuery * self) {
}


static void ns_widgets_query_finalize (GObject* obj) {
	NSWidgetsQuery * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NS_WIDGETS_TYPE_QUERY, NSWidgetsQuery);
	G_OBJECT_CLASS (ns_widgets_query_parent_class)->finalize (obj);
}


GType ns_widgets_query_get_type (void) {
	static volatile gsize ns_widgets_query_type_id__volatile = 0;
	if (g_once_init_enter (&ns_widgets_query_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (NSWidgetsQueryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ns_widgets_query_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NSWidgetsQuery), 0, (GInstanceInitFunc) ns_widgets_query_instance_init, NULL };
		GType ns_widgets_query_type_id;
		ns_widgets_query_type_id = g_type_register_static (TYPE_MAIN, "NSWidgetsQuery", &g_define_type_info, 0);
		g_once_init_leave (&ns_widgets_query_type_id__volatile, ns_widgets_query_type_id);
	}
	return ns_widgets_query_type_id__volatile;
}


static void _vala_ns_widgets_query_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	NSWidgetsQuery * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NS_WIDGETS_TYPE_QUERY, NSWidgetsQuery);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



