/* widgets-adjutment.c generated by valac 0.18.1, the Vala compiler
 * generated from widgets-adjutment.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <stdio.h>


#define NS_WIDGETS_TYPE_ADJUSTMENT (ns_widgets_adjustment_get_type ())
#define NS_WIDGETS_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustment))
#define NS_WIDGETS_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustmentClass))
#define NS_WIDGETS_IS_ADJUSTMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_WIDGETS_TYPE_ADJUSTMENT))
#define NS_WIDGETS_IS_ADJUSTMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_WIDGETS_TYPE_ADJUSTMENT))
#define NS_WIDGETS_ADJUSTMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustmentClass))

typedef struct _NSWidgetsAdjustment NSWidgetsAdjustment;
typedef struct _NSWidgetsAdjustmentClass NSWidgetsAdjustmentClass;
typedef struct _NSWidgetsAdjustmentPrivate NSWidgetsAdjustmentPrivate;

#define NS_FILE_TYPE_LOADING (ns_file_loading_get_type ())
#define NS_FILE_LOADING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_FILE_TYPE_LOADING, NSFileLoading))
#define NS_FILE_LOADING_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_FILE_TYPE_LOADING, NSFileLoadingClass))
#define NS_FILE_IS_LOADING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_FILE_TYPE_LOADING))
#define NS_FILE_IS_LOADING_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_FILE_TYPE_LOADING))
#define NS_FILE_LOADING_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_FILE_TYPE_LOADING, NSFileLoadingClass))

typedef struct _NSFileLoading NSFileLoading;
typedef struct _NSFileLoadingClass NSFileLoadingClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_variant_iter_free0(var) ((var == NULL) ? NULL : (var = (g_variant_iter_free (var), NULL)))

struct _NSWidgetsAdjustment {
	GObject parent_instance;
	NSWidgetsAdjustmentPrivate * priv;
};

struct _NSWidgetsAdjustmentClass {
	GObjectClass parent_class;
};

struct _NSWidgetsAdjustmentPrivate {
	guint8 index;
};


static gpointer ns_widgets_adjustment_parent_class = NULL;
static NSFileLoading* ns_widgets_adjustment_loading;
static NSFileLoading* ns_widgets_adjustment_loading = NULL;
static GVariant* ns_widgets_adjustment_widgets_to_check;
static GVariant* ns_widgets_adjustment_widgets_to_check = NULL;

GType ns_widgets_adjustment_get_type (void) G_GNUC_CONST;
#define NS_WIDGETS_ADJUSTMENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustmentPrivate))
enum  {
	NS_WIDGETS_ADJUSTMENT_DUMMY_PROPERTY
};
GType ns_file_loading_get_type (void) G_GNUC_CONST;
NSWidgetsAdjustment* ns_widgets_adjustment_new (const gchar* profile, gboolean startup);
NSWidgetsAdjustment* ns_widgets_adjustment_construct (GType object_type, const gchar* profile, gboolean startup);
void ns_widgets_adjustment_prepare_adjustment_to_profile (NSWidgetsAdjustment* self, const gchar* profilename);
void ns_widgets_adjustment_prepare_adjustment_mode1 (NSWidgetsAdjustment* self, const gchar* profile);
NSFileLoading* ns_file_loading_new (const gchar* file);
NSFileLoading* ns_file_loading_construct (GType object_type, const gchar* file);
GVariant* ns_widgets_query_widgets_to_check (guint8 mode);
void ns_file_loading_create_valuelist (NSFileLoading* self, guint8 mode);
GList* ns_file_loading_get_valuelist (NSFileLoading* self);
void ns_widgets_adjustment_adjust_widgets (NSWidgetsAdjustment* self, GtkBuilder* _builder);
void ns_widgets_adjustment_adjust_widgets_of_category (NSWidgetsAdjustment* self, GtkBuilder* _builder, const gchar* category, GVariant* widgettypes);
static void ns_widgets_adjustment_finalize (GObject* obj);


NSWidgetsAdjustment* ns_widgets_adjustment_construct (GType object_type, const gchar* profile, gboolean startup) {
	NSWidgetsAdjustment * self = NULL;
	gboolean _tmp0_;
	g_return_val_if_fail (profile != NULL, NULL);
	self = (NSWidgetsAdjustment*) g_object_new (object_type, NULL);
	_tmp0_ = startup;
	if (_tmp0_ == FALSE) {
		const gchar* _tmp1_;
		_tmp1_ = profile;
		ns_widgets_adjustment_prepare_adjustment_to_profile (self, _tmp1_);
	} else {
		const gchar* _tmp2_;
		_tmp2_ = profile;
		ns_widgets_adjustment_prepare_adjustment_mode1 (self, _tmp2_);
	}
	return self;
}


NSWidgetsAdjustment* ns_widgets_adjustment_new (const gchar* profile, gboolean startup) {
	return ns_widgets_adjustment_construct (NS_WIDGETS_TYPE_ADJUSTMENT, profile, startup);
}


void ns_widgets_adjustment_prepare_adjustment_to_profile (NSWidgetsAdjustment* self, const gchar* profilename) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	NSFileLoading* _tmp5_;
	GVariant* _tmp6_ = NULL;
	NSFileLoading* _tmp7_;
	NSFileLoading* _tmp8_;
	GList* _tmp9_;
	GList* _tmp10_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (profilename != NULL);
	_tmp0_ = profilename;
	_tmp1_ = g_strconcat ("profile_", _tmp0_, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat (_tmp2_, ".json", NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = ns_file_loading_new (_tmp4_);
	_g_object_unref0 (ns_widgets_adjustment_loading);
	ns_widgets_adjustment_loading = _tmp5_;
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	_tmp6_ = ns_widgets_query_widgets_to_check ((guint8) 2);
	_g_variant_unref0 (ns_widgets_adjustment_widgets_to_check);
	ns_widgets_adjustment_widgets_to_check = _tmp6_;
	_tmp7_ = ns_widgets_adjustment_loading;
	ns_file_loading_create_valuelist (_tmp7_, (guint8) 2);
	_tmp8_ = ns_widgets_adjustment_loading;
	_tmp9_ = ns_file_loading_get_valuelist (_tmp8_);
	_tmp10_ = _tmp9_;
	g_list_first (_tmp10_);
}


void ns_widgets_adjustment_prepare_adjustment_mode1 (NSWidgetsAdjustment* self, const gchar* profile) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	NSFileLoading* _tmp3_;
	GVariant* _tmp4_ = NULL;
	NSFileLoading* _tmp5_;
	NSFileLoading* _tmp6_;
	GList* _tmp7_;
	GList* _tmp8_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (profile != NULL);
	_tmp0_ = profile;
	_tmp1_ = g_strconcat (_tmp0_, ".json", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = ns_file_loading_new (_tmp2_);
	_g_object_unref0 (ns_widgets_adjustment_loading);
	ns_widgets_adjustment_loading = _tmp3_;
	_g_free0 (_tmp2_);
	_tmp4_ = ns_widgets_query_widgets_to_check ((guint8) 1);
	_g_variant_unref0 (ns_widgets_adjustment_widgets_to_check);
	ns_widgets_adjustment_widgets_to_check = _tmp4_;
	_tmp5_ = ns_widgets_adjustment_loading;
	ns_file_loading_create_valuelist (_tmp5_, (guint8) 1);
	_tmp6_ = ns_widgets_adjustment_loading;
	_tmp7_ = ns_file_loading_get_valuelist (_tmp6_);
	_tmp8_ = _tmp7_;
	g_list_first (_tmp8_);
}


void ns_widgets_adjustment_adjust_widgets (NSWidgetsAdjustment* self, GtkBuilder* _builder) {
	GVariant* val;
	gchar* key;
	GVariant* _tmp0_;
	GVariantIter* _tmp1_ = NULL;
	GVariantIter* iter;
	g_return_if_fail (self != NULL);
	g_return_if_fail (_builder != NULL);
	val = NULL;
	key = NULL;
	_tmp0_ = ns_widgets_adjustment_widgets_to_check;
	_tmp1_ = g_variant_iter_new (_tmp0_);
	iter = _tmp1_;
	while (TRUE) {
		GVariantIter* _tmp2_;
		gboolean _tmp3_ = FALSE;
		GtkBuilder* _tmp4_;
		const gchar* _tmp5_;
		GVariant* _tmp6_;
		_tmp2_ = iter;
		_tmp3_ = g_variant_iter_next (_tmp2_, "{sv}", &key, &val, NULL);
		if (!_tmp3_) {
			break;
		}
		_tmp4_ = _builder;
		_tmp5_ = key;
		_tmp6_ = val;
		ns_widgets_adjustment_adjust_widgets_of_category (self, _tmp4_, _tmp5_, _tmp6_);
	}
	_g_variant_iter_free0 (iter);
	_g_free0 (key);
	_g_variant_unref0 (val);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gdouble double_parse (const gchar* str) {
	gdouble result = 0.0;
	const gchar* _tmp0_;
	gdouble _tmp1_ = 0.0;
	g_return_val_if_fail (str != NULL, 0.0);
	_tmp0_ = str;
	_tmp1_ = g_ascii_strtod (_tmp0_, NULL);
	result = _tmp1_;
	return result;
}


static gboolean bool_parse (const gchar* str) {
	gboolean result = FALSE;
	const gchar* _tmp0_;
	g_return_val_if_fail (str != NULL, FALSE);
	_tmp0_ = str;
	if (g_strcmp0 (_tmp0_, "true") == 0) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}


void ns_widgets_adjustment_adjust_widgets_of_category (NSWidgetsAdjustment* self, GtkBuilder* _builder, const gchar* category, GVariant* widgettypes) {
	guint8 i;
	g_return_if_fail (self != NULL);
	g_return_if_fail (_builder != NULL);
	g_return_if_fail (category != NULL);
	g_return_if_fail (widgettypes != NULL);
	i = (guint8) 0;
	while (TRUE) {
		guint8 _tmp0_;
		GVariant* _tmp1_;
		gsize _tmp2_ = 0UL;
		GVariant* _tmp3_;
		guint8 _tmp4_;
		GVariant* _tmp5_ = NULL;
		GVariant* _tmp6_;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* type;
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		GQuark _tmp13_ = 0U;
		static GQuark _tmp12_label0 = 0;
		static GQuark _tmp12_label1 = 0;
		static GQuark _tmp12_label2 = 0;
		static GQuark _tmp12_label3 = 0;
		guint8 _tmp84_;
		_tmp0_ = i;
		_tmp1_ = widgettypes;
		_tmp2_ = g_variant_n_children (_tmp1_);
		if (!(((gsize) _tmp0_) < _tmp2_)) {
			break;
		}
		_tmp3_ = widgettypes;
		_tmp4_ = i;
		_tmp5_ = g_variant_get_child_value (_tmp3_, (gsize) _tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = g_variant_get_string (_tmp6_, NULL);
		_tmp8_ = g_strdup (_tmp7_);
		_tmp9_ = _tmp8_;
		_g_variant_unref0 (_tmp6_);
		type = _tmp9_;
		_tmp10_ = type;
		_tmp11_ = _tmp10_;
		_tmp13_ = (NULL == _tmp11_) ? 0 : g_quark_from_string (_tmp11_);
		if (_tmp13_ == ((0 != _tmp12_label0) ? _tmp12_label0 : (_tmp12_label0 = g_quark_from_static_string ("scale")))) {
			switch (0) {
				default:
				{
					GtkAdjustment* adjust = NULL;
					guint8 j;
					j = (guint8) 0;
					while (TRUE) {
						GtkBuilder* _tmp14_;
						const gchar* _tmp15_;
						gchar* _tmp16_;
						gchar* _tmp17_;
						guint8 _tmp18_;
						gchar* _tmp19_ = NULL;
						gchar* _tmp20_;
						gchar* _tmp21_;
						gchar* _tmp22_;
						GObject* _tmp23_ = NULL;
						GtkAdjustment* _tmp24_;
						GtkAdjustment* _tmp25_;
						GtkAdjustment* _tmp26_;
						NSFileLoading* _tmp27_;
						GList* _tmp28_;
						GList* _tmp29_;
						guint8 _tmp30_;
						gconstpointer _tmp31_ = NULL;
						gdouble _tmp32_ = 0.0;
						guint8 _tmp33_;
						guint8 _tmp34_;
						_tmp14_ = _builder;
						_tmp15_ = category;
						_tmp16_ = g_strconcat ("adjust_", _tmp15_, NULL);
						_tmp17_ = _tmp16_;
						_tmp18_ = j;
						_tmp19_ = g_strdup_printf ("%d", _tmp18_);
						_tmp20_ = _tmp19_;
						_tmp21_ = g_strconcat (_tmp17_, _tmp20_, NULL);
						_tmp22_ = _tmp21_;
						_tmp23_ = gtk_builder_get_object (_tmp14_, _tmp22_);
						_tmp24_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp23_, GTK_TYPE_ADJUSTMENT) ? ((GtkAdjustment*) _tmp23_) : NULL);
						_g_object_unref0 (adjust);
						adjust = _tmp24_;
						_g_free0 (_tmp22_);
						_g_free0 (_tmp20_);
						_g_free0 (_tmp17_);
						_tmp25_ = adjust;
						if (_tmp25_ == NULL) {
							break;
						}
						_tmp26_ = adjust;
						_tmp27_ = ns_widgets_adjustment_loading;
						_tmp28_ = ns_file_loading_get_valuelist (_tmp27_);
						_tmp29_ = _tmp28_;
						_tmp30_ = self->priv->index;
						_tmp31_ = g_list_nth_data (_tmp29_, (guint) _tmp30_);
						_tmp32_ = double_parse ((const gchar*) _tmp31_);
						gtk_adjustment_set_value (_tmp26_, _tmp32_);
						_tmp33_ = j;
						j = _tmp33_ + 1;
						_tmp34_ = self->priv->index;
						self->priv->index = _tmp34_ + 1;
					}
					_g_object_unref0 (adjust);
					break;
				}
			}
		} else if ((_tmp13_ == ((0 != _tmp12_label1) ? _tmp12_label1 : (_tmp12_label1 = g_quark_from_static_string ("e")))) || (_tmp13_ == ((0 != _tmp12_label2) ? _tmp12_label2 : (_tmp12_label2 = g_quark_from_static_string ("ce"))))) {
			switch (0) {
				default:
				{
					GtkEntry* entry = NULL;
					guint8 j;
					j = (guint8) 0;
					while (TRUE) {
						GtkBuilder* _tmp35_;
						const gchar* _tmp36_;
						gchar* _tmp37_;
						gchar* _tmp38_;
						const gchar* _tmp39_;
						gchar* _tmp40_;
						gchar* _tmp41_;
						guint8 _tmp42_;
						gchar* _tmp43_ = NULL;
						gchar* _tmp44_;
						gchar* _tmp45_;
						gchar* _tmp46_;
						GObject* _tmp47_ = NULL;
						GtkEntry* _tmp48_;
						GtkEntry* _tmp49_;
						GtkEntry* _tmp50_;
						NSFileLoading* _tmp51_;
						GList* _tmp52_;
						GList* _tmp53_;
						guint8 _tmp54_;
						gconstpointer _tmp55_ = NULL;
						guint8 _tmp56_;
						guint8 _tmp57_;
						_tmp35_ = _builder;
						_tmp36_ = type;
						_tmp37_ = g_strconcat (_tmp36_, "_", NULL);
						_tmp38_ = _tmp37_;
						_tmp39_ = category;
						_tmp40_ = g_strconcat (_tmp38_, _tmp39_, NULL);
						_tmp41_ = _tmp40_;
						_tmp42_ = j;
						_tmp43_ = g_strdup_printf ("%d", _tmp42_);
						_tmp44_ = _tmp43_;
						_tmp45_ = g_strconcat (_tmp41_, _tmp44_, NULL);
						_tmp46_ = _tmp45_;
						_tmp47_ = gtk_builder_get_object (_tmp35_, _tmp46_);
						_tmp48_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp47_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp47_) : NULL);
						_g_object_unref0 (entry);
						entry = _tmp48_;
						_g_free0 (_tmp46_);
						_g_free0 (_tmp44_);
						_g_free0 (_tmp41_);
						_g_free0 (_tmp38_);
						_tmp49_ = entry;
						if (_tmp49_ == NULL) {
							break;
						}
						_tmp50_ = entry;
						_tmp51_ = ns_widgets_adjustment_loading;
						_tmp52_ = ns_file_loading_get_valuelist (_tmp51_);
						_tmp53_ = _tmp52_;
						_tmp54_ = self->priv->index;
						_tmp55_ = g_list_nth_data (_tmp53_, (guint) _tmp54_);
						gtk_entry_set_text (_tmp50_, (const gchar*) _tmp55_);
						_tmp56_ = j;
						j = _tmp56_ + 1;
						_tmp57_ = self->priv->index;
						self->priv->index = _tmp57_ + 1;
					}
					_g_object_unref0 (entry);
					break;
				}
			}
		} else if (_tmp13_ == ((0 != _tmp12_label3) ? _tmp12_label3 : (_tmp12_label3 = g_quark_from_static_string ("cbtn")))) {
			switch (0) {
				default:
				{
					GtkToggleButton* cbtn = NULL;
					guint8 j;
					j = (guint8) 0;
					while (TRUE) {
						GtkBuilder* _tmp58_;
						const gchar* _tmp59_;
						gchar* _tmp60_;
						gchar* _tmp61_;
						const gchar* _tmp62_;
						gchar* _tmp63_;
						gchar* _tmp64_;
						guint8 _tmp65_;
						gchar* _tmp66_ = NULL;
						gchar* _tmp67_;
						gchar* _tmp68_;
						gchar* _tmp69_;
						GObject* _tmp70_ = NULL;
						GtkToggleButton* _tmp71_;
						GtkToggleButton* _tmp72_;
						GtkToggleButton* _tmp73_;
						NSFileLoading* _tmp74_;
						GList* _tmp75_;
						GList* _tmp76_;
						guint8 _tmp77_;
						gconstpointer _tmp78_ = NULL;
						gboolean _tmp79_ = FALSE;
						guint8 _tmp80_;
						guint8 _tmp81_;
						_tmp58_ = _builder;
						_tmp59_ = type;
						_tmp60_ = g_strconcat (_tmp59_, "_", NULL);
						_tmp61_ = _tmp60_;
						_tmp62_ = category;
						_tmp63_ = g_strconcat (_tmp61_, _tmp62_, NULL);
						_tmp64_ = _tmp63_;
						_tmp65_ = j;
						_tmp66_ = g_strdup_printf ("%d", _tmp65_);
						_tmp67_ = _tmp66_;
						_tmp68_ = g_strconcat (_tmp64_, _tmp67_, NULL);
						_tmp69_ = _tmp68_;
						_tmp70_ = gtk_builder_get_object (_tmp58_, _tmp69_);
						_tmp71_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp70_, GTK_TYPE_TOGGLE_BUTTON) ? ((GtkToggleButton*) _tmp70_) : NULL);
						_g_object_unref0 (cbtn);
						cbtn = _tmp71_;
						_g_free0 (_tmp69_);
						_g_free0 (_tmp67_);
						_g_free0 (_tmp64_);
						_g_free0 (_tmp61_);
						_tmp72_ = cbtn;
						if (_tmp72_ == NULL) {
							break;
						}
						_tmp73_ = cbtn;
						_tmp74_ = ns_widgets_adjustment_loading;
						_tmp75_ = ns_file_loading_get_valuelist (_tmp74_);
						_tmp76_ = _tmp75_;
						_tmp77_ = self->priv->index;
						_tmp78_ = g_list_nth_data (_tmp76_, (guint) _tmp77_);
						_tmp79_ = bool_parse ((const gchar*) _tmp78_);
						gtk_toggle_button_set_active (_tmp73_, _tmp79_);
						_tmp80_ = j;
						j = _tmp80_ + 1;
						_tmp81_ = self->priv->index;
						self->priv->index = _tmp81_ + 1;
					}
					_g_object_unref0 (cbtn);
					break;
				}
			}
		} else {
			switch (0) {
				default:
				{
					FILE* _tmp82_;
					const gchar* _tmp83_;
					_tmp82_ = stdout;
					_tmp83_ = type;
					fprintf (_tmp82_, "widgettype %s not adjusted!\n", _tmp83_);
					break;
				}
			}
		}
		_tmp84_ = i;
		i = _tmp84_ + 1;
		_g_free0 (type);
	}
}


static void ns_widgets_adjustment_class_init (NSWidgetsAdjustmentClass * klass) {
	ns_widgets_adjustment_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (NSWidgetsAdjustmentPrivate));
	G_OBJECT_CLASS (klass)->finalize = ns_widgets_adjustment_finalize;
}


static void ns_widgets_adjustment_instance_init (NSWidgetsAdjustment * self) {
	self->priv = NS_WIDGETS_ADJUSTMENT_GET_PRIVATE (self);
	self->priv->index = (guint8) 0;
}


static void ns_widgets_adjustment_finalize (GObject* obj) {
	NSWidgetsAdjustment * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NS_WIDGETS_TYPE_ADJUSTMENT, NSWidgetsAdjustment);
	G_OBJECT_CLASS (ns_widgets_adjustment_parent_class)->finalize (obj);
}


GType ns_widgets_adjustment_get_type (void) {
	static volatile gsize ns_widgets_adjustment_type_id__volatile = 0;
	if (g_once_init_enter (&ns_widgets_adjustment_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (NSWidgetsAdjustmentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ns_widgets_adjustment_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NSWidgetsAdjustment), 0, (GInstanceInitFunc) ns_widgets_adjustment_instance_init, NULL };
		GType ns_widgets_adjustment_type_id;
		ns_widgets_adjustment_type_id = g_type_register_static (G_TYPE_OBJECT, "NSWidgetsAdjustment", &g_define_type_info, 0);
		g_once_init_leave (&ns_widgets_adjustment_type_id__volatile, ns_widgets_adjustment_type_id);
	}
	return ns_widgets_adjustment_type_id__volatile;
}



