/* widgets-feedback.c generated by valac 0.16.1, the Vala compiler
 * generated from widgets-feedback.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <float.h>
#include <math.h>
#include <string.h>
#include <json-glib/json-glib.h>
#include <stdio.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define NS_WIDGETS_TYPE_FEEDBACK (ns_widgets_feedback_get_type ())
#define NS_WIDGETS_FEEDBACK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_WIDGETS_TYPE_FEEDBACK, NSWidgetsFeedback))
#define NS_WIDGETS_FEEDBACK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_WIDGETS_TYPE_FEEDBACK, NSWidgetsFeedbackClass))
#define NS_WIDGETS_IS_FEEDBACK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_WIDGETS_TYPE_FEEDBACK))
#define NS_WIDGETS_IS_FEEDBACK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_WIDGETS_TYPE_FEEDBACK))
#define NS_WIDGETS_FEEDBACK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_WIDGETS_TYPE_FEEDBACK, NSWidgetsFeedbackClass))

typedef struct _NSWidgetsFeedback NSWidgetsFeedback;
typedef struct _NSWidgetsFeedbackClass NSWidgetsFeedbackClass;
typedef struct _NSWidgetsFeedbackPrivate NSWidgetsFeedbackPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define NS_WIDGETS_FEEDBACK_TYPE__CROP (ns_widgets_feedback__crop_get_type ())
typedef struct _NSWidgetsFeedback_Crop NSWidgetsFeedback_Crop;
#define _g_free0(var) (var = (g_free (var), NULL))
#define __vala_JsonObject_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonObject_free (var), NULL)))

#define NS_COMMAND_TYPE_EXECUTION (ns_command_execution_get_type ())
#define NS_COMMAND_EXECUTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NS_COMMAND_TYPE_EXECUTION, NSCommandExecution))
#define NS_COMMAND_EXECUTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NS_COMMAND_TYPE_EXECUTION, NSCommandExecutionClass))
#define NS_COMMAND_IS_EXECUTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NS_COMMAND_TYPE_EXECUTION))
#define NS_COMMAND_IS_EXECUTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NS_COMMAND_TYPE_EXECUTION))
#define NS_COMMAND_EXECUTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NS_COMMAND_TYPE_EXECUTION, NSCommandExecutionClass))

typedef struct _NSCommandExecution NSCommandExecution;
typedef struct _NSCommandExecutionClass NSCommandExecutionClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
typedef struct _Block2Data Block2Data;

struct _Main {
	GtkApplication parent_instance;
	MainPrivate * priv;
	GtkBuilder* builder;
	GtkLabel* advice_label;
	GtkInfoBar* infobar;
	GtkInfoBar* error_infbar;
	GtkLabel* lbl_video;
	GtkLabel* lbl_audio;
	GtkLabel* lbl_other;
};

struct _MainClass {
	GtkApplicationClass parent_class;
};

struct _NSWidgetsFeedback {
	Main parent_instance;
	NSWidgetsFeedbackPrivate * priv;
	GtkInfoBar* advice_infobar;
};

struct _NSWidgetsFeedbackClass {
	MainClass parent_class;
};

struct _NSWidgetsFeedback_Crop {
	gint top;
	gint right;
	gint bottom;
	gint left;
};

struct _Block2Data {
	int _ref_count_;
	NSWidgetsFeedback * self;
	GtkInfoBar* advice_infobar;
	GtkButton* sender;
};


static gpointer ns_widgets_feedback_parent_class = NULL;
static gboolean ns_widgets_feedback_update_resolution_on_cropping;
static gboolean ns_widgets_feedback_update_resolution_on_cropping = FALSE;
static gboolean ns_widgets_feedback_question_was_asked;
static gboolean ns_widgets_feedback_question_was_asked = FALSE;
static NSWidgetsFeedback_Crop ns_widgets_feedback_crop;
static NSWidgetsFeedback_Crop ns_widgets_feedback_crop = {0};
static gint ns_widgets_feedback_original_width;
static gint ns_widgets_feedback_original_width = 0;
static gint ns_widgets_feedback_original_height;
static gint ns_widgets_feedback_original_height = 0;
static gint ns_widgets_feedback__width;
static gint ns_widgets_feedback__width = 0;
static gint ns_widgets_feedback__height;
static gint ns_widgets_feedback__height = 0;
static gint ns_widgets_feedback_min;
static gint ns_widgets_feedback_min = 0;
static gint ns_widgets_feedback_sec;
static gint ns_widgets_feedback_sec = 0;

GType main_get_type (void) G_GNUC_CONST;
GType ns_widgets_feedback_get_type (void) G_GNUC_CONST;
enum  {
	NS_WIDGETS_FEEDBACK_DUMMY_PROPERTY
};
static GType ns_widgets_feedback__crop_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static NSWidgetsFeedback_Crop* ns_widgets_feedback__crop_dup (const NSWidgetsFeedback_Crop* self);
static void ns_widgets_feedback__crop_free (NSWidgetsFeedback_Crop* self);
NSWidgetsFeedback* ns_widgets_feedback_new (void);
NSWidgetsFeedback* ns_widgets_feedback_construct (GType object_type);
Main* main_new (void);
Main* main_construct (GType object_type);
void on_adjust_crop_value_changed (GtkAdjustment* adjust, GtkInfoBar* infbar_question, NSWidgetsFeedback* self);
void on_btn_yes_clicked (GtkButton* button, GtkGrid* grid_crop, NSWidgetsFeedback* self);
void on_btn_yes_released (GtkButton* button, GtkGrid* grid_res, NSWidgetsFeedback* self);
static void ns_widgets_feedback_update_resolution_without_builder (NSWidgetsFeedback* self, GtkGrid* grid_res);
void on_btn_no_released (GtkButton* button, GtkInfoBar* infbar_res, NSWidgetsFeedback* self);
void on_adjust_croptop_value_changed (GtkAdjustment* adjust, NSWidgetsFeedback* self);
static void ns_widgets_feedback_update_resolution (NSWidgetsFeedback* self);
void on_adjust_cropright_value_changed (GtkAdjustment* adjust, NSWidgetsFeedback* self);
void on_adjust_cropbottom_value_changed (GtkAdjustment* adjust, NSWidgetsFeedback* self);
void on_adjust_cropleft_value_changed (GtkAdjustment* adjust, NSWidgetsFeedback* self);
void on_btn_show_info_clicked (GtkButton* sender, NSWidgetsFeedback* self);
static void ns_widgets_feedback_built_infbar_info_layout (NSWidgetsFeedback* self);
static gchar* ns_widgets_feedback_get_file (NSWidgetsFeedback* self);
static JsonObject* ns_widgets_feedback_get_parser_object (NSWidgetsFeedback* self, const gchar* source);
static void _vala_JsonObject_free (JsonObject* self);
void main_built_infbar_layout (Main* self, GtkMessageType type, const gchar* message, const gchar* button);
static gchar* ns_widgets_feedback_get_specific_info_of_source (NSWidgetsFeedback* self, JsonObject* root_o, const gchar* category, const gchar* type);
static void ns_widgets_feedback_update_resolution_values (NSWidgetsFeedback* self, GtkSpinButton* height_sbtn, GtkScale* scale, GtkEntry* width_entry);
static void __lambda5_ (NSWidgetsFeedback* self);
static void ___lambda5__gtk_info_bar_response (GtkInfoBar* _sender, gint response_id, gpointer self);
NSCommandExecution* ns_command_execution_new (void);
NSCommandExecution* ns_command_execution_construct (GType object_type);
GType ns_command_execution_get_type (void) G_GNUC_CONST;
gboolean ns_command_execution_sync_command (NSCommandExecution* self, const gchar* command);
const gchar* ns_command_execution_get_info (NSCommandExecution* self);
static JsonObject* _vala_JsonObject_copy (JsonObject* self);
static gchar* ns_widgets_feedback_cut_strings_of_doubles (NSWidgetsFeedback* self, const gchar* info, const gchar* additional);
void on_btn_help_clicked (GtkButton* sender, NSWidgetsFeedback* self);
static void __lambda6_ (NSWidgetsFeedback* self, GtkWidget* a);
static void ___lambda6__gfunc (gconstpointer data, gpointer self);
const gchar* main_get_active_tab (Main* self);
void on_tbtn_show_filters_toggled (GtkToggleButton* sender, NSWidgetsFeedback* self);
void on_btn_advice_clicked (GtkButton* sender, NSWidgetsFeedback* self);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda7_ (Block2Data* _data2_);
static void ___lambda7__gtk_info_bar_response (GtkInfoBar* _sender, gint response_id, gpointer self);
gint ns_widgets_feedback_get_width (void);
gint ns_widgets_feedback_get_height (void);
static void ns_widgets_feedback_finalize (GObject* obj);
static void _vala_ns_widgets_feedback_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


NSWidgetsFeedback* ns_widgets_feedback_construct (GType object_type) {
	NSWidgetsFeedback * self = NULL;
	self = (NSWidgetsFeedback*) main_construct (object_type);
	return self;
}


NSWidgetsFeedback* ns_widgets_feedback_new (void) {
	return ns_widgets_feedback_construct (NS_WIDGETS_TYPE_FEEDBACK);
}


void on_adjust_crop_value_changed (GtkAdjustment* adjust, GtkInfoBar* infbar_question, NSWidgetsFeedback* self) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (adjust != NULL);
	g_return_if_fail (infbar_question != NULL);
	_tmp0_ = ns_widgets_feedback_question_was_asked;
	if (_tmp0_ == FALSE) {
		GtkInfoBar* _tmp1_;
		_tmp1_ = infbar_question;
		gtk_widget_show ((GtkWidget*) _tmp1_);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void on_btn_yes_clicked (GtkButton* button, GtkGrid* grid_crop, NSWidgetsFeedback* self) {
	GtkGrid* _tmp0_;
	GtkWidget* _tmp1_ = NULL;
	GtkSpinButton* _tmp2_;
	GtkSpinButton* sbtn;
	GtkSpinButton* _tmp3_;
	GtkAdjustment* _tmp4_ = NULL;
	gdouble _tmp5_ = 0.0;
	GtkGrid* _tmp6_;
	GtkWidget* _tmp7_ = NULL;
	GtkSpinButton* _tmp8_;
	GtkSpinButton* _tmp9_;
	GtkAdjustment* _tmp10_ = NULL;
	gdouble _tmp11_ = 0.0;
	GtkGrid* _tmp12_;
	GtkWidget* _tmp13_ = NULL;
	GtkSpinButton* _tmp14_;
	GtkSpinButton* _tmp15_;
	GtkAdjustment* _tmp16_ = NULL;
	gdouble _tmp17_ = 0.0;
	GtkGrid* _tmp18_;
	GtkWidget* _tmp19_ = NULL;
	GtkSpinButton* _tmp20_;
	GtkAdjustment* _tmp21_ = NULL;
	gdouble _tmp22_ = 0.0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (button != NULL);
	g_return_if_fail (grid_crop != NULL);
	ns_widgets_feedback_update_resolution_on_cropping = TRUE;
	ns_widgets_feedback_question_was_asked = TRUE;
	_tmp0_ = grid_crop;
	_tmp1_ = gtk_grid_get_child_at (_tmp0_, 3, 0);
	_tmp2_ = _g_object_ref0 (GTK_IS_SPIN_BUTTON (_tmp1_) ? ((GtkSpinButton*) _tmp1_) : NULL);
	sbtn = _tmp2_;
	_tmp3_ = sbtn;
	_tmp4_ = gtk_spin_button_get_adjustment (_tmp3_);
	_tmp5_ = gtk_adjustment_get_value (_tmp4_);
	ns_widgets_feedback_crop.top = (gint) _tmp5_;
	_tmp6_ = grid_crop;
	_tmp7_ = gtk_grid_get_child_at (_tmp6_, 5, 1);
	_tmp8_ = _g_object_ref0 (GTK_IS_SPIN_BUTTON (_tmp7_) ? ((GtkSpinButton*) _tmp7_) : NULL);
	_g_object_unref0 (sbtn);
	sbtn = _tmp8_;
	_tmp9_ = sbtn;
	_tmp10_ = gtk_spin_button_get_adjustment (_tmp9_);
	_tmp11_ = gtk_adjustment_get_value (_tmp10_);
	ns_widgets_feedback_crop.right = (gint) _tmp11_;
	_tmp12_ = grid_crop;
	_tmp13_ = gtk_grid_get_child_at (_tmp12_, 3, 2);
	_tmp14_ = _g_object_ref0 (GTK_IS_SPIN_BUTTON (_tmp13_) ? ((GtkSpinButton*) _tmp13_) : NULL);
	_g_object_unref0 (sbtn);
	sbtn = _tmp14_;
	_tmp15_ = sbtn;
	_tmp16_ = gtk_spin_button_get_adjustment (_tmp15_);
	_tmp17_ = gtk_adjustment_get_value (_tmp16_);
	ns_widgets_feedback_crop.bottom = (gint) _tmp17_;
	_tmp18_ = grid_crop;
	_tmp19_ = gtk_grid_get_child_at (_tmp18_, 1, 1);
	_tmp20_ = sbtn;
	_tmp21_ = gtk_spin_button_get_adjustment (_tmp20_);
	_tmp22_ = gtk_adjustment_get_value (_tmp21_);
	ns_widgets_feedback_crop.left = (gint) _tmp22_;
	_g_object_unref0 (sbtn);
}


void on_btn_yes_released (GtkButton* button, GtkGrid* grid_res, NSWidgetsFeedback* self) {
	GtkGrid* _tmp0_;
	GtkButton* _tmp1_;
	GtkWidget* _tmp2_ = NULL;
	GtkBox* _tmp3_;
	GtkBox* box;
	GtkWidget* _tmp4_ = NULL;
	GtkWidget* _tmp5_;
	GtkWidget* infbar_res_aa;
	GtkWidget* _tmp6_ = NULL;
	GtkWidget* _tmp7_;
	GtkWidget* infbar_res;
	g_return_if_fail (self != NULL);
	g_return_if_fail (button != NULL);
	g_return_if_fail (grid_res != NULL);
	_tmp0_ = grid_res;
	ns_widgets_feedback_update_resolution_without_builder (self, _tmp0_);
	_tmp1_ = button;
	_tmp2_ = gtk_widget_get_parent ((GtkWidget*) _tmp1_);
	_tmp3_ = _g_object_ref0 (GTK_IS_BOX (_tmp2_) ? ((GtkBox*) _tmp2_) : NULL);
	box = _tmp3_;
	_tmp4_ = gtk_widget_get_parent ((GtkWidget*) box);
	_tmp5_ = _g_object_ref0 (_tmp4_);
	infbar_res_aa = _tmp5_;
	_tmp6_ = gtk_widget_get_parent (infbar_res_aa);
	_tmp7_ = _g_object_ref0 (_tmp6_);
	infbar_res = _tmp7_;
	gtk_widget_destroy (infbar_res);
	_g_object_unref0 (infbar_res);
	_g_object_unref0 (infbar_res_aa);
	_g_object_unref0 (box);
}


void on_btn_no_released (GtkButton* button, GtkInfoBar* infbar_res, NSWidgetsFeedback* self) {
	GtkInfoBar* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (button != NULL);
	g_return_if_fail (infbar_res != NULL);
	ns_widgets_feedback_update_resolution_on_cropping = FALSE;
	ns_widgets_feedback_question_was_asked = TRUE;
	_tmp0_ = infbar_res;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
}


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	gchar* _tmp4_;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


void on_adjust_croptop_value_changed (GtkAdjustment* adjust, NSWidgetsFeedback* self) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (adjust != NULL);
	_tmp0_ = ns_widgets_feedback_update_resolution_on_cropping;
	if (_tmp0_ == TRUE) {
		GtkAdjustment* _tmp1_;
		gdouble _tmp2_ = 0.0;
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_;
		gint _tmp5_ = 0;
		gint _tmp6_;
		gint temp;
		gint _tmp7_;
		_tmp1_ = adjust;
		_tmp2_ = gtk_adjustment_get_value (_tmp1_);
		_tmp3_ = double_to_string (_tmp2_);
		_tmp4_ = _tmp3_;
		_tmp5_ = atoi (_tmp4_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		temp = _tmp6_;
		_tmp7_ = temp;
		ns_widgets_feedback_crop.top = _tmp7_;
		ns_widgets_feedback_update_resolution (self);
	}
}


void on_adjust_cropright_value_changed (GtkAdjustment* adjust, NSWidgetsFeedback* self) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (adjust != NULL);
	_tmp0_ = ns_widgets_feedback_update_resolution_on_cropping;
	if (_tmp0_ == TRUE) {
		GtkAdjustment* _tmp1_;
		gdouble _tmp2_ = 0.0;
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_;
		gint _tmp5_ = 0;
		gint _tmp6_;
		gint temp;
		gint _tmp7_;
		_tmp1_ = adjust;
		_tmp2_ = gtk_adjustment_get_value (_tmp1_);
		_tmp3_ = double_to_string (_tmp2_);
		_tmp4_ = _tmp3_;
		_tmp5_ = atoi (_tmp4_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		temp = _tmp6_;
		_tmp7_ = temp;
		ns_widgets_feedback_crop.right = _tmp7_;
		ns_widgets_feedback_update_resolution (self);
	}
}


void on_adjust_cropbottom_value_changed (GtkAdjustment* adjust, NSWidgetsFeedback* self) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (adjust != NULL);
	_tmp0_ = ns_widgets_feedback_update_resolution_on_cropping;
	if (_tmp0_ == TRUE) {
		GtkAdjustment* _tmp1_;
		gdouble _tmp2_ = 0.0;
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_;
		gint _tmp5_ = 0;
		gint _tmp6_;
		gint temp;
		gint _tmp7_;
		_tmp1_ = adjust;
		_tmp2_ = gtk_adjustment_get_value (_tmp1_);
		_tmp3_ = double_to_string (_tmp2_);
		_tmp4_ = _tmp3_;
		_tmp5_ = atoi (_tmp4_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		temp = _tmp6_;
		_tmp7_ = temp;
		ns_widgets_feedback_crop.bottom = _tmp7_;
		ns_widgets_feedback_update_resolution (self);
	}
}


void on_adjust_cropleft_value_changed (GtkAdjustment* adjust, NSWidgetsFeedback* self) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (adjust != NULL);
	_tmp0_ = ns_widgets_feedback_update_resolution_on_cropping;
	if (_tmp0_ == TRUE) {
		GtkAdjustment* _tmp1_;
		gdouble _tmp2_ = 0.0;
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_;
		gint _tmp5_ = 0;
		gint _tmp6_;
		gint temp;
		gint _tmp7_;
		_tmp1_ = adjust;
		_tmp2_ = gtk_adjustment_get_value (_tmp1_);
		_tmp3_ = double_to_string (_tmp2_);
		_tmp4_ = _tmp3_;
		_tmp5_ = atoi (_tmp4_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		temp = _tmp6_;
		_tmp7_ = temp;
		ns_widgets_feedback_crop.left = _tmp7_;
		ns_widgets_feedback_update_resolution (self);
	}
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	gint _tmp0_;
	gint _tmp1_;
	glong string_length;
	glong _tmp2_;
	glong _tmp5_;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_;
	gboolean _tmp12_;
	gboolean _tmp13_ = FALSE;
	glong _tmp14_;
	gboolean _tmp17_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_;
		glong _tmp4_;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_;
		glong _tmp7_;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	_tmp12_ = _tmp8_;
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp14_ = end;
	if (_tmp14_ >= ((glong) 0)) {
		glong _tmp15_;
		glong _tmp16_;
		_tmp15_ = end;
		_tmp16_ = string_length;
		_tmp13_ = _tmp15_ <= _tmp16_;
	} else {
		_tmp13_ = FALSE;
	}
	_tmp17_ = _tmp13_;
	g_return_val_if_fail (_tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	g_return_val_if_fail (_tmp18_ <= _tmp19_, NULL);
	_tmp20_ = start;
	_tmp21_ = end;
	_tmp22_ = start;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) (_tmp21_ - _tmp22_));
	result = _tmp23_;
	return result;
}


static void _vala_JsonObject_free (JsonObject* self) {
	g_boxed_free (json_object_get_type (), self);
}


void on_btn_show_info_clicked (GtkButton* sender, NSWidgetsFeedback* self) {
	GtkInfoBar* _tmp0_;
	JsonObject* _tmp1_;
	JsonObject* object;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar** _tmp6_ = NULL;
	gchar** required_videoinfo;
	gint required_videoinfo_length1;
	gint _required_videoinfo_size_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar** _tmp9_ = NULL;
	gchar** required_audioinfo;
	gint required_audioinfo_length1;
	gint _required_audioinfo_size_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar** _tmp13_ = NULL;
	gchar** required_otherinfo;
	gint required_otherinfo_length1;
	gint _required_otherinfo_size_;
	gchar* selection = NULL;
	gchar* info = NULL;
	gchar* previous = NULL;
	gchar* examplefile = NULL;
	GtkBuilder* _tmp14_;
	GObject* _tmp15_ = NULL;
	GtkEntry* _tmp16_;
	GtkEntry* targetfield;
	GtkBuilder* _tmp17_;
	GObject* _tmp18_ = NULL;
	GtkBox* _tmp19_;
	GtkBox* box;
	GtkBox* _tmp20_;
	GtkBox* _tmp21_;
	GtkInfoBar* _tmp22_;
	gchar* _tmp23_ = NULL;
	const gchar* _tmp24_;
	const gchar* _tmp25_;
	gint _tmp26_;
	gint _tmp27_;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_;
	gchar* _tmp30_;
	GtkEntry* _tmp31_;
	const gchar* _tmp32_;
	const gchar* _tmp33_;
	JsonObject* _tmp34_ = NULL;
	JsonObject* _tmp35_;
	gchar** _tmp37_;
	gint _tmp37__length1;
	GtkLabel* _tmp74_;
	gchar** _tmp75_;
	gint _tmp75__length1;
	GtkLabel* _tmp95_;
	gchar** _tmp96_;
	gint _tmp96__length1;
	gint _tmp116_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	_tmp0_ = ((Main*) self)->infobar;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
	ns_widgets_feedback_built_infbar_info_layout (self);
	_tmp1_ = json_object_new ();
	object = _tmp1_;
	_tmp2_ = g_strdup ("width");
	_tmp3_ = g_strdup ("height");
	_tmp4_ = g_strdup ("codec");
	_tmp5_ = g_strdup ("framerate");
	_tmp6_ = g_new0 (gchar*, 4 + 1);
	_tmp6_[0] = _tmp2_;
	_tmp6_[1] = _tmp3_;
	_tmp6_[2] = _tmp4_;
	_tmp6_[3] = _tmp5_;
	required_videoinfo = _tmp6_;
	required_videoinfo_length1 = 4;
	_required_videoinfo_size_ = required_videoinfo_length1;
	_tmp7_ = g_strdup ("codec");
	_tmp8_ = g_strdup ("samplerate");
	_tmp9_ = g_new0 (gchar*, 2 + 1);
	_tmp9_[0] = _tmp7_;
	_tmp9_[1] = _tmp8_;
	required_audioinfo = _tmp9_;
	required_audioinfo_length1 = 2;
	_required_audioinfo_size_ = required_audioinfo_length1;
	_tmp10_ = g_strdup ("duration");
	_tmp11_ = g_strdup ("bitrate");
	_tmp12_ = g_strdup ("size");
	_tmp13_ = g_new0 (gchar*, 3 + 1);
	_tmp13_[0] = _tmp10_;
	_tmp13_[1] = _tmp11_;
	_tmp13_[2] = _tmp12_;
	required_otherinfo = _tmp13_;
	required_otherinfo_length1 = 3;
	_required_otherinfo_size_ = required_otherinfo_length1;
	_tmp14_ = ((Main*) self)->builder;
	_tmp15_ = gtk_builder_get_object (_tmp14_, "e_basics0");
	_tmp16_ = _g_object_ref0 (GTK_IS_ENTRY (_tmp15_) ? ((GtkEntry*) _tmp15_) : NULL);
	targetfield = _tmp16_;
	_tmp17_ = ((Main*) self)->builder;
	_tmp18_ = gtk_builder_get_object (_tmp17_, "box_on_top_of_sbar");
	_tmp19_ = _g_object_ref0 (GTK_IS_BOX (_tmp18_) ? ((GtkBox*) _tmp18_) : NULL);
	box = _tmp19_;
	_tmp20_ = box;
	gtk_widget_show ((GtkWidget*) _tmp20_);
	_tmp21_ = box;
	_tmp22_ = ((Main*) self)->infobar;
	gtk_box_pack_end (_tmp21_, (GtkWidget*) _tmp22_, TRUE, TRUE, (guint) 5);
	_tmp23_ = ns_widgets_feedback_get_file (self);
	_g_free0 (selection);
	selection = _tmp23_;
	_tmp24_ = selection;
	_tmp25_ = selection;
	_tmp26_ = strlen (_tmp25_);
	_tmp27_ = _tmp26_;
	_tmp28_ = string_slice (_tmp24_, (glong) 0, (glong) (_tmp27_ - 5));
	_tmp29_ = _tmp28_;
	_tmp30_ = g_strconcat (_tmp29_, ".ogv", NULL);
	_g_free0 (examplefile);
	examplefile = _tmp30_;
	_g_free0 (_tmp29_);
	_tmp31_ = targetfield;
	_tmp32_ = examplefile;
	gtk_entry_set_text (_tmp31_, _tmp32_);
	_tmp33_ = selection;
	_tmp34_ = ns_widgets_feedback_get_parser_object (self, _tmp33_);
	__vala_JsonObject_free0 (object);
	object = _tmp34_;
	_tmp35_ = object;
	if (_tmp35_ == NULL) {
		GtkInfoBar* _tmp36_;
		_tmp36_ = ((Main*) self)->infobar;
		gtk_widget_destroy ((GtkWidget*) _tmp36_);
		main_built_infbar_layout ((Main*) self, GTK_MESSAGE_ERROR, "Looks like the ffmpeg2theora --info " "command is not working correctly! \n" "Please make sure ffmpeg2theora is installed.", "");
		_g_object_unref0 (box);
		_g_object_unref0 (targetfield);
		_g_free0 (examplefile);
		_g_free0 (previous);
		_g_free0 (info);
		_g_free0 (selection);
		required_otherinfo = (_vala_array_free (required_otherinfo, required_otherinfo_length1, (GDestroyNotify) g_free), NULL);
		required_audioinfo = (_vala_array_free (required_audioinfo, required_audioinfo_length1, (GDestroyNotify) g_free), NULL);
		required_videoinfo = (_vala_array_free (required_videoinfo, required_videoinfo_length1, (GDestroyNotify) g_free), NULL);
		__vala_JsonObject_free0 (object);
		return;
	}
	_tmp37_ = required_videoinfo;
	_tmp37__length1 = required_videoinfo_length1;
	{
		gchar** vtype_collection = NULL;
		gint vtype_collection_length1 = 0;
		gint _vtype_collection_size_ = 0;
		gint vtype_it = 0;
		vtype_collection = _tmp37_;
		vtype_collection_length1 = _tmp37__length1;
		for (vtype_it = 0; vtype_it < _tmp37__length1; vtype_it = vtype_it + 1) {
			gchar* _tmp38_;
			gchar* vtype = NULL;
			_tmp38_ = g_strdup (vtype_collection[vtype_it]);
			vtype = _tmp38_;
			{
				JsonObject* _tmp39_;
				const gchar* _tmp40_;
				gchar* _tmp41_ = NULL;
				GtkLabel* _tmp42_;
				const gchar* _tmp43_ = NULL;
				gchar* _tmp44_;
				const gchar* _tmp45_;
				_tmp39_ = object;
				_tmp40_ = vtype;
				_tmp41_ = ns_widgets_feedback_get_specific_info_of_source (self, _tmp39_, "video", _tmp40_);
				_g_free0 (info);
				info = _tmp41_;
				_tmp42_ = ((Main*) self)->lbl_video;
				_tmp43_ = gtk_label_get_text (_tmp42_);
				_tmp44_ = g_strdup (_tmp43_);
				_g_free0 (previous);
				previous = _tmp44_;
				_tmp45_ = vtype;
				if (g_strcmp0 (_tmp45_, "width") == 0) {
					const gchar* _tmp46_;
					gint _tmp47_ = 0;
					GtkLabel* _tmp48_;
					const gchar* _tmp49_;
					gchar* _tmp50_;
					gchar* _tmp51_;
					_tmp46_ = info;
					_tmp47_ = atoi (_tmp46_);
					ns_widgets_feedback_original_width = _tmp47_;
					_tmp48_ = ((Main*) self)->lbl_video;
					_tmp49_ = info;
					_tmp50_ = g_strconcat ("Video\n Resolution: ", _tmp49_, NULL);
					_tmp51_ = _tmp50_;
					gtk_label_set_text (_tmp48_, _tmp51_);
					_g_free0 (_tmp51_);
				} else {
					const gchar* _tmp52_;
					_tmp52_ = vtype;
					if (g_strcmp0 (_tmp52_, "height") != 0) {
						GtkLabel* _tmp53_;
						const gchar* _tmp54_;
						gchar* _tmp55_;
						gchar* _tmp56_;
						const gchar* _tmp57_;
						gchar* _tmp58_;
						gchar* _tmp59_;
						gchar* _tmp60_;
						gchar* _tmp61_;
						const gchar* _tmp62_;
						gchar* _tmp63_;
						gchar* _tmp64_;
						_tmp53_ = ((Main*) self)->lbl_video;
						_tmp54_ = previous;
						_tmp55_ = g_strconcat (_tmp54_, "\n ", NULL);
						_tmp56_ = _tmp55_;
						_tmp57_ = vtype;
						_tmp58_ = g_strconcat (_tmp56_, _tmp57_, NULL);
						_tmp59_ = _tmp58_;
						_tmp60_ = g_strconcat (_tmp59_, ": ", NULL);
						_tmp61_ = _tmp60_;
						_tmp62_ = info;
						_tmp63_ = g_strconcat (_tmp61_, _tmp62_, NULL);
						_tmp64_ = _tmp63_;
						gtk_label_set_text (_tmp53_, _tmp64_);
						_g_free0 (_tmp64_);
						_g_free0 (_tmp61_);
						_g_free0 (_tmp59_);
						_g_free0 (_tmp56_);
					} else {
						const gchar* _tmp65_;
						gint _tmp66_ = 0;
						GtkLabel* _tmp67_;
						const gchar* _tmp68_;
						gchar* _tmp69_;
						gchar* _tmp70_;
						const gchar* _tmp71_;
						gchar* _tmp72_;
						gchar* _tmp73_;
						_tmp65_ = info;
						_tmp66_ = atoi (_tmp65_);
						ns_widgets_feedback_original_height = _tmp66_;
						_tmp67_ = ((Main*) self)->lbl_video;
						_tmp68_ = previous;
						_tmp69_ = g_strconcat (_tmp68_, "x", NULL);
						_tmp70_ = _tmp69_;
						_tmp71_ = info;
						_tmp72_ = g_strconcat (_tmp70_, _tmp71_, NULL);
						_tmp73_ = _tmp72_;
						gtk_label_set_text (_tmp67_, _tmp73_);
						_g_free0 (_tmp73_);
						_g_free0 (_tmp70_);
					}
				}
				_g_free0 (vtype);
			}
		}
	}
	_tmp74_ = ((Main*) self)->lbl_audio;
	gtk_label_set_text (_tmp74_, "Audio");
	_tmp75_ = required_audioinfo;
	_tmp75__length1 = required_audioinfo_length1;
	{
		gchar** atype_collection = NULL;
		gint atype_collection_length1 = 0;
		gint _atype_collection_size_ = 0;
		gint atype_it = 0;
		atype_collection = _tmp75_;
		atype_collection_length1 = _tmp75__length1;
		for (atype_it = 0; atype_it < _tmp75__length1; atype_it = atype_it + 1) {
			gchar* _tmp76_;
			gchar* atype = NULL;
			_tmp76_ = g_strdup (atype_collection[atype_it]);
			atype = _tmp76_;
			{
				JsonObject* _tmp77_;
				const gchar* _tmp78_;
				gchar* _tmp79_ = NULL;
				GtkLabel* _tmp80_;
				const gchar* _tmp81_ = NULL;
				gchar* _tmp82_;
				GtkLabel* _tmp83_;
				const gchar* _tmp84_;
				gchar* _tmp85_;
				gchar* _tmp86_;
				const gchar* _tmp87_;
				gchar* _tmp88_;
				gchar* _tmp89_;
				gchar* _tmp90_;
				gchar* _tmp91_;
				const gchar* _tmp92_;
				gchar* _tmp93_;
				gchar* _tmp94_;
				_tmp77_ = object;
				_tmp78_ = atype;
				_tmp79_ = ns_widgets_feedback_get_specific_info_of_source (self, _tmp77_, "audio", _tmp78_);
				_g_free0 (info);
				info = _tmp79_;
				_tmp80_ = ((Main*) self)->lbl_audio;
				_tmp81_ = gtk_label_get_text (_tmp80_);
				_tmp82_ = g_strdup (_tmp81_);
				_g_free0 (previous);
				previous = _tmp82_;
				_tmp83_ = ((Main*) self)->lbl_audio;
				_tmp84_ = previous;
				_tmp85_ = g_strconcat (_tmp84_, "\n ", NULL);
				_tmp86_ = _tmp85_;
				_tmp87_ = atype;
				_tmp88_ = g_strconcat (_tmp86_, _tmp87_, NULL);
				_tmp89_ = _tmp88_;
				_tmp90_ = g_strconcat (_tmp89_, ": ", NULL);
				_tmp91_ = _tmp90_;
				_tmp92_ = info;
				_tmp93_ = g_strconcat (_tmp91_, _tmp92_, NULL);
				_tmp94_ = _tmp93_;
				gtk_label_set_text (_tmp83_, _tmp94_);
				_g_free0 (_tmp94_);
				_g_free0 (_tmp91_);
				_g_free0 (_tmp89_);
				_g_free0 (_tmp86_);
				_g_free0 (atype);
			}
		}
	}
	_tmp95_ = ((Main*) self)->lbl_other;
	gtk_label_set_text (_tmp95_, "Other Details");
	_tmp96_ = required_otherinfo;
	_tmp96__length1 = required_otherinfo_length1;
	{
		gchar** otype_collection = NULL;
		gint otype_collection_length1 = 0;
		gint _otype_collection_size_ = 0;
		gint otype_it = 0;
		otype_collection = _tmp96_;
		otype_collection_length1 = _tmp96__length1;
		for (otype_it = 0; otype_it < _tmp96__length1; otype_it = otype_it + 1) {
			gchar* _tmp97_;
			gchar* otype = NULL;
			_tmp97_ = g_strdup (otype_collection[otype_it]);
			otype = _tmp97_;
			{
				JsonObject* _tmp98_;
				const gchar* _tmp99_;
				gchar* _tmp100_ = NULL;
				GtkLabel* _tmp101_;
				const gchar* _tmp102_ = NULL;
				gchar* _tmp103_;
				GtkLabel* _tmp104_;
				const gchar* _tmp105_;
				gchar* _tmp106_;
				gchar* _tmp107_;
				const gchar* _tmp108_;
				gchar* _tmp109_;
				gchar* _tmp110_;
				gchar* _tmp111_;
				gchar* _tmp112_;
				const gchar* _tmp113_;
				gchar* _tmp114_;
				gchar* _tmp115_;
				_tmp98_ = object;
				_tmp99_ = otype;
				_tmp100_ = ns_widgets_feedback_get_specific_info_of_source (self, _tmp98_, _tmp99_, "");
				_g_free0 (info);
				info = _tmp100_;
				_tmp101_ = ((Main*) self)->lbl_other;
				_tmp102_ = gtk_label_get_text (_tmp101_);
				_tmp103_ = g_strdup (_tmp102_);
				_g_free0 (previous);
				previous = _tmp103_;
				_tmp104_ = ((Main*) self)->lbl_other;
				_tmp105_ = previous;
				_tmp106_ = g_strconcat (_tmp105_, "\n ", NULL);
				_tmp107_ = _tmp106_;
				_tmp108_ = otype;
				_tmp109_ = g_strconcat (_tmp107_, _tmp108_, NULL);
				_tmp110_ = _tmp109_;
				_tmp111_ = g_strconcat (_tmp110_, ": ", NULL);
				_tmp112_ = _tmp111_;
				_tmp113_ = info;
				_tmp114_ = g_strconcat (_tmp112_, _tmp113_, NULL);
				_tmp115_ = _tmp114_;
				gtk_label_set_text (_tmp104_, _tmp115_);
				_g_free0 (_tmp115_);
				_g_free0 (_tmp112_);
				_g_free0 (_tmp110_);
				_g_free0 (_tmp107_);
				_g_free0 (otype);
			}
		}
	}
	_tmp116_ = ns_widgets_feedback_original_width;
	if (_tmp116_ > 0) {
		GtkInfoBar* _tmp117_;
		GtkLabel* _tmp118_;
		GtkInfoBar* _tmp119_;
		gchar* _tmp120_;
		gchar* _tmp121_;
		gchar* _tmp122_;
		gchar* _tmp123_;
		gchar** _tmp124_ = NULL;
		gchar** sbtns;
		gint sbtns_length1;
		gint _sbtns_size_;
		gchar** _tmp125_;
		gint _tmp125__length1;
		GtkBuilder* _tmp132_;
		GObject* _tmp133_ = NULL;
		GtkAdjustment* _tmp134_;
		GtkAdjustment* adjust;
		GtkBuilder* _tmp135_;
		GObject* _tmp136_ = NULL;
		GtkEntry* _tmp137_;
		GtkEntry* entry;
		GtkAdjustment* _tmp138_;
		gint _tmp139_;
		GtkEntry* _tmp140_;
		gint _tmp141_;
		gchar* _tmp142_ = NULL;
		gchar* _tmp143_;
		_tmp117_ = ((Main*) self)->error_infbar;
		gtk_widget_destroy ((GtkWidget*) _tmp117_);
		_tmp118_ = ((Main*) self)->lbl_other;
		gtk_widget_show ((GtkWidget*) _tmp118_);
		_tmp119_ = ((Main*) self)->infobar;
		gtk_widget_show ((GtkWidget*) _tmp119_);
		_tmp120_ = g_strdup ("adjust_crop0");
		_tmp121_ = g_strdup ("adjust_crop1");
		_tmp122_ = g_strdup ("adjust_crop2");
		_tmp123_ = g_strdup ("adjust_crop3");
		_tmp124_ = g_new0 (gchar*, 4 + 1);
		_tmp124_[0] = _tmp120_;
		_tmp124_[1] = _tmp121_;
		_tmp124_[2] = _tmp122_;
		_tmp124_[3] = _tmp123_;
		sbtns = _tmp124_;
		sbtns_length1 = 4;
		_sbtns_size_ = sbtns_length1;
		_tmp125_ = sbtns;
		_tmp125__length1 = sbtns_length1;
		{
			gchar** spinbutton_collection = NULL;
			gint spinbutton_collection_length1 = 0;
			gint _spinbutton_collection_size_ = 0;
			gint spinbutton_it = 0;
			spinbutton_collection = _tmp125_;
			spinbutton_collection_length1 = _tmp125__length1;
			for (spinbutton_it = 0; spinbutton_it < _tmp125__length1; spinbutton_it = spinbutton_it + 1) {
				gchar* _tmp126_;
				gchar* spinbutton = NULL;
				_tmp126_ = g_strdup (spinbutton_collection[spinbutton_it]);
				spinbutton = _tmp126_;
				{
					GtkBuilder* _tmp127_;
					const gchar* _tmp128_;
					GObject* _tmp129_ = NULL;
					GtkAdjustment* _tmp130_;
					GtkAdjustment* crop_sbtn;
					GtkAdjustment* _tmp131_;
					_tmp127_ = ((Main*) self)->builder;
					_tmp128_ = spinbutton;
					_tmp129_ = gtk_builder_get_object (_tmp127_, _tmp128_);
					_tmp130_ = _g_object_ref0 (GTK_IS_ADJUSTMENT (_tmp129_) ? ((GtkAdjustment*) _tmp129_) : NULL);
					crop_sbtn = _tmp130_;
					_tmp131_ = crop_sbtn;
					gtk_adjustment_set_value (_tmp131_, (gdouble) 0);
					_g_object_unref0 (crop_sbtn);
					_g_free0 (spinbutton);
				}
			}
		}
		ns_widgets_feedback_update_resolution (self);
		_tmp132_ = ((Main*) self)->builder;
		_tmp133_ = gtk_builder_get_object (_tmp132_, "adjust_basics1");
		_tmp134_ = _g_object_ref0 (GTK_IS_ADJUSTMENT (_tmp133_) ? ((GtkAdjustment*) _tmp133_) : NULL);
		adjust = _tmp134_;
		_tmp135_ = ((Main*) self)->builder;
		_tmp136_ = gtk_builder_get_object (_tmp135_, "e_end_min");
		_tmp137_ = _g_object_ref0 (GTK_IS_ENTRY (_tmp136_) ? ((GtkEntry*) _tmp136_) : NULL);
		entry = _tmp137_;
		_tmp138_ = adjust;
		_tmp139_ = ns_widgets_feedback_sec;
		gtk_adjustment_set_value (_tmp138_, (gdouble) _tmp139_);
		_tmp140_ = entry;
		_tmp141_ = ns_widgets_feedback_min;
		_tmp142_ = g_strdup_printf ("%d", _tmp141_);
		_tmp143_ = _tmp142_;
		gtk_entry_set_text (_tmp140_, _tmp143_);
		_g_free0 (_tmp143_);
		_g_object_unref0 (entry);
		_g_object_unref0 (adjust);
		sbtns = (_vala_array_free (sbtns, sbtns_length1, (GDestroyNotify) g_free), NULL);
	} else {
		GtkInfoBar* _tmp144_;
		_tmp144_ = ((Main*) self)->infobar;
		gtk_widget_destroy ((GtkWidget*) _tmp144_);
		main_built_infbar_layout ((Main*) self, GTK_MESSAGE_ERROR, "No valid video file found! \n" "Possible reasons: video codec unknown or malformed video file!\n", "");
	}
	_g_object_unref0 (box);
	_g_object_unref0 (targetfield);
	_g_free0 (examplefile);
	_g_free0 (previous);
	_g_free0 (info);
	_g_free0 (selection);
	required_otherinfo = (_vala_array_free (required_otherinfo, required_otherinfo_length1, (GDestroyNotify) g_free), NULL);
	required_audioinfo = (_vala_array_free (required_audioinfo, required_audioinfo_length1, (GDestroyNotify) g_free), NULL);
	required_videoinfo = (_vala_array_free (required_videoinfo, required_videoinfo_length1, (GDestroyNotify) g_free), NULL);
	__vala_JsonObject_free0 (object);
}


static void ns_widgets_feedback_update_resolution (NSWidgetsFeedback* self) {
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkSpinButton* _tmp2_;
	GtkSpinButton* height_sbtn;
	GtkBuilder* _tmp3_;
	GObject* _tmp4_ = NULL;
	GtkScale* _tmp5_;
	GtkScale* scale;
	GtkBuilder* _tmp6_;
	GObject* _tmp7_ = NULL;
	GtkEntry* _tmp8_;
	GtkEntry* width_entry;
	g_return_if_fail (self != NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "scale_quality4");
	_tmp2_ = _g_object_ref0 (GTK_IS_SPIN_BUTTON (_tmp1_) ? ((GtkSpinButton*) _tmp1_) : NULL);
	height_sbtn = _tmp2_;
	_tmp3_ = ((Main*) self)->builder;
	_tmp4_ = gtk_builder_get_object (_tmp3_, "scale_scale");
	_tmp5_ = _g_object_ref0 (GTK_IS_SCALE (_tmp4_) ? ((GtkScale*) _tmp4_) : NULL);
	scale = _tmp5_;
	_tmp6_ = ((Main*) self)->builder;
	_tmp7_ = gtk_builder_get_object (_tmp6_, "e_quality0");
	_tmp8_ = _g_object_ref0 (GTK_IS_ENTRY (_tmp7_) ? ((GtkEntry*) _tmp7_) : NULL);
	width_entry = _tmp8_;
	ns_widgets_feedback_update_resolution_values (self, height_sbtn, scale, width_entry);
	_g_object_unref0 (width_entry);
	_g_object_unref0 (scale);
	_g_object_unref0 (height_sbtn);
}


static void ns_widgets_feedback_update_resolution_without_builder (NSWidgetsFeedback* self, GtkGrid* grid_res) {
	GtkGrid* _tmp0_;
	GtkWidget* _tmp1_ = NULL;
	GtkSpinButton* _tmp2_;
	GtkSpinButton* height_sbtn;
	GtkGrid* _tmp3_;
	GtkWidget* _tmp4_ = NULL;
	GtkScale* _tmp5_;
	GtkScale* scale;
	GtkGrid* _tmp6_;
	GtkWidget* _tmp7_ = NULL;
	GtkEntry* _tmp8_;
	GtkEntry* width_entry;
	g_return_if_fail (self != NULL);
	g_return_if_fail (grid_res != NULL);
	_tmp0_ = grid_res;
	_tmp1_ = gtk_grid_get_child_at (_tmp0_, 1, 1);
	_tmp2_ = _g_object_ref0 (GTK_IS_SPIN_BUTTON (_tmp1_) ? ((GtkSpinButton*) _tmp1_) : NULL);
	height_sbtn = _tmp2_;
	_tmp3_ = grid_res;
	_tmp4_ = gtk_grid_get_child_at (_tmp3_, 0, 0);
	_tmp5_ = _g_object_ref0 (GTK_IS_SCALE (_tmp4_) ? ((GtkScale*) _tmp4_) : NULL);
	scale = _tmp5_;
	_tmp6_ = grid_res;
	_tmp7_ = gtk_grid_get_child_at (_tmp6_, 0, 1);
	_tmp8_ = _g_object_ref0 (GTK_IS_ENTRY (_tmp7_) ? ((GtkEntry*) _tmp7_) : NULL);
	width_entry = _tmp8_;
	ns_widgets_feedback_update_resolution_values (self, height_sbtn, scale, width_entry);
	_g_object_unref0 (width_entry);
	_g_object_unref0 (scale);
	_g_object_unref0 (height_sbtn);
}


static void ns_widgets_feedback_update_resolution_values (NSWidgetsFeedback* self, GtkSpinButton* height_sbtn, GtkScale* scale, GtkEntry* width_entry) {
	gint _tmp0_;
	NSWidgetsFeedback_Crop _tmp1_;
	gint _tmp2_;
	NSWidgetsFeedback_Crop _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	NSWidgetsFeedback_Crop _tmp6_;
	gint _tmp7_;
	NSWidgetsFeedback_Crop _tmp8_;
	gint _tmp9_;
	GtkSpinButton* _tmp10_;
	GtkAdjustment* _tmp11_ = NULL;
	GtkAdjustment* _tmp12_;
	GtkAdjustment* adjust;
	gint _tmp13_;
	GtkScale* _tmp14_;
	gdouble _tmp15_ = 0.0;
	gchar* _tmp16_ = NULL;
	gchar* scale_info;
	gint _tmp17_ = 0;
	gint _tmp18_;
	gint new_width;
	gint _tmp19_ = 0;
	gint _tmp20_;
	gint new_height;
	GtkEntry* _tmp21_;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (height_sbtn != NULL);
	g_return_if_fail (scale != NULL);
	g_return_if_fail (width_entry != NULL);
	_tmp0_ = ns_widgets_feedback_original_height;
	_tmp1_ = ns_widgets_feedback_crop;
	_tmp2_ = _tmp1_.top;
	_tmp3_ = ns_widgets_feedback_crop;
	_tmp4_ = _tmp3_.bottom;
	ns_widgets_feedback__height = (_tmp0_ - _tmp2_) - _tmp4_;
	_tmp5_ = ns_widgets_feedback_original_width;
	_tmp6_ = ns_widgets_feedback_crop;
	_tmp7_ = _tmp6_.right;
	_tmp8_ = ns_widgets_feedback_crop;
	_tmp9_ = _tmp8_.left;
	ns_widgets_feedback__width = (_tmp5_ - _tmp7_) - _tmp9_;
	_tmp10_ = height_sbtn;
	_tmp11_ = gtk_spin_button_get_adjustment (_tmp10_);
	_tmp12_ = _g_object_ref0 (GTK_IS_ADJUSTMENT (_tmp11_) ? ((GtkAdjustment*) _tmp11_) : NULL);
	adjust = _tmp12_;
	_tmp13_ = ns_widgets_feedback__height;
	gtk_adjustment_set_upper (adjust, (gdouble) _tmp13_);
	_tmp14_ = scale;
	_tmp15_ = gtk_range_get_value ((GtkRange*) _tmp14_);
	_tmp16_ = double_to_string (_tmp15_ * 1000);
	scale_info = _tmp16_;
	_tmp17_ = atoi (scale_info);
	_tmp18_ = ns_widgets_feedback__width;
	new_width = (_tmp17_ * _tmp18_) / 1000;
	_tmp19_ = atoi (scale_info);
	_tmp20_ = ns_widgets_feedback__height;
	new_height = (_tmp19_ * _tmp20_) / 1000;
	_tmp21_ = width_entry;
	_tmp22_ = g_strdup_printf ("%d", new_width);
	_tmp23_ = _tmp22_;
	gtk_entry_set_text (_tmp21_, _tmp23_);
	_g_free0 (_tmp23_);
	gtk_adjustment_set_value (adjust, (gdouble) new_height);
	_g_free0 (scale_info);
	_g_object_unref0 (adjust);
}


static void __lambda5_ (NSWidgetsFeedback* self) {
	GtkInfoBar* _tmp0_;
	_tmp0_ = ((Main*) self)->infobar;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
}


static void ___lambda5__gtk_info_bar_response (GtkInfoBar* _sender, gint response_id, gpointer self) {
	__lambda5_ (self);
}


static void ns_widgets_feedback_built_infbar_info_layout (NSWidgetsFeedback* self) {
	GtkInfoBar* _tmp0_;
	GtkInfoBar* _tmp1_;
	GtkInfoBar* _tmp2_;
	GtkWidget* _tmp3_ = NULL;
	GtkContainer* _tmp4_;
	GtkContainer* infobar_content;
	GtkGrid* _tmp5_;
	GtkGrid* _tmp6_;
	GtkGrid* grid_video;
	GtkGrid* _tmp7_;
	GtkGrid* _tmp8_;
	GtkGrid* grid_audio;
	GtkGrid* _tmp9_;
	GtkGrid* _tmp10_;
	GtkGrid* grid_other;
	GtkLabel* _tmp11_;
	GtkLabel* _tmp12_;
	GtkLabel* _tmp13_;
	GtkLabel* _tmp14_;
	GtkLabel* _tmp15_;
	GtkLabel* _tmp16_;
	GtkLabel* _tmp17_;
	GtkLabel* _tmp18_;
	GtkLabel* _tmp19_;
	GtkInfoBar* _tmp20_;
	GtkLabel* _tmp21_;
	GtkLabel* _tmp22_;
	GtkLabel* _tmp23_;
	GtkInfoBar* _tmp24_;
	GtkInfoBar* _tmp25_;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkInfoBar*) gtk_info_bar_new ();
	_tmp1_ = g_object_ref_sink (_tmp0_);
	_g_object_unref0 (((Main*) self)->infobar);
	((Main*) self)->infobar = _tmp1_;
	_tmp2_ = ((Main*) self)->infobar;
	_tmp3_ = gtk_info_bar_get_content_area (_tmp2_);
	_tmp4_ = _g_object_ref0 (GTK_IS_CONTAINER (_tmp3_) ? ((GtkContainer*) _tmp3_) : NULL);
	infobar_content = _tmp4_;
	_tmp5_ = (GtkGrid*) gtk_grid_new ();
	_tmp6_ = g_object_ref_sink (_tmp5_);
	grid_video = _tmp6_;
	_tmp7_ = (GtkGrid*) gtk_grid_new ();
	_tmp8_ = g_object_ref_sink (_tmp7_);
	grid_audio = _tmp8_;
	_tmp9_ = (GtkGrid*) gtk_grid_new ();
	_tmp10_ = g_object_ref_sink (_tmp9_);
	grid_other = _tmp10_;
	_tmp11_ = (GtkLabel*) gtk_label_new ("");
	_tmp12_ = g_object_ref_sink (_tmp11_);
	_g_object_unref0 (((Main*) self)->lbl_video);
	((Main*) self)->lbl_video = _tmp12_;
	_tmp13_ = (GtkLabel*) gtk_label_new ("");
	_tmp14_ = g_object_ref_sink (_tmp13_);
	_g_object_unref0 (((Main*) self)->lbl_audio);
	((Main*) self)->lbl_audio = _tmp14_;
	_tmp15_ = (GtkLabel*) gtk_label_new ("");
	_tmp16_ = g_object_ref_sink (_tmp15_);
	_g_object_unref0 (((Main*) self)->lbl_other);
	((Main*) self)->lbl_other = _tmp16_;
	_tmp17_ = ((Main*) self)->lbl_video;
	gtk_grid_attach (grid_video, (GtkWidget*) _tmp17_, 0, 0, 1, 4);
	_tmp18_ = ((Main*) self)->lbl_audio;
	gtk_grid_attach (grid_video, (GtkWidget*) _tmp18_, 1, 0, 1, 3);
	_tmp19_ = ((Main*) self)->lbl_other;
	gtk_grid_attach (grid_other, (GtkWidget*) _tmp19_, 2, 0, 1, 4);
	_tmp20_ = ((Main*) self)->infobar;
	gtk_widget_show ((GtkWidget*) _tmp20_);
	gtk_widget_show ((GtkWidget*) grid_video);
	_tmp21_ = ((Main*) self)->lbl_video;
	gtk_widget_show ((GtkWidget*) _tmp21_);
	gtk_widget_show ((GtkWidget*) grid_audio);
	_tmp22_ = ((Main*) self)->lbl_audio;
	gtk_widget_show ((GtkWidget*) _tmp22_);
	gtk_widget_show ((GtkWidget*) grid_other);
	_tmp23_ = ((Main*) self)->lbl_other;
	gtk_widget_show ((GtkWidget*) _tmp23_);
	_tmp24_ = ((Main*) self)->infobar;
	gtk_info_bar_add_button (_tmp24_, "Hide", (gint) GTK_RESPONSE_CLOSE);
	gtk_container_add (infobar_content, (GtkWidget*) grid_video);
	gtk_container_add (infobar_content, (GtkWidget*) grid_audio);
	gtk_container_add (infobar_content, (GtkWidget*) grid_other);
	_tmp25_ = ((Main*) self)->infobar;
	g_signal_connect_object (_tmp25_, "response", (GCallback) ___lambda5__gtk_info_bar_response, self, 0);
	_g_object_unref0 (grid_other);
	_g_object_unref0 (grid_audio);
	_g_object_unref0 (grid_video);
	_g_object_unref0 (infobar_content);
}


static gchar* ns_widgets_feedback_get_file (NSWidgetsFeedback* self) {
	gchar* result = NULL;
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkFileChooserButton* _tmp2_;
	GtkFileChooserButton* fbtn;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "fbtn_basics0");
	_tmp2_ = _g_object_ref0 (GTK_IS_FILE_CHOOSER_BUTTON (_tmp1_) ? ((GtkFileChooserButton*) _tmp1_) : NULL);
	fbtn = _tmp2_;
	_tmp3_ = gtk_file_chooser_get_filename ((GtkFileChooser*) fbtn);
	result = _tmp3_;
	_g_object_unref0 (fbtn);
	return result;
}


static JsonObject* _vala_JsonObject_copy (JsonObject* self) {
	return g_boxed_copy (json_object_get_type (), self);
}


static gpointer __vala_JsonObject_copy0 (gpointer self) {
	return self ? _vala_JsonObject_copy (self) : NULL;
}


static JsonObject* ns_widgets_feedback_get_parser_object (NSWidgetsFeedback* self, const gchar* source) {
	JsonObject* result = NULL;
	gchar* info = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* command;
	FILE* _tmp5_;
	NSCommandExecution* _tmp6_;
	NSCommandExecution* process;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	JsonObject* _tmp15_;
	JsonObject* dont_throw;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (source != NULL, NULL);
	_tmp0_ = source;
	_tmp1_ = g_strconcat ("ffmpeg2theora --info " "'", _tmp0_, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat (_tmp2_, "'", NULL);
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	command = _tmp4_;
	_tmp5_ = stdout;
	fprintf (_tmp5_, "show info command: %s\n", command);
	_tmp6_ = ns_command_execution_new ();
	process = _tmp6_;
	ns_command_execution_sync_command (process, command);
	_tmp7_ = ns_command_execution_get_info (process);
	_tmp8_ = _tmp7_;
	_tmp9_ = g_strdup (_tmp8_);
	_g_free0 (info);
	info = _tmp9_;
	{
		JsonParser* _tmp10_;
		JsonParser* parser;
		JsonNode* _tmp11_ = NULL;
		JsonObject* _tmp12_ = NULL;
		JsonObject* _tmp13_;
		JsonObject* root_object;
		_tmp10_ = json_parser_new ();
		parser = _tmp10_;
		json_parser_load_from_data (parser, info, (gssize) (-1), &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (parser);
			goto __catch4_g_error;
		}
		_tmp11_ = json_parser_get_root (parser);
		_tmp12_ = json_node_get_object (_tmp11_);
		_tmp13_ = __vala_JsonObject_copy0 (_tmp12_);
		root_object = _tmp13_;
		result = root_object;
		_g_object_unref0 (parser);
		_g_object_unref0 (process);
		_g_free0 (command);
		_g_free0 (info);
		return result;
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* e = NULL;
		FILE* _tmp14_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp14_ = stderr;
		fprintf (_tmp14_, "Error: Something went wrong...\n");
		_g_error_free0 (e);
	}
	__finally4:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (process);
		_g_free0 (command);
		_g_free0 (info);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp15_ = json_object_new ();
	dont_throw = _tmp15_;
	result = dont_throw;
	_g_object_unref0 (process);
	_g_free0 (command);
	_g_free0 (info);
	return result;
}


static gchar* ns_widgets_feedback_get_specific_info_of_source (NSWidgetsFeedback* self, JsonObject* root_o, const gchar* category, const gchar* type) {
	gchar* result = NULL;
	gchar* info = NULL;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (root_o != NULL, NULL);
	g_return_val_if_fail (category != NULL, NULL);
	g_return_val_if_fail (type != NULL, NULL);
	_tmp0_ = type;
	if (g_strcmp0 (_tmp0_, "") == 0) {
		gdouble val = 0.0;
		JsonObject* _tmp1_;
		const gchar* _tmp2_;
		gdouble _tmp3_ = 0.0;
		const gchar* _tmp4_;
		const gchar* _tmp15_;
		_tmp1_ = root_o;
		_tmp2_ = category;
		_tmp3_ = json_object_get_double_member (_tmp1_, _tmp2_);
		val = _tmp3_;
		_tmp4_ = category;
		if (g_strcmp0 (_tmp4_, "size") == 0) {
			gdouble bitrate = 0.0;
			gdouble seconds = 0.0;
			gdouble size = 0.0;
			JsonObject* _tmp5_;
			gdouble _tmp6_ = 0.0;
			JsonObject* _tmp7_;
			gdouble _tmp8_ = 0.0;
			gdouble _tmp9_;
			gdouble _tmp10_;
			gdouble _tmp11_;
			gchar* _tmp12_ = NULL;
			const gchar* _tmp13_;
			gchar* _tmp14_ = NULL;
			_tmp5_ = root_o;
			_tmp6_ = json_object_get_double_member (_tmp5_, "bitrate");
			bitrate = _tmp6_;
			_tmp7_ = root_o;
			_tmp8_ = json_object_get_double_member (_tmp7_, "duration");
			seconds = _tmp8_;
			_tmp9_ = bitrate;
			_tmp10_ = seconds;
			size = ((_tmp9_ * _tmp10_) / 8.0) / 1000.0;
			_tmp11_ = size;
			_tmp12_ = double_to_string (_tmp11_);
			_g_free0 (info);
			info = _tmp12_;
			_tmp13_ = info;
			_tmp14_ = ns_widgets_feedback_cut_strings_of_doubles (self, _tmp13_, " MB");
			result = _tmp14_;
			_g_free0 (info);
			return result;
		}
		_tmp15_ = category;
		if (g_strcmp0 (_tmp15_, "duration") == 0) {
			gdouble _tmp16_;
			gdouble _tmp17_;
			gint _tmp18_;
			gint _tmp19_;
			gchar* _tmp20_ = NULL;
			gchar* _tmp21_;
			gchar* _tmp22_;
			gchar* _tmp23_;
			gint _tmp24_;
			gchar* _tmp25_ = NULL;
			gchar* _tmp26_;
			gchar* _tmp27_;
			gchar* _tmp28_;
			gchar* _tmp29_;
			gchar* _tmp30_;
			_tmp16_ = val;
			ns_widgets_feedback_min = (gint) (_tmp16_ / 60);
			_tmp17_ = val;
			_tmp18_ = ns_widgets_feedback_min;
			ns_widgets_feedback_sec = ((gint) _tmp17_) - (_tmp18_ * 60);
			_tmp19_ = ns_widgets_feedback_min;
			_tmp20_ = g_strdup_printf ("%d", _tmp19_);
			_tmp21_ = _tmp20_;
			_tmp22_ = g_strconcat (_tmp21_, " min ", NULL);
			_tmp23_ = _tmp22_;
			_tmp24_ = ns_widgets_feedback_sec;
			_tmp25_ = g_strdup_printf ("%d", _tmp24_);
			_tmp26_ = _tmp25_;
			_tmp27_ = g_strconcat (_tmp23_, _tmp26_, NULL);
			_tmp28_ = _tmp27_;
			_tmp29_ = g_strconcat (_tmp28_, " sec", NULL);
			_tmp30_ = _tmp29_;
			_g_free0 (_tmp28_);
			_g_free0 (_tmp26_);
			_g_free0 (_tmp23_);
			_g_free0 (_tmp21_);
			result = _tmp30_;
			_g_free0 (info);
			return result;
		} else {
			gdouble _tmp31_;
			gchar* _tmp32_ = NULL;
			const gchar* _tmp33_;
			gchar* _tmp34_ = NULL;
			_tmp31_ = val;
			_tmp32_ = double_to_string (_tmp31_);
			_g_free0 (info);
			info = _tmp32_;
			_tmp33_ = info;
			_tmp34_ = ns_widgets_feedback_cut_strings_of_doubles (self, _tmp33_, " kb/s");
			result = _tmp34_;
			_g_free0 (info);
			return result;
		}
	} else {
		JsonObject* _tmp35_;
		const gchar* _tmp36_;
		JsonArray* _tmp37_ = NULL;
		JsonObject* _tmp38_ = NULL;
		JsonObject* _tmp39_;
		JsonObject* item;
		JsonObject* _tmp40_;
		const gchar* _tmp41_;
		const gchar* _tmp42_ = NULL;
		gchar* _tmp43_;
		const gchar* _tmp44_;
		const gchar* _tmp49_;
		_tmp35_ = root_o;
		_tmp36_ = category;
		_tmp37_ = json_object_get_array_member (_tmp35_, _tmp36_);
		_tmp38_ = json_array_get_object_element (_tmp37_, (guint) 0);
		_tmp39_ = __vala_JsonObject_copy0 (_tmp38_);
		item = _tmp39_;
		_tmp40_ = item;
		_tmp41_ = type;
		_tmp42_ = json_object_get_string_member (_tmp40_, _tmp41_);
		_tmp43_ = g_strdup (_tmp42_);
		_g_free0 (info);
		info = _tmp43_;
		_tmp44_ = info;
		if (_tmp44_ == NULL) {
			JsonObject* _tmp45_;
			const gchar* _tmp46_;
			gint64 _tmp47_ = 0LL;
			gchar* _tmp48_ = NULL;
			_tmp45_ = item;
			_tmp46_ = type;
			_tmp47_ = json_object_get_int_member (_tmp45_, _tmp46_);
			_tmp48_ = g_strdup_printf ("%d", _tmp47_);
			_g_free0 (info);
			info = _tmp48_;
		}
		_tmp49_ = info;
		if (_tmp49_ == NULL) {
			JsonObject* _tmp50_;
			const gchar* _tmp51_;
			gdouble _tmp52_ = 0.0;
			gchar* _tmp53_ = NULL;
			_tmp50_ = item;
			_tmp51_ = type;
			_tmp52_ = json_object_get_double_member (_tmp50_, _tmp51_);
			_tmp53_ = double_to_string (_tmp52_);
			_g_free0 (info);
			info = _tmp53_;
		}
		result = info;
		__vala_JsonObject_free0 (item);
		return result;
	}
	_g_free0 (info);
}


static gchar* ns_widgets_feedback_cut_strings_of_doubles (NSWidgetsFeedback* self, const gchar* info, const gchar* additional) {
	gchar* result = NULL;
	gint count = 0;
	const gchar* _tmp0_;
	gint _tmp1_ = 0;
	const gchar* _tmp2_;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (info != NULL, NULL);
	g_return_val_if_fail (additional != NULL, NULL);
	_tmp0_ = info;
	_tmp1_ = g_utf8_strlen (_tmp0_, (gssize) (-1));
	count = _tmp1_;
	_tmp2_ = info;
	_tmp3_ = string_slice (_tmp2_, (glong) 0, (glong) (count - 12));
	_tmp4_ = _tmp3_;
	_tmp5_ = additional;
	_tmp6_ = g_strconcat (_tmp4_, _tmp5_, NULL);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp4_);
	result = _tmp7_;
	return result;
}


static void __lambda6_ (NSWidgetsFeedback* self, GtkWidget* a) {
	GtkWidget* _tmp0_;
	g_return_if_fail (a != NULL);
	_tmp0_ = a;
	gtk_widget_destroy (_tmp0_);
}


static void ___lambda6__gfunc (gconstpointer data, gpointer self) {
	__lambda6_ (self, data);
}


void on_btn_help_clicked (GtkButton* sender, NSWidgetsFeedback* self) {
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkBox* _tmp2_;
	GtkBox* box;
	GtkBox* _tmp3_;
	GList* _tmp4_ = NULL;
	GList* children;
	GList* _tmp5_;
	GtkBuilder* _tmp6_;
	GObject* _tmp7_ = NULL;
	GtkButton* _tmp8_;
	GtkButton* advice_button;
	GtkBuilder* _tmp9_;
	GObject* _tmp10_ = NULL;
	GtkButton* _tmp11_;
	GtkButton* show_info_button;
	GtkButton* _tmp12_;
	GtkButton* _tmp13_;
	NSCommandExecution* _tmp14_;
	NSCommandExecution* process;
	const gchar* _tmp15_;
	const gchar* _tmp16_;
	gchar* info = NULL;
	GtkBuilder* _tmp38_;
	GObject* _tmp39_ = NULL;
	GtkWidget* _tmp40_;
	GtkWidget* infobar_f2theora;
	GtkBuilder* _tmp41_;
	GObject* _tmp42_ = NULL;
	GtkTextBuffer* _tmp43_;
	GtkTextBuffer* textbuffer_f2theora;
	GtkBuilder* _tmp44_;
	GObject* _tmp45_ = NULL;
	GtkToggleButton* _tmp46_;
	GtkToggleButton* toggle_f2theora;
	GtkToggleButton* _tmp47_;
	gboolean _tmp48_ = FALSE;
	NSCommandExecution* _tmp51_;
	const gchar* _tmp52_;
	const gchar* _tmp53_;
	gchar* _tmp54_;
	GtkTextBuffer* _tmp55_;
	GtkWidget* _tmp56_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "box_on_top_of_sbar");
	_tmp2_ = _g_object_ref0 (GTK_IS_BOX (_tmp1_) ? ((GtkBox*) _tmp1_) : NULL);
	box = _tmp2_;
	_tmp3_ = box;
	_tmp4_ = gtk_container_get_children ((GtkContainer*) _tmp3_);
	children = _tmp4_;
	_tmp5_ = children;
	g_list_foreach (_tmp5_, ___lambda6__gfunc, self);
	_tmp6_ = ((Main*) self)->builder;
	_tmp7_ = gtk_builder_get_object (_tmp6_, "btn_advice");
	_tmp8_ = _g_object_ref0 (GTK_IS_BUTTON (_tmp7_) ? ((GtkButton*) _tmp7_) : NULL);
	advice_button = _tmp8_;
	_tmp9_ = ((Main*) self)->builder;
	_tmp10_ = gtk_builder_get_object (_tmp9_, "btn_show_info");
	_tmp11_ = _g_object_ref0 (GTK_IS_BUTTON (_tmp10_) ? ((GtkButton*) _tmp10_) : NULL);
	show_info_button = _tmp11_;
	_tmp12_ = advice_button;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp12_, TRUE);
	_tmp13_ = show_info_button;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp13_, TRUE);
	_tmp14_ = ns_command_execution_new ();
	process = _tmp14_;
	_tmp15_ = main_get_active_tab ((Main*) self);
	_tmp16_ = _tmp15_;
	if (g_strcmp0 (_tmp16_, "other") == 0) {
		GtkBuilder* _tmp17_;
		GObject* _tmp18_ = NULL;
		GtkWidget* _tmp19_;
		GtkWidget* ibar;
		GtkWidget* _tmp20_;
		GtkBuilder* _tmp21_;
		GObject* _tmp22_ = NULL;
		GtkWidget* _tmp23_;
		GtkWidget* _tmp24_;
		GtkBuilder* _tmp25_;
		GObject* _tmp26_ = NULL;
		GtkWidget* _tmp27_;
		GtkWidget* _tmp28_;
		_tmp17_ = ((Main*) self)->builder;
		_tmp18_ = gtk_builder_get_object (_tmp17_, "infbar_color");
		_tmp19_ = _g_object_ref0 (GTK_IS_WIDGET (_tmp18_) ? ((GtkWidget*) _tmp18_) : NULL);
		ibar = _tmp19_;
		_tmp20_ = ibar;
		gtk_widget_hide (_tmp20_);
		_tmp21_ = ((Main*) self)->builder;
		_tmp22_ = gtk_builder_get_object (_tmp21_, "infbar_terminal");
		_tmp23_ = _g_object_ref0 (GTK_IS_WIDGET (_tmp22_) ? ((GtkWidget*) _tmp22_) : NULL);
		_g_object_unref0 (ibar);
		ibar = _tmp23_;
		_tmp24_ = ibar;
		gtk_widget_hide (_tmp24_);
		_tmp25_ = ((Main*) self)->builder;
		_tmp26_ = gtk_builder_get_object (_tmp25_, "infbar_profiles");
		_tmp27_ = _g_object_ref0 (GTK_IS_WIDGET (_tmp26_) ? ((GtkWidget*) _tmp26_) : NULL);
		_g_object_unref0 (ibar);
		ibar = _tmp27_;
		_tmp28_ = ibar;
		gtk_widget_hide (_tmp28_);
		_g_object_unref0 (ibar);
	} else {
		GtkBuilder* _tmp29_;
		const gchar* _tmp30_;
		const gchar* _tmp31_;
		gchar* _tmp32_;
		gchar* _tmp33_;
		GObject* _tmp34_ = NULL;
		GtkWidget* _tmp35_;
		GtkWidget* _tmp36_;
		GtkWidget* ibar;
		GtkWidget* _tmp37_;
		_tmp29_ = ((Main*) self)->builder;
		_tmp30_ = main_get_active_tab ((Main*) self);
		_tmp31_ = _tmp30_;
		_tmp32_ = g_strconcat ("infbar_", _tmp31_, NULL);
		_tmp33_ = _tmp32_;
		_tmp34_ = gtk_builder_get_object (_tmp29_, _tmp33_);
		_tmp35_ = _g_object_ref0 (GTK_IS_WIDGET (_tmp34_) ? ((GtkWidget*) _tmp34_) : NULL);
		_tmp36_ = _tmp35_;
		_g_free0 (_tmp33_);
		ibar = _tmp36_;
		_tmp37_ = ibar;
		gtk_widget_hide (_tmp37_);
		_g_object_unref0 (ibar);
	}
	_tmp38_ = ((Main*) self)->builder;
	_tmp39_ = gtk_builder_get_object (_tmp38_, "infbar_f2theora_help");
	_tmp40_ = _g_object_ref0 (GTK_IS_WIDGET (_tmp39_) ? ((GtkWidget*) _tmp39_) : NULL);
	infobar_f2theora = _tmp40_;
	_tmp41_ = ((Main*) self)->builder;
	_tmp42_ = gtk_builder_get_object (_tmp41_, "txb_f2theora_help");
	_tmp43_ = _g_object_ref0 (GTK_IS_TEXT_BUFFER (_tmp42_) ? ((GtkTextBuffer*) _tmp42_) : NULL);
	textbuffer_f2theora = _tmp43_;
	_tmp44_ = ((Main*) self)->builder;
	_tmp45_ = gtk_builder_get_object (_tmp44_, "tbtn_show_filters");
	_tmp46_ = _g_object_ref0 (GTK_IS_TOGGLE_BUTTON (_tmp45_) ? ((GtkToggleButton*) _tmp45_) : NULL);
	toggle_f2theora = _tmp46_;
	_tmp47_ = toggle_f2theora;
	_tmp48_ = gtk_toggle_button_get_active (_tmp47_);
	if (_tmp48_ == FALSE) {
		NSCommandExecution* _tmp49_;
		_tmp49_ = process;
		ns_command_execution_sync_command (_tmp49_, "ffmpeg2theora --help");
	} else {
		NSCommandExecution* _tmp50_;
		_tmp50_ = process;
		ns_command_execution_sync_command (_tmp50_, "ffmpeg2theora --pp help");
	}
	_tmp51_ = process;
	_tmp52_ = ns_command_execution_get_info (_tmp51_);
	_tmp53_ = _tmp52_;
	_tmp54_ = g_strdup (_tmp53_);
	_g_free0 (info);
	info = _tmp54_;
	_tmp55_ = textbuffer_f2theora;
	gtk_text_buffer_set_text (_tmp55_, info, -1);
	_tmp56_ = infobar_f2theora;
	gtk_widget_show (_tmp56_);
	_g_object_unref0 (toggle_f2theora);
	_g_object_unref0 (textbuffer_f2theora);
	_g_object_unref0 (infobar_f2theora);
	_g_free0 (info);
	_g_object_unref0 (process);
	_g_object_unref0 (show_info_button);
	_g_object_unref0 (advice_button);
	_g_list_free0 (children);
	_g_object_unref0 (box);
}


void on_tbtn_show_filters_toggled (GtkToggleButton* sender, NSWidgetsFeedback* self) {
	GtkBuilder* _tmp0_;
	GObject* _tmp1_ = NULL;
	GtkTextBuffer* _tmp2_;
	GtkTextBuffer* textbuffer_f2theora;
	gchar* info = NULL;
	NSCommandExecution* _tmp3_;
	NSCommandExecution* process;
	GtkToggleButton* _tmp4_;
	gboolean _tmp5_ = FALSE;
	NSCommandExecution* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	GtkTextBuffer* _tmp12_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	_tmp0_ = ((Main*) self)->builder;
	_tmp1_ = gtk_builder_get_object (_tmp0_, "txb_f2theora_help");
	_tmp2_ = _g_object_ref0 (GTK_IS_TEXT_BUFFER (_tmp1_) ? ((GtkTextBuffer*) _tmp1_) : NULL);
	textbuffer_f2theora = _tmp2_;
	_tmp3_ = ns_command_execution_new ();
	process = _tmp3_;
	_tmp4_ = sender;
	_tmp5_ = gtk_toggle_button_get_active (_tmp4_);
	if (_tmp5_ == TRUE) {
		NSCommandExecution* _tmp6_;
		_tmp6_ = process;
		ns_command_execution_sync_command (_tmp6_, "ffmpeg2theora --pp help");
	} else {
		NSCommandExecution* _tmp7_;
		_tmp7_ = process;
		ns_command_execution_sync_command (_tmp7_, "ffmpeg2theora --help");
	}
	_tmp8_ = process;
	_tmp9_ = ns_command_execution_get_info (_tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = g_strdup (_tmp10_);
	_g_free0 (info);
	info = _tmp11_;
	_tmp12_ = textbuffer_f2theora;
	gtk_text_buffer_set_text (_tmp12_, info, -1);
	_g_object_unref0 (process);
	_g_free0 (info);
	_g_object_unref0 (textbuffer_f2theora);
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		NSWidgetsFeedback * self;
		self = _data2_->self;
		_g_object_unref0 (_data2_->advice_infobar);
		_g_object_unref0 (_data2_->sender);
		_g_object_unref0 (self);
		g_slice_free (Block2Data, _data2_);
	}
}


static void __lambda7_ (Block2Data* _data2_) {
	NSWidgetsFeedback * self;
	GtkButton* _tmp0_;
	self = _data2_->self;
	gtk_widget_destroy ((GtkWidget*) _data2_->advice_infobar);
	_tmp0_ = _data2_->sender;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp0_, TRUE);
}


static void ___lambda7__gtk_info_bar_response (GtkInfoBar* _sender, gint response_id, gpointer self) {
	__lambda7_ (self);
}


void on_btn_advice_clicked (GtkButton* sender, NSWidgetsFeedback* self) {
	Block2Data* _data2_;
	GtkButton* _tmp0_;
	GtkButton* _tmp1_;
	GtkButton* _tmp2_;
	GtkInfoBar* _tmp3_;
	GtkInfoBar* _tmp4_;
	GtkBuilder* _tmp5_;
	GObject* _tmp6_ = NULL;
	GtkBox* _tmp7_;
	GtkBox* box;
	GtkImage* _tmp8_;
	GtkImage* _tmp9_;
	GtkImage* idea;
	GtkWidget* _tmp10_ = NULL;
	GtkContainer* _tmp11_;
	GtkContainer* infobar_content;
	GtkLabel* _tmp12_;
	GtkLabel* _tmp13_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sender != NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_data2_->self = g_object_ref (self);
	_tmp0_ = sender;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_data2_->sender = _tmp1_;
	_tmp2_ = _data2_->sender;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp2_, FALSE);
	_tmp3_ = (GtkInfoBar*) gtk_info_bar_new ();
	_tmp4_ = g_object_ref_sink (_tmp3_);
	_data2_->advice_infobar = GTK_IS_INFO_BAR (_tmp4_) ? ((GtkInfoBar*) _tmp4_) : NULL;
	_tmp5_ = ((Main*) self)->builder;
	_tmp6_ = gtk_builder_get_object (_tmp5_, "box_on_top_of_sbar");
	_tmp7_ = _g_object_ref0 (GTK_IS_BOX (_tmp6_) ? ((GtkBox*) _tmp6_) : NULL);
	box = _tmp7_;
	_tmp8_ = (GtkImage*) gtk_image_new_from_stock (GTK_STOCK_DIALOG_INFO, GTK_ICON_SIZE_DIALOG);
	_tmp9_ = g_object_ref_sink (_tmp8_);
	idea = _tmp9_;
	_tmp10_ = gtk_info_bar_get_content_area (_data2_->advice_infobar);
	_tmp11_ = _g_object_ref0 (GTK_IS_CONTAINER (_tmp10_) ? ((GtkContainer*) _tmp10_) : NULL);
	infobar_content = _tmp11_;
	gtk_widget_show ((GtkWidget*) box);
	g_signal_connect_data (_data2_->advice_infobar, "response", (GCallback) ___lambda7__gtk_info_bar_response, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
	gtk_info_bar_add_button (_data2_->advice_infobar, "Hide", (gint) GTK_RESPONSE_CLOSE);
	gtk_container_add (infobar_content, (GtkWidget*) idea);
	_tmp12_ = ((Main*) self)->advice_label;
	gtk_container_add (infobar_content, (GtkWidget*) _tmp12_);
	gtk_box_pack_end (box, (GtkWidget*) _data2_->advice_infobar, TRUE, TRUE, (guint) 5);
	gtk_widget_show ((GtkWidget*) idea);
	_tmp13_ = ((Main*) self)->advice_label;
	gtk_widget_show ((GtkWidget*) _tmp13_);
	gtk_widget_show ((GtkWidget*) _data2_->advice_infobar);
	_g_object_unref0 (infobar_content);
	_g_object_unref0 (idea);
	_g_object_unref0 (box);
	block2_data_unref (_data2_);
	_data2_ = NULL;
}


gint ns_widgets_feedback_get_width (void) {
	gint result;
	gint _tmp0_;
	_tmp0_ = ns_widgets_feedback__width;
	result = _tmp0_;
	return result;
}


gint ns_widgets_feedback_get_height (void) {
	gint result;
	gint _tmp0_;
	_tmp0_ = ns_widgets_feedback__height;
	result = _tmp0_;
	return result;
}


static NSWidgetsFeedback_Crop* ns_widgets_feedback__crop_dup (const NSWidgetsFeedback_Crop* self) {
	NSWidgetsFeedback_Crop* dup;
	dup = g_new0 (NSWidgetsFeedback_Crop, 1);
	memcpy (dup, self, sizeof (NSWidgetsFeedback_Crop));
	return dup;
}


static void ns_widgets_feedback__crop_free (NSWidgetsFeedback_Crop* self) {
	g_free (self);
}


static GType ns_widgets_feedback__crop_get_type (void) {
	static volatile gsize ns_widgets_feedback__crop_type_id__volatile = 0;
	if (g_once_init_enter (&ns_widgets_feedback__crop_type_id__volatile)) {
		GType ns_widgets_feedback__crop_type_id;
		ns_widgets_feedback__crop_type_id = g_boxed_type_register_static ("NSWidgetsFeedback_Crop", (GBoxedCopyFunc) ns_widgets_feedback__crop_dup, (GBoxedFreeFunc) ns_widgets_feedback__crop_free);
		g_once_init_leave (&ns_widgets_feedback__crop_type_id__volatile, ns_widgets_feedback__crop_type_id);
	}
	return ns_widgets_feedback__crop_type_id__volatile;
}


static void ns_widgets_feedback_class_init (NSWidgetsFeedbackClass * klass) {
	ns_widgets_feedback_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = _vala_ns_widgets_feedback_get_property;
	G_OBJECT_CLASS (klass)->finalize = ns_widgets_feedback_finalize;
	{
		NSWidgetsFeedback_Crop _tmp0_ = {0, 0, 0, 0};
		ns_widgets_feedback_crop = _tmp0_;
	}
}


static void ns_widgets_feedback_instance_init (NSWidgetsFeedback * self) {
}


static void ns_widgets_feedback_finalize (GObject* obj) {
	NSWidgetsFeedback * self;
	self = NS_WIDGETS_FEEDBACK (obj);
	_g_object_unref0 (self->advice_infobar);
	G_OBJECT_CLASS (ns_widgets_feedback_parent_class)->finalize (obj);
}


GType ns_widgets_feedback_get_type (void) {
	static volatile gsize ns_widgets_feedback_type_id__volatile = 0;
	if (g_once_init_enter (&ns_widgets_feedback_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (NSWidgetsFeedbackClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ns_widgets_feedback_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NSWidgetsFeedback), 0, (GInstanceInitFunc) ns_widgets_feedback_instance_init, NULL };
		GType ns_widgets_feedback_type_id;
		ns_widgets_feedback_type_id = g_type_register_static (TYPE_MAIN, "NSWidgetsFeedback", &g_define_type_info, 0);
		g_once_init_leave (&ns_widgets_feedback_type_id__volatile, ns_widgets_feedback_type_id);
	}
	return ns_widgets_feedback_type_id__volatile;
}


static void _vala_ns_widgets_feedback_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	NSWidgetsFeedback * self;
	self = NS_WIDGETS_FEEDBACK (object);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



